if GetLocale()~="deDE" then return end

-- These are the main viewer's lines.

local COLOR_TIP_MOUSE = "|cffeedd99"
local COLOR_TIP_HINT = "|cff99ff00"
local COLOR_TIP = "|cff00ff00"

ZygorGuidesViewer_L("Main", "deDE", function() return {
    ["name"] = "|cffffff88Z|cffffee66y|cffffdd44g|cffffcc22o|cffffbb00r |cffffaa00Guide-Betrachter|r",
    ["name_plain"] = "Zygor Guide-Betrachter",
    ["desc"] = "Haupteinstellungen für Zygor Guides Viewer %s.|n",

    ['welcome_guides'] = "%d Guides sind geladen.",

    ["opt_guide"] = "Guide auswählen:",
    ["opt_guide_steps"] = "Schritte: %d",
    ["opt_guide_author"] = "Autor: %s",
    ["opt_guide_next"] = "Nächster in der Reihe: %s",

    ["opt_report"] = "Fehlerhaften Schritt melden",
    ["opt_report_desc"] = "Erstellt einen Fehlerbericht mit den Details des aktuell angezeigten Schritts. Kopieren/einfügen und an die Guide-Autoren senden.",

    ["opt_visible"] = "Zygor Guides Viewer-Fenster anzeigen",
    ["opt_visible_desc"] = "",
    ["opt_hideincombat"] = "Guides im Kampf ausblenden",
    ["opt_hideincombat_desc"] = "Blendet alle Guide-Fenster während des Kampfes aus, wenn der Bildschirm zu voll wird.",
    
    --["opt_group_main"] = "Main window settings",
    ["opt_opacitymain"] = "Deckkraft",
    ["opt_opacitymain_desc"] = "Deckkraft des Hauptfensters.",
    ["opt_framescale"] = "Skalierung",
    ["opt_framescale_desc"] = "Fenstergröße nach deinen Vorlieben anpassen.",
    ["opt_fontsize"] = "Textgröße",
    ["opt_fontsize_desc"] = "Bevorzugte Textgröße. Die Fensterskalierung beeinflusst diesen Wert ebenfalls.",
    ["opt_fontsecsize"] = "Sekundäre Textgröße",
    ["opt_fontsecsize_desc"] = "Bevorzugte sekundäre Textgröße für zusätzliche Beschreibungen und Hinweise.",
    ["opt_backcolor"] = "Hintergrundfarbe",
    ["opt_backcolor_desc"] = "Hintergrundfarbe des Fensters.",

    ["opt_group_window"] = "Fensterfunktionen",
    --["opt_minimapnotedesc"] = "Show waypoint caption",
    --["opt_minimapnotedesc_desc"] = "Show the relevant waypoint's caption not only on the waypoint's tooltip, but on the mini window as well.",
    --["opt_showgoals"] = "Show step goals",
    --["opt_showgoals_desc"] = "Show step completion goals in the mini window",
    --["opt_autosizemini"] = "Auto-size",
    --["opt_autosizemini_desc"] = "Automatically adjust the height of the mini window.",
    ["opt_miniresizeup"] = "Nach oben vergrößern",
    ["opt_miniresizeup_desc"] = "Dreht die Erweiterungsrichtung um, sodass das Fenster nach oben statt nach unten wächst. Nützlich am unteren Bildschirmrand.",
    ["opt_opacitymini"] = "Hintergrund-Deckkraft",
    ["opt_opacitymini_desc"] = "Deckkraft des Schrittfenster-Hintergrunds.",

    --["opt_showallsteps"] = "Collapsed mode",
    --["opt_showallsteps_desc"] = "Display only the current step and some next steps, instead of the whole guide",

    ["opt_showcountsteps"] = "Schritte anzeigen:",
    ["opt_showcountsteps_desc"] = "Anzahl der anzuzeigenden Schritte.\n|cffffffaaAlle|r zeigt alle Schritte in einer scrollbaren Liste.\n|cffffffaa1-5|r zeigt den aktuellen Schritt oben und passt die Fenstergröße automatisch für einige folgende Schritte an.",
    ["opt_showcountsteps_all"] = "Alle",

    ["opt_group_map"] = "Wegpunkte",
    ["opt_group_map_desc"] = "Diese Einstellungen steuern, wie Zygor Guides Viewer mit Karten-Addons zusammenarbeitet.",
    ["opt_group_map_waypointing"] = "Wegpunkt-Addon",
    ["opt_group_map_waypointing_desc"] = "Wähle das Addon, das Wegpunkte für Zygor Guides Viewer verwalten soll.",
    ["opt_group_addons_builtin"] = "Integrierte Wegpunkte",
    ["opt_group_addons_tomtom"] = "TomTom (Addon)",
    ["opt_group_addons_cart2"] = "Cartographer 2 (Addon)",
    ["opt_group_addons_cart3"] = "Cartographer 3 (Addon)",
    ["opt_group_addons_metamap"] = "MetaMap (Addon)",
    ["opt_group_addons_none"] = "keins",
    ["opt_debug"] = "Fehlersuche",
    ["opt_debug_desc"] = "Debug-Informationen anzeigen.",
    ["opt_debugging"] = "Fehlersuche",
    ["opt_debugging_desc"] = "Debugging-Optionen.",
    --["opt_browse"] = "Toggle windows",
     --["opt_browse_desc"] = "Toggle the visibility of either of Zygor's Guides windows.",

    ["opt_autoskip"] = "Automatisch weiter",
    ["opt_autoskip_desc"] = "Springt automatisch zum nächsten Schritt, wenn alle Bedingungen erfüllt sind. Einige komplexe Schritte müssen eventuell weiterhin manuell übersprungen werden.",

    ["opt_goalicons"] = "Schritt-Symbole anzeigen",
    ["opt_goalicons_desc"] = "Symbole entsprechend dem Fortschrittsstatus anzeigen.",
    ["opt_goalcolorize"] = "Abgeschlossene Schrittzeilen einfärben",
    ["opt_goalcolorize_desc"] = "Abgeschlossene Schrittzeilen vollständig grün einfärben.",
    ["opt_goalbackprogress"] = "Farben nach Fortschrittsprozent anwenden",
    ["opt_goalbackprogress_desc"] = "Teilfortschritt als Zwischenfarben zwischen unvollständig und vollständig anzeigen.|nWenn aus, werden nur die Farben für 'unvollständig' und 'vollständig' verwendet.",

    ["opt_group_step"] = "Schrittziele",

    ["opt_goalbackcolor_desc"] = "Fortschrittsfarben:",
    ["opt_goalbackgrounds"] = "Hintergründe einfärben",
    ["opt_goalbackgrounds_desc"] = "Hintergründe der Schrittzeilen gemäß Fortschritt einfärben.",
    ["opt_goalbackcomplete"] = "Vollständig",
    ["opt_goalbackcomplete_desc"] = "Diese Farbe für vollständige Ziele verwenden.",
    ["opt_goalbackincomplete"] = "Unvollständig",
    ["opt_goalbackincomplete_desc"] = "Diese Farbe für unvollständige Ziele verwenden.",
    ["opt_goalbackimpossible"] = "Unmöglich",
    ["opt_goalbackimpossible_desc"] = "Diese Farbe für derzeit unmögliche Ziele verwenden.",

    ['opt_tooltipsbelow'] = "Zusätzliche Infos in der Zeile anzeigen",
    ['opt_tooltipsbelow_desc'] = "Zusätzliche Informationen zu bestimmten Schrittzeilen können direkt in der Zeile oder als Tooltip beim Überfahren angezeigt werden.",

    ["opt_flash_desc"] = "Fortschrittsbenachrichtigung:",
    ["opt_goalcompletionflash"] = "Ziel bei Abschluss aufblitzen lassen",
    ["opt_goalcompletionflash_desc"] = "Verwendet einen visuellen Aufblitz-Effekt, wenn ein einzelnes Ziel abgeschlossen wird.",
    ["opt_goalupdateflash"] = "Ziel bei Fortschritt aufblitzen lassen",
    ["opt_goalupdateflash_desc"] = "Verwendet einen visuellen Aufblitz-Effekt, wenn ein einzelnes Ziel Fortschritt erhält.",
    ["opt_flashborder"] = "Fenster bei Schrittabschluss aufblitzen lassen",
    ["opt_flashborder_desc"] = "Lässt das gesamte Fenster aufblitzen, wenn ein Schritt abgeschlossen wird.",

    --["opt_colorborder"] = "Color step window border",
    --["opt_colorborder_desc"] = "Use the step window border's color to indicate completion of the whole step.",

    ["opt_group_display"] = "Anzeige",
    ["opt_group_display_desc"] = "Lege fest, wie die Guides angezeigt werden sollen.",

    ["opt_group_data"] = "Gespeicherte Guides",
    ["opt_group_data_desc"] = "Zygor Guides Viewer kann kommerzielle Guides intern speichern, die nicht als eigenständige Addons verteilt werden dürfen.",
    ["opt_group_data_guide"] = "Intern gespeicherte Guides:",
    ["opt_group_data_guide_desc"] = "Wähle einen gespeicherten Guide aus dieser Liste, um ihn zu bearbeiten oder zu löschen. Diese Liste zeigt KEINE separat geladenen Addons.",
    ["opt_group_data_del"] = "Guide löschen",
    ["opt_group_data_del_desc"] = "Löscht den ausgewählten Guide aus dem internen Speicher.",
    ["opt_group_data_edit"] = "Guide bearbeiten",
    ["opt_group_data_edit_desc"] = "Lädt den ausgewählten Guide in das Editorfenster unten, um ihn direkt zu bearbeiten.",
    ["opt_group_data_entry"] = "Guide-Daten:",
    ["opt_group_data_entry_desc"] = "Füge hier einen neuen Guide ein (die Schritte müssen in folgendes Format:|nguide Title Of Guide|nsteps...|nsteps...|nend\n); das Einfügen und Parsen eines großen Guides (>30kB) kann einige Sekunden dauern.",

    ['opt_windowlocked'] = "Fenster sperren",
    ['opt_windowlocked_desc'] = "Sperrt das Fenster, sodass es nicht mehr mit der Maus verschoben werden kann.\nNur Schaltflächen bleiben aktiv.",
    ['opt_hideborder'] = "Rahmen automatisch ausblenden",
    ['opt_hideborder_desc'] = "Blendet Rahmen und Schaltflächen automatisch aus, wenn die Maus nicht über dem Fenster ist.\nFahre kurz über den Fenstertitel, um sie wieder einzublenden.",

    ['opt_skin'] = "Fensterstil",
    ['opt_skin_desc'] = "Wähle einen Stil für die Fensterdekoration passend zur Benutzeroberfläche.",
    ['opt_skin_violet'] = "|cffee55ffViolett",
    ['opt_skin_green'] = "|cff88ff88Grün",
    ['opt_skin_blue'] = "|cff99aaffBlau",
    ['opt_skin_orange'] = "|cffffbb00Orange",
    ["opt_skinpanel_title"] = "Fensterstil",
    ["opt_skinpanel_desc"] = "Wähle das visuelle Erscheinungsbild für den Guide-Viewer.",
    ["opt_skinpanel_intro"] = "Wähle zuerst den allgemeinen Look des Viewers und passe dann Größe, Transparenz und Text an. Remaster bleibt der empfohlene Standard-Skin, während Retail stärker an die Blizzard-Optik angelehnt ist.",
    ["opt_skinpanel_skin"] = "Fensterstil",
    ["opt_skinpanel_skin_desc"] = "Wähle einen Skin und eine Farbvariante.",
    ["opt_skinpanel_appearance_header"] = "Darstellung",
    ["opt_skinpanel_appearance_desc"] = "Passe Viewer-Skalierung, Textgröße und Fenstertransparenz an.",
    ["opt_skinpanel_colors_header"] = "Farben",
    ["opt_skinpanel_colors_desc"] = "Passe die Stärke des Fensterhintergrunds für die gewählte Skin-Variante an.",
    ["opt_skinpanel_advanced_header"] = "Erweitert",
    ["opt_skinpanel_advanced_desc"] = "Weniger häufig genutzte Anzeigeoptionen, die Fensterlayout und Schrittpräsentation beeinflussen.",

    ['opt_backopacity'] = "Hintergrund-Deckkraft",
    ['opt_backopacity_desc'] = "Deckkraft des Fensterhintergrunds.",

    --["mainframe_guide"] = "Select a guide:",
    --["mainframe_notloaded"] = "No leveling guides are loaded.|n|nPlease go to http://zygorguides.com to purchase Zygor's 1-80 Leveling Guides, or load some third-party guides.|n|nIf you're sure you have installed some guides, ask their authors for installation troubleshooting.",
    --["mainframe_notselected"] = "%d guides are loaded.|nPlease select a guide from the list above.",


    ["report_title"] = "Drücke Strg+C, um diesen Bericht zu kopieren.|nSende ihn dann an den Autor von |cffffffff%s|r,|nan |cffffffff%s|r.",
    ["report_notitle"] = "|cffff8888(unbenannter Guide?)|r",
    ["report_noauthor"] = "|cffff8888(keine Adresse verfügbar)|r",


    ["opt_mapbutton"] = "Minikarten-Schaltfläche anzeigen",
    ["opt_mapbutton_desc"] = "Zeigt die Schaltfläche von Zygor Guides Viewer neben der Minikarte an",

    ["minimap_tooltip"] = COLOR_TIP_MOUSE.."Klick|r zum Ein-/Ausblenden des Guide-Fensters|n"..COLOR_TIP_MOUSE.."Rechtsklick|r für Einstellungen|n", --..COLOR_TIP_MOUSE.."Drag|r to move icon"


    ["waypointaddon_set"] = "Wegpunkt-Addon ausgewählt: %s",
    ["waypointaddon_connecting"] = "Verbinde mit Wegpunkt-Addon: %s",
    ["waypointaddon_connected"] = "Erfolgreich mit %s verbunden.",
    ["waypointaddon_fail"] = "Verbindung mit %s fehlgeschlagen.",
    ['waypoint_step'] = "Stufe %s",

    ["checkmap"] = "Prüfe deine Karte.",

    ["initialized"] = 'Initialisiert.',

    ["miniframe_notloaded"] = "Keine Leveling-Guides sind geladen.|n|nBesuche http://zygorguides.com, um Zygors 1-80 Leveling Guides zu kaufen, oder lade Guides von Drittanbietern.|n|nWenn du sicher bist, dass Guides installiert sind, frage deren Autoren nach Installationshilfe.",
    ["miniframe_notselected"] = "Derzeit ist kein Guide ausgewählt.\nKlicke auf die blinkende Schaltfläche oben, um einen Guide auszuwählen.",

    ['frame_locked'] = "Fenster fixiert",
    ['frame_unlock'] = COLOR_TIP_MOUSE.."Linksklick|r zum Freigeben",
    ['frame_unlocked'] = "Fenster frei",
    ['frame_lock'] = COLOR_TIP_MOUSE.."Linksklick|r zum Fixieren",
    ['frame_settings'] = "Optionen",
    ['frame_settings1'] = COLOR_TIP_MOUSE.."Linksklick|r für Menü",
    ['frame_settings2'] = COLOR_TIP_MOUSE.."Rechtsklick|r für Optionen",
    ['frame_minimized'] = "Zeigt |cffffffff%d|r Schritt(e)",
    ['frame_maximized'] = "Zeigt alle Schritte",
    ['frame_minimize'] = COLOR_TIP_MOUSE.."Linksklick|r für nur |cffffffff%d|r anzeigen",
    ['frame_maximize'] = COLOR_TIP_MOUSE.."Linksklick|r für alles anzeigen",
    ['frame_stepnav_prev'] = "Vorheriger Schritt",
    ['frame_stepnav_prev_click'] = COLOR_TIP_MOUSE.."Linksklick|r: zurück",
    ['frame_stepnav_next'] = "Nächster Schritt",
    ['frame_stepnav_next_click'] = COLOR_TIP_MOUSE.."Linksklick|r: weiter",
    ['frame_stepnav_next_right'] = COLOR_TIP_MOUSE.."Rechtsklick|r: vorspulen",
    ['frame_section'] = "Aktueller Guide",
    ['frame_section_click'] = COLOR_TIP_MOUSE.."Klick|r zum Auswählen",


    ['tooltip_tip'] = COLOR_TIP_HINT.."%s|r",
    ['tooltip_waypoint'] = COLOR_TIP_MOUSE.."Klick|r"..COLOR_TIP.." um Wegpunkt zu setzen: |cffffaa00%s|r",
    ['tooltip_waypoint_coords'] = "Position: |cffffaa00%s|r",

    ["message_errorloading_full"] = "|cffff4444Fehler|r beim Laden von Guide |cffaaffaa%s|r\nZeile %d: %s\nFehler: %s",
    ["message_errorloading_brief"] = "|cffff4444Fehler|r beim Laden von Guide |cffaaffaa%s|r",
    ["message_loadedguide"] = "Guide aktiviert: |cffaaffaa%s|r",
    ["message_missingguide"] = "|cffff4444Fehlender|r Guide: |cffaaffaa%s|r",
    ["title_noguide"] = "Zygor Guides Viewer (kein Guide geladen)",

	['step_num'] = "|cffaaaaaa%s|cff888888.|r ",
    ['step_level'] = "|cffaaccaaStufe: |cffcceecc%s|cffaaccaa|r ",

    ["questtitle"] = "`%s'",
    ["questtitle_part"] = "`%s' (Teil %s)",
    ["coords"] = "%d,%d",
    ["map_coords"] = "%s %d,%d",

    ["stepgoal_home"] = "Setze dein Zuhause auf %s",
    ["stepgoal_flightpath"] = "Nimm den Flugpunkt %s",

    ["stepgoal_accept"] = "Nimm %s an",
    ["stepgoal_turn in"] = "Gib %s ab",
    ["stepgoal_talk to"] = "Sprich mit %s",
    ["stepgoal_kill"] = "Töte %s",
    ["stepgoal_kill #"] = "Töte %s %s",
    ["stepgoal_goal"] = "%s",
    ["stepgoal_goal #"] = "%s %s",
    ["stepgoal_get"] = "Besorge %s",
    ["stepgoal_get #"] = "Besorge %s %s",
    ["stepgoal_ding"] = "Du solltest jetzt Stufe %s sein.|n Falls nicht, kämpfe noch etwas, bis du sie erreicht hast.",
    ["stepgoal_go to"] = "Gehe zu %s",
    ["stepgoal_also at"] = "Auch bei %s",
    ["stepgoal_hearth to"] = "Ruhestein nach %s",
    ["stepgoal_collect"] = "Sammle %s",
    ["stepgoal_collect #"] = "Sammle %s %s",
    ["stepgoal_buy"] = "Kaufe %s %s",
    ["stepgoal_fpath"] = "Nimm den Flugpunkt %s",
    ["stepgoal_use"] = "Benutze %s",
    ["stepgoal_petaction"] = "Tieraktion benutzen: %s",
    ["stepgoal_havebuff"] = "Erhalte Buff/Debuff '%s'",
    ["stepgoal_nobuff"] = "Verliere Buff/Debuff '%s'",
    ["stepgoal_invehicle"] = "Steige in ein Fahrzeug",
    ["stepgoal_outvehicle"] = "Verlasse das Fahrzeug",
    ["stepgoal_equipped"] = "Lege %s an",
    ["stepgoal_at_suff"] = " (%s)",

    ["completion_collect"] = "(%s/%s)",
    ["completion_goal"] = "(%s/%s)",
    ["completion_ding"] = "(%s%%)",
    --["completion_(done)"] = "(erledigt)",

--[[
    ["stepgoalshort_complete"] = "fertig",
    ["stepgoalshort_incomplete"] = "offen",
    ["stepgoalshort_questgoal"] = "(%d/%d)",
    ["stepgoalshort_level"] = "(%d%%)",
--]]

    ["step_req"] = "Schritt nur gültig für: %s",


    ["map_highlight"] = "Hervorheben",

    ["stepreq"] = "Schritt Klassen-/Rassenanforderung: ",
    ["stepreqor"] = " oder ",

    ["opt_do_searchforgoal"] = "Erfüllbares Ziel finden",
    ["searching_for_goal_success"] = "Ein erfüllbares Ziel wurde für dich gefunden: %s. Das kann ein guter Einstiegspunkt im Guide sein.",
    ["searching_for_goal_failed"] = "Kein erfüllbares Ziel gefunden. Probiere einen anderen Guide oder Abschnitt, nimm ein paar Quests an oder starte die Suche vom Abschnittsbeginn (die Suche geht nur vorwärts).",

    ["going"] = "%d%% bis %s",
    ["miniframe_loading"] = "Lade Guides: %d%%",
    ["menu_last"] = "Zuletzt verwendete Guides",
    ["menu_last_entry"] = "%s |cffaaffaa%d|r",
    ["gb_window_title"] = "Guide-Browser",
    ["gb_addon_title"] = "Zygor Guides Viewer Remastered",
    ["gb_root"] = "Hauptmenü",
    ["gb_search"] = "Suche",
    ["gb_folders"] = "Ordner",
    ["gb_guides"] = "Guides",
    ["gb_load_guide"] = "Guide laden",
    ["gb_open_legacy"] = "Alten Picker öffnen",
    ["gb_path_format"] = "Pfad: %s",
    ["gb_select_guide"] = "Guide auswählen",
    ["gb_select_guide_from_list"] = "Wähle einen Guide aus der Liste.",
    ["gb_select_settings_page"] = "Wähle eine Einstellungsseite",
    ["gb_all_guides"] = "Alle Guides",
    ["gb_other"] = "Andere",
    ["gb_unknown"] = "unbekannt",
    ["gb_none"] = "keine",
    ["gb_folder_format"] = "Ordner: %s",
    ["gb_progress_format"] = "Fortschritt: %d%%",
    ["gb_guides_count_format"] = "%d Guides",
    ["gb_current_meta_format"] = "Schritt %d / %d  |  %s",
    ["gb_detail_meta_format"] = "Schritte: %d\nAutor: %s\nNächster: %s",
    ["gb_tab_home"] = "Start",
    ["gb_tab_featured"] = "Empfohlen",
    ["gb_tab_current"] = "Aktuell",
    ["gb_tab_recent"] = "Zuletzt",
    ["gb_tab_options"] = "Optionen",
    ["gb_cat_leveling"] = "Leveln",
    ["gb_cat_dungeons"] = "Dungeons",
    ["gb_cat_daily"] = "Täglich",
    ["gb_cat_events"] = "Events",
    ["gb_cat_reputations"] = "Ruf",
    ["gb_cat_gold"] = "Gold",
    ["gb_cat_professions"] = "Berufe",
    ["gb_cat_petsmounts"] = "Haustiere & Reittiere",
    ["gb_cat_titles"] = "Titel",
    ["gb_cat_achievements"] = "Erfolge",
    ["gb_cat_misc"] = "Verschiedenes",
    ["gb_cat_favorites"] = "Favoriten",
    ["gb_opt_guides"] = "Guide-Auswahl",
    ["gb_opt_desc_guides"] = "Guide-Auswahl, Daten des aktiven Guides und grundlegende Guide-Steuerung.",
    ["gb_opt_stepdisplay"] = "Schrittanzeige",
    ["gb_opt_desc_stepdisplay"] = "Viewer-Optik, Fensterlayout, Skin/Schriften und Anzeige von Schritten und Zielen.",
    ["gb_opt_progress"] = "Fortschritt",
    ["gb_opt_desc_progress"] = "Schrittfortschritt, Überspringe-Regeln und Abschlussverhalten.",
    ["gb_opt_travel"] = "Reisesystem",
    ["gb_opt_desc_travel"] = "Wegpunkt-Anbieter und Verhalten des Reisesystems.",
    ["gb_opt_map"] = "Karten & Wegpunkte",
    ["gb_opt_desc_map"] = "Pfeilstil, Minimap-/Kartenmarker und Wegpunkt-Optik.",
    ["gb_opt_notifications"] = "Benachrichtigungen",
    ["gb_opt_desc_notifications"] = "Hinweise für Fortschritt und Abschluss.",
    ["gb_opt_actionbuttons"] = "Aktionsschaltflächen",
    ["gb_opt_desc_actionbuttons"] = "Verhalten klickbarer Schritt-/Zielanzeigen.",
    ["gb_opt_convenience"] = "Quests",
    ["gb_opt_desc_convenience"] = "Automatisches Annehmen/Abgeben und Komfortfunktionen.",
    ["gb_opt_accessibility"] = "Barrierefreiheit",
    ["gb_opt_desc_accessibility"] = "Optionen für Farbensichtbarkeit und bessere Lesbarkeit.",
    ["gb_opt_profile"] = "Profile",
    ["gb_opt_desc_profile"] = "Profilverwaltung pro Charakter/Global sowie Kopier-/Reset-Werkzeuge.",
    ["gb_opt_about"] = "Info",
    ["gb_opt_desc_about"] = "Version, Support und Diagnose-/Fehlerberichtswerkzeuge.",
    ["gb_opt_advanced"] = "Erweitert",
    ["gb_opt_desc_advanced"] = "Debug-Werkzeuge, Diagnose und entwicklernahe Steuerungen.",
    ["gb_opt_general"] = "Allgemein",
    ["gb_opt_desc_general"] = "Allgemeine Einstellungen.",
    ["gb_title_viewer"] = "Viewer",
    ["gb_options_viewer_desc"] = "Grundverhalten des Viewers, Guide-Laden und Basissteuerung des Addons.",
    ["gb_hint_search_settings"] = "Tipp:\nNutze links die Suche, um schnell eine Einstellungsseite zu finden.",
    ["gb_hint_options_filter"] = "Tipp:\nDie Suche links filtert Einstellungsseiten.\nNutze 'Vollständige Optionen öffnen' für die Blizzard-Ansicht.",
    ["gb_empty_no_guides_search"] = "Keine Guides passen zu dieser Suche.",
    ["gb_empty_no_guides_category"] = "Keine Guides in dieser Kategorie.",
    ["gb_empty_no_current_guide"] = "Kein aktueller Guide geladen.",
    ["gb_empty_no_current_guide_short"] = "Kein aktueller Guide geladen",
    ["gb_empty_no_recent_guides"] = "Noch keine kürzlich genutzten Guides.",
    ["gb_empty_no_featured_match"] = "Keine empfohlenen Vorschläge passen zu diesem Filter.",
    ["gb_empty_no_featured_suggestions"] = "Keine empfohlenen Vorschläge",
    ["gb_empty_no_favorites"] = "Noch keine Favoriten-Guides.",
    ["gb_no_guide_selected"] = "Kein Guide ausgewählt",
    ["gb_action_clear_search"] = "Suche löschen",
    ["gb_action_show_all_categories"] = "Alle Kategorien anzeigen",
    ["gb_action_go_home"] = "Startseite",
    ["gb_action_open_home"] = "Start öffnen",
    ["gb_action_reset_snoozed"] = "Schlummernde Vorschläge zurücksetzen",
    ["gb_action_clear_search_restore"] = "Suche löschen, um Vorschläge wiederherzustellen",
    ["gb_action_reset_snoozed_restore"] = "Schlummern zurücksetzen, um Empfehlungen wiederherzustellen",
    ["gb_action_try_home"] = "Versuche 'Start', um alle Kategorien zu durchsuchen",
    ["gb_action_browse_all_from_home"] = "Alle Guides von der Startseite durchsuchen",
    ["gb_action_back_to_guides"] = "Zurück zu den Guides",
    ["gb_action_open_full_options"] = "Vollständige Optionen öffnen",
    ["gb_action_go_current_folder"] = "Zum aktuellen Guide-Ordner gehen",
    ["gb_action_resume"] = "Fortsetzen",
    ["gb_action_restart"] = "Neustart",
    ["gb_nav_navigation"] = "Navigation",
    ["gb_nav_back"] = "Zurück",
    ["gb_nav_reset_to_root"] = "Zurück zur Kategorie-Ebene",
    ["gb_featured_bucket_next"] = "Als Nächstes",
    ["gb_featured_bucket_progress"] = "In Bearbeitung",
    ["gb_featured_bucket_level"] = "Passend zu deiner Stufe",
    ["gb_featured_bucket_featured"] = "Empfohlene Routen",
    ["gb_featured_confidence_strong"] = "Stark",
    ["gb_featured_confidence_good"] = "Gut",
    ["gb_featured_confidence_fallback"] = "Ersatz",
    ["gb_roadmap"] = "Fahrplan",
    ["gb_roadmap_bucket_format"] = "%s-Fahrplan",
    ["gb_bucket_preview_next_with_title"] = "Setze deine Reihe fort: %s",
    ["gb_bucket_preview_next"] = "Setze deine Reihe fort",
    ["gb_bucket_preview_progress_with_title"] = "Fortsetzen: %s",
    ["gb_bucket_preview_progress"] = "Angefangene Guides fortsetzen",
    ["gb_bucket_preview_level_with_title"] = "Stufen-passend starten: %s",
    ["gb_bucket_preview_level"] = "Stufen-passende Guides starten",
    ["gb_bucket_preview_featured_with_title"] = "Optionale Route: %s",
    ["gb_bucket_preview_featured"] = "Optionale Routen und Extras",
    ["gb_meta_action"] = "Aktion",
    ["gb_meta_suggestion"] = "Vorschlag",
    ["gb_meta_suggested"] = "Vorgeschlagen",
    ["gb_meta_current"] = "Aktuell",
    ["gb_meta_recommended"] = "empfohlen",
    ["gb_meta_other_useful_option"] = "andere nützliche Option",
    ["gb_meta_current_selection"] = "aktuelle Auswahl",
    ["gb_meta_suggestions_snoozed"] = "Vorschläge könnten schlummern",
    ["gb_meta_restore_recommendations"] = "Empfehlungen wiederherstellen",
    ["gb_meta_filter_no_matches"] = "Filter hat keine Treffer",
    ["gb_meta_see_full_recommendations"] = "Vollständige Empfehlungen ansehen",
    ["gb_meta_no_bucket_suggestions"] = "keine Vorschläge in diesem Bereich",
    ["gb_meta_full_category_access"] = "Vollständiger Kategorie-Zugriff",
    ["gb_meta_suggested_from"] = "Vorgeschlagen von: %s",
    ["gb_meta_confidence"] = "Vertrauen: %s",
    ["gb_meta_why_prefix"] = "Grund: ",
    ["gb_meta_gain_prefix"] = "Gewinn: ",
    ["gb_reason_recently_used"] = "kürzlich verwendet",
    ["gb_reason_incomplete"] = "unvollständig",
    ["gb_reason_your_level_range"] = "dein Stufenbereich",
    ["gb_reason_near_your_level"] = "nahe deiner Stufe",
    ["gb_reason_your_class"] = "deine Klasse",
    ["gb_reason_your_race"] = "deine Rasse",
	["gb_reason_your_profession"] = "dein Beruf",
    ["gb_reason_favorite"] = "Favorit",
    ["gb_reason_current_chain"] = "aktuelle Questreihe",
    ["gb_reason_chain_step_format"] = "Reihenschritt +%d",
    ["gb_reason_inferred_continuation"] = "abgeleitete Fortsetzung",
    ["gb_reason_chapter_continuation"] = "Kapitel-Fortsetzung",
    ["gb_tooltip_featured_controls"] = "Steuerung für Empfehlungen",
    ["gb_tooltip_featured_click"] = "Klick auf das X: für 24 Stunden schlummern",
    ["gb_tooltip_featured_shift_click"] = "Shift-Klick auf X: für diese Sitzung ausblenden",
    ["gb_tooltip_featured_restore"] = "Drücke R oder nutze 'Zurücksetzen' in den Optionen zum Wiederherstellen.",
    ["gb_tooltip_snooze"] = "Vorschlag schlummern lassen",
    ["gb_tooltip_snooze_click"] = "Klick: für 24 Stunden ausblenden",
    ["gb_tooltip_snooze_shift_click"] = "Shift-Klick: für diese Sitzung ausblenden",
    ["gb_tooltip_why_prefix"] = "Grund: ",
    ["gb_tooltip_gain_prefix"] = "Gewinn: ",
    ["gb_tooltip_confidence_prefix"] = "Vertrauen: ",
    ["gb_tooltip_chain_prefix"] = "Questreihe: ",
    ["gb_tooltip_fallback_recommendation"] = "Ersatzempfehlung",
    ["gb_current_guide"] = "Aktueller Guide",
    ["gb_options_fallback_embed_unavailable"] = "Eingebettete Optionen nicht verfügbar. Klicke erneut auf Optionen, um die Blizzard-Interfaceoptionen zu öffnen.",
    ["gb_options_fallback_missing_widgets"] = "Eingebettete Optionen nicht verfügbar. AceGUI-Einbettungswidgets fehlen.",
    ["gb_options_fallback_render_error"] = "Eingebettete Optionen konnten nicht dargestellt werden: %s",
    ["opt_legacyguideddropdown"] = "Klassisches Guide-Dropdown",
    ["opt_featured_header"] = "Empfohlene Vorschläge",
    ["opt_featured_enablefallback"] = "Ersatzvorschläge aktivieren",
    ["opt_featured_enablefallback_desc"] = "Wenn ein Empfehlungsbereich keine direkten Treffer hat, einige nützliche Ersatz-Guides anzeigen.",
    ["opt_featured_hiderecentcompleted"] = "Kürzlich abgeschlossene Guides ausblenden",
    ["opt_featured_hiderecentcompleted_desc"] = "Ganz frisch abgeschlossene Guides aus intelligenten Empfehlungen ausblenden.",
    ["opt_featured_showconfidence"] = "Sicherheitsstufen anzeigen",
    ["opt_featured_showconfidence_desc"] = "Stark/Gut/Ersatz-Markierungen in empfohlenen Zeilen anzeigen.",
    ["opt_featured_resethidden"] = "Ausgeblendete Vorschläge zurücksetzen",
    ["opt_featured_resethidden_desc"] = "Alle mit dem Schließen-Button ausgeblendeten Vorschläge wiederherstellen.",
    ["opt_disablerouteloopstacking"] = "Routen-/Schleifen-Stapelung deaktivieren",
    ["opt_disablerouteloopstacking_desc"] = "Verhindert, dass Routen und Schleifen im gleichen Empfehlungsbereich gestapelt werden.",
    ["opt_routeantminimapmode"] = "Minikarten-Routenpfad",
    ["opt_routeantminimapmode_desc"] = "Lege fest, wie viel vom marschierenden Routenpfad auf der Minikarte angezeigt wird.",
    ["opt_routeantminimapmode_local"] = "Fokussiertes Segment",
    ["opt_routeantminimapmode_local_desc"] = "Zeigt nur den lokalen Abschnitt der Route: vorheriger Punkt, aktueller Punkt und nächster Punkt.",
    ["opt_routeantminimapmode_all"] = "Gesamte Route",
    ["opt_routeantminimapmode_all_desc"] = "Zeigt die komplette Route oder Schleife auf der Minikarte an.",
    ["opt_routeantminimapmode_none"] = "Nur Wegpunkt",
    ["opt_routeantminimapmode_none_desc"] = "Blendet die marschierenden Ameisen auf der Minikarte aus und zeigt nur den aktiven Wegpunkt an.",
    ["opt_routeantdensity"] = "Routenpfad-Dichte",
    ["opt_routeantdensity_desc"] = "Legt fest, wie dicht die marschierenden Ameisen zwischen Routenpunkten angezeigt werden. 1 ist locker, 5 entspricht dem Standard und 9 ist die höchste Dichte.",
    ["opt_accessibility_intro"] = "Passe Optionen für Farbensichtbarkeit und Textlesbarkeit an.",
    ["opt_colorblindmode"] = "Farbenblind-Modus",
    ["opt_colorblindmode_desc"] = "Ersetzt Guide-, Pfeil- und Distanzfarben durch farbenblindfreundliche Paletten und erzwingt kontrastreichere Pfeil-Begriffsfarben.",
    ["opt_colorblindmode_off"] = "Aus",
    ["opt_colorblindmode_protanopia"] = "Protanopie",
    ["opt_colorblindmode_deuteranopia"] = "Deuteranopie",
    ["opt_colorblindmode_tritanopia"] = "Tritanopie",
    ["opt_colorblindmode_global"] = "Global",
    ["opt_colorblindmode_custom"] = "Benutzerdefiniert",
    ["opt_arrowcolor_far"] = "Weit",
    ["opt_arrowcolor_mid"] = "Mittel",
    ["opt_arrowcolor_near"] = "Nah",
    ["opt_simplifyarrownouncolors"] = "Vereinfachte Pfeil-Begriffsfarben",
    ["opt_simplifyarrownouncolors_desc"] = "Sauberere, kontrastreichere Farben für Pfeilbeschriftungen verwenden.",
    ["opt_about_heading"] = "Zygor Guides Viewer Remastered für WoTLK 3.3.5a",
    ["opt_about_support"] = "Support",
    ["opt_about_diag"] = "Tipp: `/zygor status` und `/zygor debug` helfen bei der Fehlersuche.",
    ["opt_showminimapicons"] = "Minimap-Symbole anzeigen",
    ["opt_showminimapicons_desc"] = "Symbole auf der Minimap anzeigen",
    ["opt_iconalpha"] = "Symbol-Alpha",
    ["opt_iconalpha_desc"] = "Transparenz der Kartennotiz-Symbole",
    ["opt_iconsize"] = "Symbolgröße",
    ["opt_iconsize_desc"] = "Größe der Symbole auf der Karte",
    ["opt_arrowshow"] = "Pfeil anzeigen",
    ["opt_arrowshow_desc"] = "Den internen Wegpunkt-Pfeil anzeigen oder ausblenden.",
    ["opt_arrowcolormode_direction"] = "Richtung",
    ["opt_arrowcolormode_distance"] = "Distanz",
    ["opt_arrowtextoutline"] = "Pfeiltext-Kontur",
    ["opt_arrowtextoutline_desc"] = "Konturstärke für den Wegpunkt-Pfeiltext wählen.",
    ["opt_arrowtextoutline_default"] = "Standard",
    ["opt_arrowtextoutline_strong"] = "Stark",
    ["opt_arrowtextoutline_reduced"] = "Reduziert",
    ["opt_remasterpointeronlegacy"] = "Remastered-Zeiger auf Legacy-Skins nutzen",
    ["opt_remasterpointeronlegacy_desc"] = "Wenn aktiviert, verwenden Legacy-Skins den remasterten Wegpunkt-Pfeil.",
    ["opt_resetarrowposition"] = "Pfeilposition zurücksetzen",
    ["opt_resetarrowposition_desc"] = "Setzt den Wegpunkt-Pfeil auf die Standardposition zurück.",
    ["opt_foglightdebug"] = "(Debug) Foglight prüfen",
    ["opt_foglightdebug_desc"] = "Foglight für die aktuelle Karte prüfen",
    ["opt_travelsystem_intro"] = "Wähle, wie Reise- und Wegpunkt-Anbieter behandelt werden.",
    ["opt_mapswaypoints_intro"] = "Konfiguriere Kartenmarker und die Optik des internen Pfeils.",
    ["opt_notifications_intro"] = "Konfiguriere visuelle Benachrichtigungshinweise während des Fortschritts.",
    ["opt_actionbuttons_intro"] = "Konfiguriere Zielsymbole und die Darstellung interaktiver Schritte.",
    ["opt_inlinebuttons_enable"] = "Inline-Schaltflächen aktivieren",
    ["opt_inlinebuttons_enable_desc"] = "Zeigt interaktive Schaltflächen direkt in den Schrittzeilen an.",
    ["opt_actionbar_enable"] = "Aktionsleiste aktivieren",
    ["opt_actionbar_enable_desc"] = "Zeigt eine anklickbare Leiste mit Aktionsschaltflächen für den aktuellen Schritt an.",
    ["opt_actionbar_onlywhenneeded"] = "Nur bei Bedarf anzeigen",
    ["opt_actionbar_onlywhenneeded_desc"] = "Blendet die Aktionsleiste nur ein, wenn der aktuelle Schritt interaktive Aktionen enthält.",
    ["opt_actionbar_locked"] = "Aktionsleiste sperren",
    ["opt_actionbar_locked_desc"] = "Verhindert, dass die Aktionsleiste mit der Maus verschoben werden kann.",
    ["opt_actionbar_scale"] = "Skalierung",
    ["opt_actionbar_scale_desc"] = "Passt die Größe der Aktionsleiste an.",
    ["opt_actionbar_size"] = "Schaltflächengröße",
    ["opt_actionbar_size_desc"] = "Größe der einzelnen Schaltflächen in der Aktionsleiste.",
    ["opt_actionbar_spacing"] = "Abstand",
    ["opt_actionbar_spacing_desc"] = "Abstand zwischen den Schaltflächen in der Aktionsleiste.",
    ["opt_actionbar_pinside"] = "Ankerseite",
    ["opt_actionbar_pinside_desc"] = "Wähle, an welcher Seite des Viewer-Fensters die Aktionsleiste andockt.",
    ["opt_actionbar_pinside_top"] = "Oben",
    ["opt_actionbar_pinside_bottom"] = "Unten",
    ["opt_actionbar_pinside_left"] = "Links",
    ["opt_actionbar_pinside_right"] = "Rechts",
    ["opt_actionbar_resetanchor"] = "Anker zurücksetzen",
    ["opt_actionbar_resetanchor_desc"] = "Setzt die Position der Aktionsleiste auf die Standardposition zurück.",
    ["opt_actionbar_markers"] = "Zielmarkierungen aktivieren",
    ["opt_actionbar_markers_desc"] = "Zeigt zusätzliche Markierungen für Ziele in der Aktionsleiste an.",
    ["frame_toolbar_guides"] = "Guides",
    ["frame_toolbar_guides_click"] = "zum Öffnen des Guide-Menüs",
    ["frame_toolbar_guides_right"] = "zum Öffnen des Guide-Managers",
    ["frame_toolbar_close"] = "Schließen",
    ["frame_toolbar_close_click"] = "zum Schließen",
    ["frame_toolbar_settings"] = "Optionen",
    ["frame_toolbar_settings_click"] = "für das Schnellmenü",
    ["frame_toolbar_settings_right"] = "zum Öffnen der Guide-Manager-Optionen",
    ["frame_toolbar_stepview"] = "Schrittansicht",
    ["frame_toolbar_stepview_showall"] = "um alle anzuzeigen",
    ["frame_toolbar_stepview_showonly"] = "um nur |cffffffff%s|r anzuzeigen",
    ["frame_toolbar_stepview_setcount"] = "um die Schrittzahl festzulegen",
    ["frame_toolbar_unlock"] = "Fenster entsperren",
    ["frame_toolbar_unlock_click"] = "zum Entsperren",
    ["frame_toolbar_lock"] = "Fenster sperren",
    ["frame_toolbar_lock_click"] = "zum Sperren",
    ["frame_title_default"] = "Zygor Guides",
    ["frame_tab_guides"] = "Guides",
    ["frame_tab_spots"] = "Spots",

    ["completion_done"] = "(fertig)",
    ["completion_rep"] = "(%s)",

    ["req_not"] = "nicht %s",

    ["stepgoal_rep"] = "Werde %s bei %s",
    ["stepgoal_achieve"] = "Erhalte Erfolg '%s'",
    ["stepgoal_achievesub"] = "Schließe '%s' für den Erfolg '%s' ab",
    ["stepgoal_skill"] = "Lerne %s bis Stufe %s",
    ["stepgoal_skillmax"] = "Steigere %s auf die maximale Stufe %s",
    ["stepgoal_learn"] = "Lerne, %s herzustellen",
    ["stepgoal_or"] = "  - oder -",

    ["binding_prev"] = "Vorheriger Schritt",
    ["binding_next"] = "Nächster Schritt",

    ["waypointaddon_detecting"] = "Versuche, Wegpunkt-Addon automatisch zu erkennen...",
    ["waypointaddon_disconnected"] = "Verbindung zu |cffddeeff%s|r getrennt.",
    ["pointer_corpselabel1"] = "Ex-Du",
    ["pointer_corpselabel2"] = "Wer wegrennt, lebt länger...",
    ["pointer_corpselabel3"] = "Da war wohl ein Gegner zu viel.",
    ["pointer_corpselabel4"] = "Eimer-Treter - hier entlang",
    ["pointer_corpselabel5"] = "Denk lieber nicht an die Reparaturkosten.",

    ["opt_group_map_hidearrowwithguide"] = "Pfeil beim Schließen des Viewers ausblenden",
    ["opt_group_map_hidearrowwithguide_desc"] = "Aktiviere dies, damit der Pfeil der Sichtbarkeit des Guide-Fensters folgt.\nDeaktiviert lassen, wenn der Pfeil sichtbar bleiben soll, wenn du Guides ausblendest.",
    ["opt_group_addons_internal"] = "Integrierte Wegpunkte",
    ["opt_group_addons_carbonite"] = "Carbonite (Addon)",
    ["opt_stepnumber"] = "Schrittnummern anzeigen",
    ["opt_stepnumber_desc"] = "Zeige Schrittnummern und empfohlene Stufen für jeden Schritt an.\nDeaktiviere dies, um Bildschirmplatz zu sparen.",
    ["opt_hidestepborders"] = "Rahmen ausblenden",
    ["opt_hidestepborders_desc"] = "Blendet die grafischen Rahmen um Schritte aus.",
    ["opt_stepbackopacity"] = "Hintergrund-Deckkraft",
    ["opt_stepbackopacity_desc"] = "Deckkraft des Schrittfenster-Hintergrunds.\nDie Hintergrundfarbe richtet sich nach dem Fortschritt und wird abgedunkelt.",
    ["opt_goalbackprogressing"] = "Mitte",
    ["opt_goalbackprogressing_desc"] = "Diese Farbe markiert Ziele bei 50% Fortschritt.",
    ["opt_progressbackcolor_desc"] = "Schrittfarben:",
    ["opt_goalbackaux"] = "Reise",
    ["opt_goalbackaux_desc"] = "Diese Farbe für Reiseschritte verwenden.",
    ["opt_goalbackobsolete"] = "Veraltet",
    ["opt_goalbackobsolete_desc"] = "Diese Farbe für veraltete Ziele oder Schritte verwenden.",
    ["opt_resetwindow"] = "Fenster zurücksetzen",
    ["opt_resetwindow_desc"] = "Wenn das Fenster außerhalb des Bildschirms liegt, setzt diese Schaltfläche es zurück in die Mitte.",
    ["opt_trackchains"] = "Questketten verfolgen",
    ["opt_trackchains_desc"] = "Markiert Quest-Annahme-Schritte als nicht verfügbar, wenn eine vorherige Quest nicht abgeschlossen wurde.\n\nDie Questketten-Datenbank enthält auch 'lockere Ketten'; dadurch kann eine Questannahme manchmal als nicht verfügbar erscheinen, obwohl sie angenommen werden kann.",
    ["opt_guidesinhistory"] = "Anzahl zuletzt genutzter Guides",
    ["opt_guidesinhistory_desc"] = "Zeigt diese Anzahl kürzlich genutzter Guides an.",
    ["opt_skin_remaster"] = "|cffc7d9ffRemaster (Standard)",
    ["opt_group_progress"] = "Dynamischer Fortschritt",
    ["opt_group_progress_desc"] = "Zur Optimierung des Levelns kann dieses Addon Quests dynamisch überspringen, die dir auf deiner Stufe wenig bringen.",
    ["opt_levelsahead"] = "Stufen voraus erlauben",
    ["opt_levelsahead_desc"] = "Diese Einstellung steuert, wie weit du dem Guide voraus sein willst.\nMit 0 werden Quests unterhalb deiner Stufe normalerweise übersprungen (wenn sie keine Folgequests haben).\nMit 1 oder mehr werden nur Quests übersprungen, die mehr als diese Anzahl Stufen unter dir liegen.",
    ["opt_showobsolete"] = "Veraltete Schritte markieren",
    ["opt_showobsolete_desc"] = "Markiert veraltete Schritte mit grauem Hintergrund.\nSchritte gelten als veraltet, wenn sie für deine Stufe zu niedrig sind.",
    ["opt_skipobsolete"] = "Veraltete Schritte überspringen",
    ["opt_skipobsolete_desc"] = "Überspringt veraltete Schritte automatisch.",
    ["opt_skipauxsteps"] = "Reiseschritte überspringen",
    ["opt_skipauxsteps_desc"] = "Überspringt Reiseschritte automatisch, wenn danach bereits abgeschlossene oder veraltete Schritte folgen.\nDamit wird vermieden, dass du weit reist und danach ein bereits erledigter Annahmeschritt folgt.",
    ["opt_skipflightsteps"] = "Flugrouten als bekannt annehmen",
    ["opt_skipflightsteps_desc"] = "Nimmt an, dass du Flugrouten selbst verwaltest, und markiert Flugrouten-Schritte automatisch als abgeschlossen.\n\nBesonders nützlich beim Einstieg in spätere Guide-Abschnitte.",
    ["opt_skipimpossible"] = "Unmögliche Schritte überspringen",
    ["opt_skipimpossible_desc"] = "Überspringt unmögliche Schritte automatisch, falls du absichtlich ausgelassene Questziele nicht angezeigt bekommen möchtest.",
    ["opt_group_progress_bottomdesc"] = "Dynamischer Fortschritt markiert Quests als 'veraltet', wenn du den im Guide erwarteten Stufenbereich um mehr als den oben definierten Wert überschreitest. Questketten werden nur dann als veraltet markiert, wenn die gesamte Kette veraltet ist.\n\nFür neue Spieler hilft dies, indem Inhalte niedriger Stufe intelligent übersprungen werden und nur sinnvolle Questketten übrig bleiben. Wenn du einen guten Startpunkt suchst, lade den Startguide deiner Rasse und lasse den Viewer passende Bereiche automatisch finden.\n\nFür erfahrene Spieler verhindert dies, dass der Guide mit zu niedrigen Quests bremst, falls du schneller levelst als erwartet (zum Beispiel durch Instanzen oder Ruhend-Bonus). Du kannst festlegen, wie weit du voraus sein darfst, bevor der Guide dich durch Überspringen nach vorne schiebt.",
    ["opt_group_mapinternal"] = "Interne Wegpunkte",
    ["opt_arrowmeters"] = "Metrisches System",
    ["opt_arrowmeters_desc"] = "Verwendet Meter und Kilometer statt Yards und Meilen.",
    ["opt_arrowfreeze"] = "Pfeil ignoriert Klicks",
    ["opt_arrowfreeze_desc"] = "Lässt den Pfeil Mausklicks ignorieren. Deaktivieren, um ihn verschieben zu können.",
    ["opt_arrowcam"] = "Pfeil folgt Kamera",
    ["opt_arrowcam_desc"] = "Zeigt Richtungen relativ zur Kameraausrichtung. Ist dies aus, orientiert sich der Pfeil an der Blickrichtung deines Charakters.\n\nHinweis: Im Kameramodus kann der Pfeil bei Click-to-Move ungenau wirken.",
    ["opt_arrowcolordir"] = "Farbe nach Richtung",
    ["opt_arrowcolordir_desc"] = "Färbt den Pfeil-Edelstein grün, wenn er in die richtige Richtung zeigt.\n\nDeaktivieren, wenn Grün nur bei Nähe zum Ziel erscheinen soll.",
    ["opt_arrowscale"] = "Pfeil-Skalierung",
    ["opt_arrowscale_desc"] = "Größe des Pfeils.",
    ["opt_arrowfontsize"] = "Pfeil-Schriftgröße",
    ["opt_arrowfontsize_desc"] = "Schriftgröße im Pfeil-Fenster.",
    ["opt_minimapzoom"] = "Automatisch zoomen",
    ["opt_minimapzoom_desc"] = "Erhöht den Minikarten-Zoom automatisch, wenn ein Wegpunkt gesetzt wird, und stellt ihn danach wieder her.",
    ["opt_foglight"] = "Karte aufdecken",
    ["opt_foglight_desc"] = "Unentdeckte Bereiche auf der Karte anzeigen.",
    ["opt_group_gold"] = "Gold-Guide",
    ["opt_group_gold_desc"] = "Diese Einstellungen steuern die Anzeige von Goldfarming-Schritten und Ressourcenknoten.",
    ["opt_gold_detectiondist"] = "Erkennungsreichweite",
    ["opt_gold_detectiondist_desc"] = "Entfernung, in der naheliegende Gold-Guide-Spots erkannt und berücksichtigt werden.",
    ["opt_gold_reqmode"] = "Anforderungsmodus",
    ["opt_gold_reqmode_desc"] = "Legt fest, welche Spot-Typen berücksichtigt werden sollen.",
    ["opt_gold_reqmode_all"] = "Alle",
    ["opt_gold_reqmode_current"] = "Nur aktueller Guide",
    ["opt_gold_reqmode_future"] = "Aktueller + zukünftige Guides",
    ["gold_missing_noguidesloaded"] = "Keine Gold-Guides geladen.",
    ["gold_missing_nospotsinrange"] = "Keine passenden Gold-Spots in Reichweite gefunden.",
    ["gold_header_ore"] = "Erzvorkommen:",
    ["gold_header_herb"] = "Kräuter:",
    ["gold_header_skin"] = "Häute:",
    ["gold_header_drop"] = "Beute von |cffffdddd%s|r:",
    ["opt_group_convenience"] = "Zusatzfunktionen",
    ["opt_group_convenience_desc"] = "Verschiedene Funktionen, die nützlich sein können.",
    ["opt_autoaccept"] = "Quests automatisch annehmen",
    ["opt_autoaccept_desc"] = "Nimmt angebotene Quests automatisch an.",
    ["opt_autoturnin"] = "Quests automatisch abgeben",
    ["opt_autoturnin_desc"] = "Gibt abgeschlossene Quests automatisch ab.",
    ["opt_autoquestreward"] = "Questbelohnung automatisch wählen",
    ["opt_autoquestreward_desc"] = "Wählt die Questbelohnung automatisch anhand des höchsten ItemScore aus.",
    ["opt_fixblizzardautoaccept"] = "Blizzard-Auto-Annahme reparieren",
    ["opt_fixblizzardautoaccept_desc"] = "Aktiviert bei aktivierter Blizzard-Option 'Quest automatisch annehmen' dennoch die Schritte 'Nimm' und 'Angenommen' als abgeschlossen.",
    ["opt_audiocues"] = "Audiohinweise",
    ["opt_audiocues_desc"] = "Spielt Töne bei Schrittfortschritt ab.",
    ["opt_analyzereps"] = "Ruf analysieren",
    ["opt_analyzereps_desc"] = "Wertet deinen aktuellen Rufstand aus und markiert unpassende Rufschritte als veraltet.",
    ["opt_mapcoords"] = "Kartenkoordinaten anzeigen",
    ["opt_mapcoords_desc"] = "Zeigt Maus- und Spielerkoordinaten in Kartenfenstern an.",
    ["opt_targetpreview_growth"] = "Wachstumsrichtung",
    ["opt_targetpreview_growth_desc"] = "Wähle, ob die angedockte Zielvorschau der Größenrichtung des Viewers folgen, nach oben wachsen oder nach unten wachsen soll.",
    ["opt_targetpreview_growth_auto"] = "Viewer folgen",
    ["opt_targetpreview_growth_up"] = "Nach oben wachsen",
    ["opt_targetpreview_growth_down"] = "Nach unten wachsen",
    ["opt_targetpreview_enable"] = "Zielvorschau aktivieren",
    ["opt_targetpreview_enable_desc"] = "Zeigt eine Vorschau des aktuellen Ziels mit Modell und Informationen an.",
    ["opt_targetpreview_header"] = "Zielvorschau",
    ["opt_targetpreview_intro"] = "Konfiguriere die Darstellung der Zielvorschau.",
    ["opt_targetpreview_locked"] = "Zielvorschau sperren",
    ["opt_targetpreview_locked_desc"] = "Verhindert, dass die Zielvorschau mit der Maus verschoben werden kann.",
    ["opt_targetpreview_scale"] = "Skalierung",
    ["opt_targetpreview_scale_desc"] = "Passt die Größe der Zielvorschau an.",
    ["opt_targetpreview_width"] = "Breite",
    ["opt_targetpreview_width_desc"] = "Breite des Zielvorschau-Fensters.",
    ["opt_targetpreview_height"] = "Höhe",
    ["opt_targetpreview_height_desc"] = "Höhe des Zielvorschau-Fensters.",
    ["opt_targetpreview_pinside"] = "Ankerseite",
    ["opt_targetpreview_pinside_desc"] = "Wähle, an welcher Seite des Viewer-Fensters die Zielvorschau andockt.",
    ["opt_targetpreview_resetanchor"] = "Anker zurücksetzen",
    ["opt_targetpreview_resetanchor_desc"] = "Setzt die Position der Zielvorschau auf die Standardposition zurück.",
    ["opt_targetpreview_onlywhenneeded"] = "Nur bei Bedarf anzeigen",
    ["opt_targetpreview_onlywhenneeded_desc"] = "Blendet die Zielvorschau nur ein, wenn ein Ziel verfügbar ist.",
    ["opt_targetpreview_mode"] = "Anzeigemodus",
    ["opt_targetpreview_mode_desc"] = "Wähle den Darstellungsstil der Zielvorschau.",
    ["opt_targetpreview_mode_hybrid"] = "Hybrid",
    ["opt_targetpreview_mode_model"] = "Modell",
    ["opt_targetpreview_mode_card"] = "Karte",


    ["opt_gearadvisor_title"] = "Ausrüstungs-Berater",
    ["opt_gearadvisor_desc"] = "Ausrüstungs-Bewertung und Verbesserungserkennung",
    ["opt_gearadvisor_intro"] = "Lege fest, wie Zygor Verbesserungen erkennt, wie er dich benachrichtigt und welche Quellen der Ausrüstungs-Finder durchsuchen soll.",
    ["opt_gearadvisor_detection_header"] = "Erkennung",
    ["opt_gearadvisor_enable"] = "Ausrüstungs-Berater aktivieren",
    ["opt_gearadvisor_enable_desc"] = "Aktiviert die Gegenstandsbewertung und Verbesserungserkennung.",
    ["opt_itemscore_tooltips"] = "ItemScore in Tooltips anzeigen",
    ["opt_itemscore_tooltips_desc"] = "Zeigt den Verbesserungsprozentsatz in Gegenstands-Tooltips an.",
    ["opt_itemscore_tooltips_allbuilds"] = "Alle Builds in Tooltips anzeigen",
    ["opt_itemscore_tooltips_allbuilds_desc"] = "Zeigt Verbesserungs- oder Verschlechterungszeilen für alle Specs deiner Klasse in Gegenstands-Tooltips. Aktive Build-Empfehlungen und Anlegen-Hinweise verwenden weiterhin nur deinen erkannten aktiven Build.",
    ["opt_gearadvisor_prompting_header"] = "Benachrichtigung",
    ["opt_autogearauto"] = "Verbesserungen automatisch anlegen",
    ["opt_autogearauto_desc"] = "Legt Verbesserungen automatisch an, ohne zu fragen (nur Benachrichtigung).",
    ["opt_masterloot_notices"] = "Master-Loot-Verbesserungshinweise anzeigen",
    ["opt_masterloot_notices_desc"] = "Zeigt eine lokale Ausrüstungs-Berater-Nachricht, wenn ein sichtbarer Master-Loot-Gegenstand eine echte Verbesserung für deinen aktiven Build ist.",
    ["opt_masterloot_compare"] = "Verglichenen angelegten Gegenstand in Master-Loot-Hinweisen einbeziehen",
    ["opt_masterloot_compare_desc"] = "Fügt den Link des aktuell angelegten Basis-Gegenstands in die Master-Loot-Verbesserungsnachricht ein, wenn verfügbar.",
    ["opt_gearadvisor_vendor_header"] = "Händler & Komfort",
    ["opt_autosellgrey"] = "Graue Gegenstände automatisch verkaufen",
    ["opt_autosellgrey_desc"] = "Verkauft graue (wertlose) Gegenstände automatisch beim Händlerbesuch.",
    ["opt_autorepair"] = "Automatisch reparieren",
    ["opt_autorepair_desc"] = "Repariert Ausrüstung automatisch beim Händlerbesuch.",
    ["opt_gearadvisor_sources_desc"] = "Wähle, welche Dungeon- und Schlachtzugs-Schwierigkeiten der Ausrüstungs-Finder vorschlagen darf.",
    ["opt_gearadfinder_sources_header"] = "Quellen für Ausrüstungs-Finder",
    ["opt_gear_normal_dungeons"] = "Normale Dungeons",
    ["opt_gear_heroic_dungeons"] = "Heroische Dungeons",
    ["opt_gear_normal_raids"] = "Normale Schlachtzüge",
    ["opt_gear_heroic_raids"] = "Heroische Schlachtzüge",
    ["opt_gearadvisor_maintenance_header"] = "Wartung",
    ["opt_clearnotupgrades"] = "Abgelehnte Verbesserungen zurücksetzen",
    ["opt_clearnotupgrades_desc"] = "Löscht die Liste der Gegenstände, die du zuvor abgelehnt hast.",
    ["opt_clearnotupgrades_done"] = "Liste abgelehnter Verbesserungen gelöscht.",
    ["opt_statweights_intro"] = "Passe an, wie stark jede Eigenschaft die Gegenstandsbewertung beeinflusst. Höhere Werte machen die Eigenschaft wichtiger.",
    ["opt_statweights_warning"] = "|cffff6600Warnung:|r Das Ändern von Stat Weights ist für fortgeschrittene Benutzer. Falsche Werte können zu schlechten Ausrüstungsempfehlungen führen.\n",
    ["opt_statweights_curated"] = "|cff88ccffEmpfohlene Standardwerte:|r Die Wrath-Stat-Weights sind kuratierte, quellbasierte Baselines für 3.3.5a. Die meisten Spieler sollten hier beginnen und nur bei klarem Grund anpassen.\n",
    ["opt_statweights_class_header"] = "Klassen- & Spec-Auswahl",
    ["opt_statweights_class"] = "Klasse",
    ["opt_statweights_spec"] = "Spec",
    ["opt_statweights_override"] = "Aktiven Build überschreiben",
    ["opt_statweights_override_desc"] = "Verwendet den ausgewählten Spec aus diesem Panel als deinen aktiven Live-Build für Tooltips und Ausrüstungsempfehlungen, bis deaktiviert.",
    ["opt_statweights_activate"] = "Als aktiven Spec-Weight festlegen",
    ["opt_statweights_activate_desc"] = "Verwendet diese Stat Weights für die Ausrüstungsbewertung.",
    ["opt_statweights_activelabel"] = "|cff00ff00Dies ist dein aktiver Stat-Weight-Satz.|r",
    ["opt_statweights_visibility_header"] = "Sichtbarkeit",
    ["opt_statweights_showallstats"] = "Alle Stats anzeigen",
    ["opt_statweights_showallstats_desc"] = "Zeigt alle Stat-Weight-Felder an, auch die, die von diesem Spec nicht verwendet werden.",
    ["opt_statweights_weights_header"] = "Stat Weights",
    ["opt_statweights_spacer"] = "Passe das Gewicht für jede Eigenschaft unten an. Höhere Werte machen die Eigenschaft wertvoller für die Bewertung.\n",
    ["haman$"] = "hamans",
    ["(%a)man$"] = "%1men",

    ["binding_togglewindow"] = "Guide-Fenster anzeigen",

} end)



local plurals = {
}

ZygorGuidesViewer_L("Specials", "deDE", function() return {
    ["plural"] = function (word)
        return word
    end,
    ['contract_mobs'] = false,
    ['contract_mobs_old'] = function(mobs)
            local start,ending

            if not mobs[1].name and type(mobs)=="table" then
                local l=mobs
                mobs={}
                for i=1,#l do mobs[i]={name=l[i]} end
            end
            local common,all
            for i=1,50 do
                common = mobs[1].name:sub(1,i)
                all=true
                for m=2,#mobs do
                    if mobs[m].name:find(common)~=1 then
                        all=false
                        break
                    end
                end
                if not all then
                    common = common:sub(1,-2)
                    break
                end
            end
            if common:sub(-1)==" " then common = common:sub(1,-2) end
            start=common

            for i=1,50 do
                common = mobs[1].name:sub(-i)
                all=true
                for m=2,#mobs do
                    if mobs[m].name:sub(-i)~=common then
                        all=false
                        break
                    end
                end
                if not all then
                    common = common:sub(2)
                    break
                end
            end
            if common:sub(1,1)==" " then common = common:sub(2) end
            ending=common

            if #start>#ending and #start>3 then
                return ZygorGuidesViewer_L("Specials")['contract_mobs_start'](start)
            elseif #ending>#start and #ending>3 then
                return ZygorGuidesViewer_L("Specials")['contract_mobs_end'](ending)
            else
                return nil
            end
        end,
    ['contract_mobs_start'] = function(s) return ZygorGuidesViewer_L("Specials")['plural'](s) end,
    ['contract_mobs_end'] = function(s)
        local pre=s:sub(1,4)
        if pre=="der " or pre=="das " or pre=="die " then
            return "Gegner "..s
        else
            return ZygorGuidesViewer_L("Specials")['plural'](s)
        end
    end,
} end)



-- Add lines for any translations needed for:

-- MISC STRINGS

ZygorGuidesViewer_L("G_string", "deDE", function() return {
--  ["blabla"] = TRUE,
} end)

ZygorGuidesViewer_L("Main", "deDE", function() return {
    ["targetpreview_level"] = "Stufe",
    ["targetpreview_class_boss"] = "Boss",
    ["targetpreview_class_elite"] = "Elite",
    ["targetpreview_class_rareelite"] = "Rar Elite",
    ["targetpreview_class_rare"] = "Rar",
    ["targetpreview_title"] = "Zielvorschau",
    ["targetpreview_title_locked"] = "Zielvorschau",
    ["targetpreview_role_talk"] = "Ansprechen",
    ["targetpreview_role_kill"] = "Töten",
    ["targetpreview_hint"] = "Klicken, um\n diese Kreatur anzuvisieren.",
    ["targetpreview_hint_empty"] = "In diesem Schritt ist kein Ansprech- oder Tötungsziel aktiv.",
    ["targetpreview_empty_name"] = "Kein Ziel",
    ["popup_accept"] = "Annehmen",
    ["popup_decline"] = "Ablehnen",
    ["actionbutton_bar_title"] = "Ziehen, um Aktionsschaltflächen zu bewegen",
    ["actionbutton_bar_title_locked"] = "Aktionsschaltflächen",
    ["actionbutton_tooltip_talk"] = "Visiere %s an und versuche, es mit einem grünen Dreieck zu markieren.",
    ["actionbutton_tooltip_kill"] = "Visiere %s an und versuche, es mit einem Totenkopf zu markieren.",
    ["actionbutton_tooltip_script"] = "Führe das Makro des aktuellen Schritts aus.",
    ["actionbutton_tooltip_petaction"] = "Verwende die empfohlene Begleiteraktion.",
    ["gearfinder_title"] = "Ausrüstungs-Finder",
    ["gearfinder_no_upgrade"] = "Keine Verbesserung gefunden",
    ["gearfinder_load_guide"] = "Guide laden",
    ["gearfinder_suggested_dungeon"] = "Empfohlener Dungeon:",
    ["gearfinder_refresh"] = "Klicken zum Aktualisieren",
    ["gearfinder_status_searching"] = "Suche nach Verbesserungen%s",
    ["gearfinder_status_searching_future"] = "Suche nach zukünftigen Verbesserungen%s",
    ["gearfinder_label_dungeon"] = "Dungeon:",
    ["gearfinder_label_unknown"] = "Unbekannt",
    ["gearfinder_label_inbags"] = "In Taschen:",
    ["gearfinder_label_score"] = "Wertung: %d",
    ["gearfinder_label_score_value"] = "%.1f Wertung",
    ["gearfinder_label_equipped"] = "Angelegt",
    ["gearfinder_label_empty"] = "Leerer Slot",
    ["gearfinder_upgrade_percent"] = "+%d%% Verbesserung",
    ["gearfinder_upgrade_percent_short"] = "%+.1f%%",
    ["gearfinder_label_new_item"] = "Neuer Gegenstand",
    ["gearfinder_label_delta_score"] = "%+.1f Score",
    ["gearfinder_label_best_gains"] = "Beste Gewinne: %s",
    ["gearfinder_label_found"] = "Bestes gefunden:",
    ["gearfinder_label_future"] = "Später:",
    ["gearfinder_items_found"] = "%d Gegenstände gefunden",
    ["itemscore_ae_equip"] = "%s anlegen",
    ["itemscore_ae_over"] = " statt %s",
    ["itemscore_ae_equip1"] = "Diesen Gegenstand ersetzen",
    ["itemscore_ae_equip2"] = "Diesen Gegenstand anlegen",
    ["itemscore_ae_with"] = "mit",
    ["itemscore_ae_accept"] = "Anlegen",
    ["itemscore_ae_decline"] = "Nicht jetzt",
    ["itemscore_ae_report_tip"] = "Halte Umschalt gedrückt und klicke, um einen detaillierten Ausrüstungsbericht zu sehen.\nAbgelehnte Gegenstände werden nicht erneut vorgeschlagen.",
    ["itemscore_ae_build"] = "Spezialisierung",
    ["itemscore_questitem1"] = "Eine Quest benötigt diesen Gegenstand.",
    ["itemscore_questitem2"] = "Für den aktuellen Questschritt anlegen?",
    ["itemscore_questitem3"] = "Vorherigen Gegenstand wieder anlegen?",
    ["notifcenter_gear_title"] = "Ausrüstungs-Berater",
    ["notifcenter_gear_text"] = "Verbesserung gefunden",
    ["notifcenter_gear_text_sl"] = "%d Verbesserung gefunden",
    ["notifcenter_gear_text_pl"] = "%d Verbesserungen gefunden",
    ["notifcenter_gear_equipped"] = "%s im Slot %s angelegt",
    ["notifcenter_quest_text"] = "Questgegenstand",
    ["notifcenter_gen_popup_tooltip"] = "Klicken zum Öffnen",
    ["opt_itemscore_ae_clearednotupgrade"] = "Liste abgelehnter Verbesserungen gelöscht.",
    ["opt_itemscore_warning"] = "Bearbeite Stat Weights für die Gegenstandsbewertung. Höhere Werte bedeuten, dass die Eigenschaft für deinen Spec wichtiger ist.",
    ["opt_gear_title"] = "Konfiguriere automatische Ausrüstungsbewertung und Verbesserungserkennung.",
    ["opt_gear_score_class"] = "Klasse:",
    ["opt_gear_score_spec"] = "Spec:",
    ["opt_gear_sources"] = "Quellen für Ausrüstungs-Finder",
    ["opt_gear_sources_dungeons"] = "Dungeons",
    ["opt_gear_sources_raids"] = "Schlachtzüge",
    ["opt_quickscan_warning"] = "Schnellscan-Modus - Gegenstandslinks wurden nicht gesammelt.",
    ["gold_app_no_goldguide"] = "Öffne den Gold-Guide (/zgold), um Trenddaten zu laden.",
    ["gold_app_no_goldguide_short"] = "Öffne /zgold, um Guides zu laden. ",
    ["gold_app_no_goldguide_tooltip"] = "Öffne das Gold-Guide-Fenster, um Trenddaten aus Auktionshaus-Scans zu initialisieren.",
    ["gold_app_no_scan_data"] = "Aktuelle Preise unbekannt. Scanne das Auktionshaus.",
    ["gold_app_no_scan_data_short"] = "Aktuelle Preise unbekannt.",
    ["gold_app_no_scan_data_tooltip"] = "Scanne das Auktionshaus, um aktuelle Preisdaten zu sammeln.",
    ["gold_app_no_servertrends"] = "Keine Trenddaten. Scanne täglich, um Trends aufzubauen.",
    ["gold_app_no_servertrends_short"] = "Keine Trenddaten. ",
    ["gold_app_no_servertrends_tooltip"] = "Scanne das Auktionshaus täglich, um Preistrends aufzubauen.",
    ["gold_app_old_scan_data"] = "Scandaten sind veraltet. Scanne zum Aktualisieren.",
    ["gold_app_old_scan_data_short"] = "Scannen zum Aktualisieren.",
    ["gold_app_old_scan_data_tooltip"] = "Scanne das Auktionshaus, um Preisdaten zu aktualisieren.",
    ["gold_app_old_servertrends"] = "Trenddaten sind veraltet (%s). Scanne zum Aktualisieren.",
    ["gold_app_old_servertrends_short"] = "Trenddaten sind veraltet (%s). ",
    ["gold_app_old_servertrends_tooltip"] = "Trenddaten sind veraltet. Scanne täglich.",
    ["gold_app_trend_tooltip"] = "Trenddaten werden aus Auktionshaus-Scans erstellt. Scanne täglich für bessere Daten.",
    ["gold_auctions_error_noresults"] = "Keine profitablen Auktionen gefunden.",
    ["gold_crafting_error_noprofessions"] = "Du hast keinen Herstellungsberuf.",
    ["gold_crafting_error_noresults"] = "Keine profitablen hergestellten Gegenstände gefunden.",
    ["gold_crafting_error_recipesnotcached"] = "Keine Rezepte gefunden. Öffne zuerst dein Berufsfenster.",
    ["gold_farming_error_noitemtype"] = "Keine farmbaren %s-Gegenstände für deine Stufe gefunden.",
    ["gold_farming_error_noresults"] = "Keine farmbaren Gegenstände für deine Stufe gefunden.",
    ["gold_gathering_error_all_noprofessions"] = "Du hast keinen Sammelberuf gelernt.",
    ["gold_gathering_error_one_noresults"] = "Keine profitablen Sammelrouten für %s gefunden.",
    ["gold_gathering_error_one_noskillin"] = "Du hast %s nicht gelernt.",
    ["gold_gathering_error_one_noskillin_skills"] = "\n\nDeine Sammelberufe: %s",
    ["gold_gathering_error_one_nothing"] = "Keine Sammelrouten gefunden.\n\nDeine Sammelberufe: %s",
    ["gold_gathering_error_prof"] = "%s (%d)",
    ["gold_gathering_no_results"] = "Du benötigst einen Sammelberuf: Kürschnerei, Kräuterkunde oder Bergbau.",
    ["gold_general_open_window1"] = "\nÖffne dein Berufsfenster, um Rezepte zwischenzuspeichern.",
    ["gold_general_open_window2"] = "\nÖffne dein Berufsfenster, um Rezepte zwischenzuspeichern.",
    ["gold_expertmode_easylabel"] = "Einfach",
    ["gold_expertmode_easytooltip"] = "Nur Gegenstände anzeigen, die sich voraussichtlich schnell verkaufen.",
    ["gold_expertmode_expertlabel"] = "Experte",
    ["gold_expertmode_experttooltip"] = "Sowohl schnell als auch langsam verkaufbare Gegenstände anzeigen.\nEs kann Tage dauern, bis sich Ware verkauft.",
    ["gold_expertmode_generictooltip"] = "Lege den Investitionsmodus fest.",
    ["frame_selectguide"] = "Guide laden",
    ["frame_selectguide_left"] = "Klicken, um den Dungeon-Guide zu laden",
    ["frame_toolbar_stepview_options"] = "zum Öffnen der Schrittanzeige-Optionen",
    ["stepgoal_arrive"] = "Komme bei %s an",
    ["stepgoal_cast"] = "Wirke %s",
    ["stepgoal_click"] = "Klicke %s",
    ["stepgoal_fly"] = "Fliege nach %s",
    ["waypointaddon_disconnecting"] = "Trenne Verbindung zum Wegpunkt-Addon: %s",
    ["gb_opt_optimization"] = "Optimierung",
    ["gb_opt_desc_optimization"] = "Leistungsrelevante Einstellungen, Pfeil-Aktualisierungsrate und künftige Optimierungs-Optionen.",
    ["opt_optimization_intro"] = "Passe leistungsrelevante Verhaltensweisen für den internen Pfeil an und halte Platz für künftige Wrath-spezifische Optimierungen bereit.",
    ["opt_optimization_arrow_header"] = "Pfeil-Leistung",
    ["opt_optimization_arrow_desc"] = "Steuert, wie oft der integrierte Wegpunkt-Pfeil aktualisiert wird. Niedrigere Raten senken die CPU-Last; höhere Raten wirken flüssiger.",
    ["opt_arrow_refresh_rate"] = "Pfeil-Aktualisierungsrate",
    ["opt_arrow_refresh_rate_desc"] = "Bestimmt die Frequenz der Pfeil-Updates. Niedrige Werte sparen CPU; hohe Werte verbessern die Flüssigkeit.",
    ["opt_arrow_refresh_rate_20"] = "20 FPS (Klassisch)",
    ["opt_arrow_refresh_rate_30"] = "30 FPS (Empfohlen)",
    ["opt_arrow_refresh_rate_60"] = "60 FPS (Flüssig)",
    ["opt_arrow_refresh_rate_unlimited"] = "Unbegrenzt (Jeder Frame)",
    ["opt_optimization_internal_only"] = "Diese Einstellung betrifft nur den integrierten Pfeil, wenn der interne Wegweiser aktiv ist.",
    ["opt_optimization_routing_header"] = "Reiserouten-Berechnung",
    ["opt_optimization_routing_desc"] = "Steuert, wie aggressiv das Reisesystem Routen berechnet und vorbereitet.",
    ["opt_pathfinding_speed"] = "Rechenbudget für Routen",
    ["opt_pathfinding_speed_desc"] = "Bestimmt die Arbeitslast von LibRover pro Update. Niedrige Werte verhindern CPU-Spitzen; hohe Werte schließen Berechnungen schneller ab.",
    ["opt_pathfinding_speed_slow"] = "Langsam (Niedrigste Last)",
    ["opt_pathfinding_speed_medium"] = "Mittel",
    ["opt_pathfinding_speed_fast"] = "Schnell (Schnellste Updates)",
    ["opt_travel_full_linking_startup"] = "Vollständige Reiseverknüpfungen beim Start",
    ["opt_travel_full_linking_startup_desc"] = "Berechnet mehr Reiseverbindungen beim Login vor. Dies verbessert die spätere Reaktionszeit auf Kosten eines längeren Startvorgangs.",
    ["opt_optimization_memory_header"] = "Speicher & Laden",
    ["opt_optimization_memory_desc"] = "Künftiges Ziel: Geringere initiale Speichernutzung durch selektives Laden von Guides. In dieser Version noch nicht implementiert.",
    ["opt_optimization_diagnostics_header"] = "Diagnose",
    ["opt_optimization_diagnostics_desc"] = "Künftiges Ziel: Leichtgewichtige FPS- oder Speicherdiagnose zur Analyse von Rucklern. In dieser Version noch nicht implementiert.",
} end)

