if GetLocale()~="frFR" then return end

-- These are the main viewer's lines.

local COLOR_TIP_MOUSE = "|cffeedd99"
local COLOR_TIP_HINT = "|cff99ff00"
local COLOR_TIP = "|cff00ff00"

local COLOR_GOAL_LOC = "|cffffee77"
local COLOR_GOAL_COUNT = "|cffffffcc"
local COLOR_GOAL_ITEM = "|cffaaeeff"
local COLOR_GOAL_QUEST = "|cffbb99ff"
local COLOR_GOAL_NPC = "|cffaaffaa"
local COLOR_GOAL_MONSTER = "|cffffaaaa"
local COLOR_GOAL_GOAL = "|cffffcccc"



ZygorGuidesViewer_L("Main", "frFR", function() return {
	["name"] = "|cffffff88Z|cffffee66y|cffffdd44g|cffffcc22o|cffffbb00r |cffffaa00Guides Viewer|r",
	["name_plain"] = "Visionneuse de guides Zygor",
	["desc"] = "Parametres principaux de Zygor Guides Viewer %s.|n",

	['welcome_guides'] = "%d guides charges.",

	["opt_guide"] = "Selectionnez un guide :",
	["opt_guide_steps"] = "Etapes : %d",
	["opt_guide_author"] = "Auteur : %s",
	["opt_guide_next"] = "Suivant dans la serie : %s",

	["opt_report"] = "Creer un rapport de bug",
	["opt_report_desc"] = "Cree un rapport de bug avec les details de l'etape actuellement affichee. Copiez/collez-le puis envoyez-le aux auteurs du guide.",

	["opt_visible"] = "Afficher la fenetre Zygor Guides Viewer",
	["opt_visible_desc"] = "",
	["opt_hideincombat"] = "Masquer les guides en combat",
	["opt_hideincombat_desc"] = "Masquer toutes les fenetres de guide pendant le combat si l'ecran devient trop charge.",
	
	--["opt_group_main"] = "Main window settings",
	["opt_opacitymain"] = "Opacite",
	["opt_opacitymain_desc"] = "Opacite de la fenetre principale.",
	["opt_framescale"] = "Echelle",
	["opt_framescale_desc"] = "Redimensionnez la fenetre selon vos preferences.",
	["opt_fontsize"] = "Taille du texte",
	["opt_fontsize_desc"] = "Definit votre taille de texte preferee. L'echelle de la fenetre affecte aussi cette valeur.",
	["opt_fontsecsize"] = "Taille du texte secondaire",
	["opt_fontsecsize_desc"] = "Definit la taille du texte secondaire utilise pour les descriptions et notes.",
	["opt_backcolor"] = "Couleur d'arriere-plan",
	["opt_backcolor_desc"] = "Couleur d'arriere-plan de la fenetre.",

	["opt_group_window"] = "Fonctions de la fenetre",
	--["opt_minimapnotedesc"] = "Show waypoint caption",
	--["opt_minimapnotedesc_desc"] = "Show the relevant waypoint's caption not only on the waypoint's tooltip, but on the mini window as well.",
	--["opt_showgoals"] = "Show step goals",
	--["opt_showgoals_desc"] = "Show step completion goals in the mini window",
	--["opt_autosizemini"] = "Auto-size",
	--["opt_autosizemini_desc"] = "Automatically adjust the height of the mini window.",
	["opt_miniresizeup"] = "Redimensionner vers le haut",
	["opt_miniresizeup_desc"] = "Inverse la fenetre pour qu'elle s'etende vers le haut au lieu du bas. Utile si elle est placee en bas de l'ecran.",
	["opt_opacitymini"] = "Opacite de l'arriere-plan",
	["opt_opacitymini_desc"] = "Opacite de l'arriere-plan de la fenetre d'etapes.",

	--["opt_showallsteps"] = "Collapsed mode",
	--["opt_showallsteps_desc"] = "Display only the current step and some next steps, instead of the whole guide",

	["opt_showcountsteps"] = "Afficher les etapes :",
	["opt_showcountsteps_desc"] = "Nombre d'etapes a afficher.\n|cffffffaaTous|r affiche toutes les etapes dans une liste defilante.\n|cffffffaa1-5|r affiche l'etape actuelle en haut et redimensionne automatiquement la fenetre pour afficher seulement quelques etapes suivantes.",
	["opt_showcountsteps_all"] = "Tous",

	["opt_group_map"] = "Points de passage",
	["opt_group_map_desc"] = "Ces parametres definissent comment Zygor Guides Viewer interagit avec les addons de carte.",
	["opt_group_map_waypointing"] = "Addon de points de passage",
	["opt_group_map_waypointing_desc"] = "Selectionnez l'addon qui gerera les points de passage pour Zygor Guides Viewer.",
	["opt_group_addons_builtin"] = "Points de passage integres",
	["opt_group_addons_tomtom"] = "TomTom",
	["opt_group_addons_cart2"] = "Cartographer 2",
	["opt_group_addons_cart3"] = "Cartographer 3",
	["opt_group_addons_metamap"] = "MetaMap",
	["opt_group_addons_none"] = "aucun",
	["opt_debug"] = "Debogage",
	["opt_debug_desc"] = "Afficher les informations de debogage.",
	["opt_debugging"] = "Debogage",
	["opt_debugging_desc"] = "Options de debogage.",
	--["opt_browse"] = "Toggle windows",
	 --["opt_browse_desc"] = "Toggle the visibility of either of Zygor's Guides windows.",

	["opt_autoskip"] = "Avancer automatiquement",
	["opt_autoskip_desc"] = "Passe automatiquement a l'etape suivante quand toutes les conditions sont remplies. Certaines etapes peuvent encore necessiter un passage manuel si leurs conditions sont trop complexes.",

	["opt_goalicons"] = "Afficher les icones d'etape",
	["opt_goalicons_desc"] = "Afficher des icones indiquant l'etat d'avancement.",
	["opt_goalcolorize"] = "Colorer les lignes completes",
	["opt_goalcolorize_desc"] = "Colore entierement en vert les lignes d'etape completees.",
	["opt_goalbackprogress"] = "Appliquer des couleurs selon le pourcentage",
	["opt_goalbackprogress_desc"] = "Affiche la progression partielle avec des couleurs intermediaires entre incomplet et complet.|nSi desactive, les objectifs utilisent uniquement les couleurs 'incomplet' ou 'complet'.",

	["opt_group_step"] = "Objectifs de l'etape",

	["opt_goalbackcolor_desc"] = "Couleurs de completion :",
	["opt_goalbackgrounds"] = "Colorer les arriere-plans",
	["opt_goalbackgrounds_desc"] = "Colorer l'arriere-plan des lignes d'etape selon l'etat d'avancement.",
	["opt_goalbackcomplete"] = "Complet",
	["opt_goalbackcomplete_desc"] = "Utiliser cette couleur pour les objectifs completes.",
	["opt_goalbackincomplete"] = "Incomplet",
	["opt_goalbackincomplete_desc"] = "Utiliser cette couleur pour les objectifs incomplets.",
	["opt_goalbackimpossible"] = "Impossible a completer",
	["opt_goalbackimpossible_desc"] = "Utiliser cette couleur pour les objectifs impossibles a completer pour le moment.",

	['opt_tooltipsbelow'] = "Afficher les informations supplementaires en ligne",
	['opt_tooltipsbelow_desc'] = "Les informations supplementaires de certaines lignes d'etape peuvent etre affichees en ligne ou dans des info-bulles au survol.",

	["opt_flash_desc"] = "Notification de progression :",
	["opt_goalcompletionflash"] = "Faire clignoter l'objectif a la completion",
	["opt_goalcompletionflash_desc"] = "Utiliser un effet visuel de clignotement quand un objectif est complete.",
	["opt_goalupdateflash"] = "Faire clignoter l'objectif en progression",
	["opt_goalupdateflash_desc"] = "Utiliser un effet visuel de clignotement quand un objectif progresse.",
	["opt_flashborder"] = "Faire clignoter la fenetre a la fin d'une etape",
	["opt_flashborder_desc"] = "Faire clignoter toute la fenetre a chaque etape completee.",

	--["opt_colorborder"] = "Color step window border",
	--["opt_colorborder_desc"] = "Use the step window border's color to indicate completion of the whole step.",

	["opt_group_display"] = "Affichage",
	["opt_group_display_desc"] = "Reglez la facon dont les guides doivent etre affiches.",

	["opt_group_data"] = "Guides stockes",
	["opt_group_data_desc"] = "Zygor Guides Viewer peut stocker en interne des guides commerciaux qui ne peuvent pas etre distribues comme addons separes.",
	["opt_group_data_guide"] = "Guides stockes en interne :",
	["opt_group_data_guide_desc"] = "Selectionnez un guide stocke dans cette liste pour le modifier ou le supprimer. Cette liste n'affiche PAS les guides charges comme addons separes.",
	["opt_group_data_del"] = "Supprimer le guide",
	["opt_group_data_del_desc"] = "Supprime le guide selectionne du stockage interne.",
	["opt_group_data_edit"] = "Modifier le guide",
	["opt_group_data_edit_desc"] = "Charge le guide selectionne dans la fenetre d'edition ci-dessous pour le corriger.",
	["opt_group_data_entry"] = "Donnees du guide :",
	["opt_group_data_entry_desc"] = "Collez un nouveau guide ici (pensez a entourer ses etapes par :|nguide Title Of Guide|nsteps...|nsteps...|nend\n); le collage et l'analyse d'un gros guide (>30kB) peuvent prendre quelques secondes.",

	['opt_windowlocked'] = "Verrouiller la fenetre",
	['opt_windowlocked_desc'] = "Verrouille la fenetre pour la rendre non interactive a la souris.\nSeuls les boutons restent actifs.",
	['opt_hideborder'] = "Masquage automatique de la bordure",
	['opt_hideborder_desc'] = "Masque automatiquement la bordure et les boutons de la fenetre lorsque la souris est ailleurs.\nSurvolez un instant le titre de la fenetre pour les faire reapparaitre.",

	['opt_skin'] = "Couleur du theme de fenetre",
	['opt_skin_desc'] = "Choisissez une couleur pour les decorations de fenetre selon votre interface.",
	['opt_skin_violet'] = "|cffee55ffViolet",
	['opt_skin_green'] = "|cff88ff88Vert",
	['opt_skin_blue'] = "|cff99aaffBleu",
	['opt_skin_orange'] = "|cffffbb00Orange",
	["opt_skinpanel_title"] = "Apparence",
	["opt_skinpanel_desc"] = "Choisissez le thème visuel du visionneur de guides.",
	["opt_skinpanel_intro"] = "Choisissez d'abord l'apparence générale du visionneur, puis ajustez la taille, l'opacité et le texte. Remaster reste l'apparence recommandée par défaut, tandis que Retail offre un rendu plus proche de l'interface Blizzard.",
	["opt_skinpanel_skin"] = "Thème",
	["opt_skinpanel_skin_desc"] = "Choisissez un thème et sa variante de couleur.",
	["opt_skinpanel_appearance_header"] = "Apparence",
	["opt_skinpanel_appearance_desc"] = "Ajustez l'échelle du visionneur, la taille du texte et l'opacité du cadre.",
	["opt_skinpanel_colors_header"] = "Couleurs",
	["opt_skinpanel_colors_desc"] = "Ajustez l'intensité du fond du cadre pour la variante de thème sélectionnée.",
	["opt_skinpanel_advanced_header"] = "Avancé",
	["opt_skinpanel_advanced_desc"] = "Contrôles d'affichage moins fréquents qui influencent la disposition du cadre et la présentation des étapes.",

	['opt_backopacity'] = "Opacite de l'arriere-plan",
	['opt_backopacity_desc'] = "Opacite de l'arriere-plan de la fenetre.",



	--["mainframe_guide"] = "Select a guide:",
	--["mainframe_notloaded"] = "No leveling guides are loaded.|n|nPlease go to http://zygorguides.com to purchase Zygor's 1-80 Leveling Guides, or load some third-party guides.|n|nIf you're sure you have installed some guides, ask their authors for installation troubleshooting.",
	--["mainframe_notselected"] = "%d guides are loaded.|nPlease select a guide from the list above.",


	["report_title"] = "Appuyez sur Ctrl+C pour copier ce rapport.|nEnsuite, envoyez-le a l'auteur de |cffffffff%s|r,|na |cffffffff%s|r.",
	["report_notitle"] = "|cffff8888(guide sans nom ?)|r",
	["report_noauthor"] = "|cffff8888(adresse indisponible)|r",


	["opt_mapbutton"] = "Afficher le bouton de minicarte",
	["opt_mapbutton_desc"] = "Afficher le bouton Zygor Guides Viewer a cote de votre minicarte",

	["minimap_tooltip"] = COLOR_TIP_MOUSE.."Clic|r pour afficher/masquer la fenetre du guide|n"..COLOR_TIP_MOUSE.."Clic droit|r pour configurer|n", --..COLOR_TIP_MOUSE.."Drag|r to move icon"


	["waypointaddon_set"] = "Addon de points de passage selectionne : %s",
	["waypointaddon_connecting"] = "Connexion a l'addon de points de passage : %s",
	["waypointaddon_connected"] = "Connexion reussie a %s.",
	["waypointaddon_fail"] = "Echec de connexion a %s.",
	['waypoint_step'] = "Etape %s",

	["checkmap"] = "Verifiez votre carte.",

	["initialized"] = 'Initialise.',

	["miniframe_notloaded"] = "Aucun guide de progression n'est charge.|n|nRendez-vous sur http://zygorguides.com pour acheter les guides Zygor 1-80, ou chargez des guides tiers.|n|nSi vous etes sur d'avoir installe des guides, contactez leurs auteurs pour l'aide a l'installation.",
	["miniframe_notselected"] = "Aucun guide n'est actuellement selectionne.\nVeuillez cliquer sur le bouton clignotant ci-dessus pour choisir un guide.",

	['frame_locked'] = "Fenetre verrouillee",
	['frame_unlock'] = COLOR_TIP_MOUSE.."Clic|r pour deverrouiller",
	['frame_unlocked'] = "Fenetre deverrouillee",
	['frame_lock'] = COLOR_TIP_MOUSE.."Clic|r pour verrouiller",
	['frame_settings'] = "Parametres",
	['frame_settings1'] = COLOR_TIP_MOUSE.."Clic|r pour regler les options de base",
	['frame_settings2'] = COLOR_TIP_MOUSE.."Clic droit|r pour ouvrir la configuration",
	['frame_minimized'] = "Affiche |cffffffff%d|r etape(s)",
	['frame_maximized'] = "Affiche toutes les etapes",
	['frame_minimize'] = COLOR_TIP_MOUSE.."Clic|r pour n'afficher que |cffffffff%d|r",
	['frame_maximize'] = COLOR_TIP_MOUSE.."Clic|r pour tout afficher",
	['frame_stepnav_prev'] = "Etape precedente",
	['frame_stepnav_prev_click'] = COLOR_TIP_MOUSE.."Clic|r pour revenir",
	['frame_stepnav_next'] = "Etape suivante",
	['frame_stepnav_next_click'] = COLOR_TIP_MOUSE.."Clic|r pour passer",
	['frame_stepnav_next_right'] = COLOR_TIP_MOUSE.."Clic droit|r pour avancer rapidement",
	['frame_section'] = "Guide actuel",
	['frame_section_click'] = COLOR_TIP_MOUSE.."Clic|r pour selectionner",


	['tooltip_tip'] = COLOR_TIP_HINT.."%s|r",
	['tooltip_waypoint'] = COLOR_TIP_MOUSE.."Clic|r"..COLOR_TIP.." pour definir le point de passage : |cffffaa00%s|r",
	['tooltip_waypoint_coords'] = "Position : |cffffaa00%s|r",

	["message_errorloading_full"] = "|cffff4444Erreur|r lors du chargement du guide |cffaaffaa%s|r\nligne %d : %s\nerreur : %s",
	["message_errorloading_brief"] = "|cffff4444Erreur|r lors du chargement du guide |cffaaffaa%s|r",
	["message_loadedguide"] = "Guide active : |cffaaffaa%s|r",
	["message_missingguide"] = "|cffff4444Guide manquant|r : |cffaaffaa%s|r",
	["title_noguide"] = "Zygor Guides Viewer (aucun guide chargé)",


	['step_num'] = "|cffaaaaaa%s|cff888888.|r ",
	['step_level'] = "|cffaaccaaNiveau : |cffcceecc%s|cffaaccaa|r ",

	["questtitle"] = "`%s'",
	["questtitle_part"] = "`%s' (partie %s)",
	["coords"] = "%d,%d",
	["map_coords"] = "%s %d,%d",

	["stepgoal_home"] = "Définissez votre foyer à %s",
	["stepgoal_flightpath"] = "Prenez le trajet aérien %s",

	["stepgoal_accept"] = "Acceptez %s",
	["stepgoal_turn in"] = "Rendez %s",
	["stepgoal_talk to"] = "Parlez à %s",
	["stepgoal_kill"] = "Tuez %s",
	["stepgoal_kill #"] = "Tuez %s %s",
	["stepgoal_goal"] = "%s",
	["stepgoal_goal #"] = "%s %s",
	["stepgoal_get"] = "Obtenez %s",
	["stepgoal_get #"] = "Obtenez %s %s",
	["stepgoal_ding"] = "Vous devriez maintenant être niveau %s.|n    Sinon, tuez quelques monstres jusqu'à l'atteindre.",
	["stepgoal_go to"] = "Allez au %s",
	["stepgoal_also at"] = "Aussi à %s",
	["stepgoal_hearth to"] = "Utilisez votre pierre de foyer vers %s",
	["stepgoal_collect"] = "Collectez %s",
	["stepgoal_collect #"] = "Collectez %s %s",
	["stepgoal_buy"] = "Achetez %s %s",
	["stepgoal_fpath"] = "Prenez le trajet aérien %s",
	["stepgoal_use"] = "Utilisez %s",
	["stepgoal_home"] = "Faites de %s votre foyer",
	["stepgoal_petaction"] = "Utilisez l'action de familier %s",
	["stepgoal_havebuff"] = "Obtenez l'effet/buff '%s'",
	["stepgoal_nobuff"] = "Perdez l'effet/buff '%s'",
	["stepgoal_invehicle"] = "Montez dans le véhicule",
	["stepgoal_outvehicle"] = "Sortez du véhicule",
	["stepgoal_equipped"] = "Équipez %s",
	["stepgoal_at_suff"] = " (%s)",

	["completion_collect"] = "(%s/%s)",
	["completion_goal"] = "(%s/%s)",
	["completion_ding"] = "(%s%%)",
	--["completion_(done)"] = "(done)",

--[[
	["stepgoalshort_complete"] = "termine",
	["stepgoalshort_incomplete"] = "en attente",
	["stepgoalshort_questgoal"] = "(%d/%d)",
	["stepgoalshort_level"] = "(%d%%)",
--]]

	["step_req"] = "Étape valable uniquement pour : %s",


	["map_highlight"] = "Surligner",

	["stepreq"] = "Exigence de classe/race pour l'étape : ",
	["stepreqor"] = " ou ",

	["opt_do_searchforgoal"] = "Trouver un objectif réalisable",
	["searching_for_goal_success"] = "Un objectif réalisable a été trouvé pour vous : %s. Cela peut être un bon point de départ dans le guide.",
	["searching_for_goal_failed"] = "Aucun objectif réalisable n'a été trouvé. Essayez un autre guide ou une autre section, prenez quelques quêtes, ou relancez la recherche depuis le début de la section (la recherche se fait uniquement vers l'avant).",

	["going"] = "%d%% vers %s",
	["miniframe_loading"] = "Chargement des guides : %d%%",
	["menu_last"] = "Guides utilises recemment",
	["menu_last_entry"] = "%s |cffaaffaa%d|r",
	["gb_window_title"] = "Navigateur de guides",
	["gb_addon_title"] = "Zygor Guides Viewer Remastered",
	["gb_root"] = "Accueil",
	["gb_search"] = "Recherche",
	["gb_folders"] = "Dossiers",
	["gb_guides"] = "Guides",
	["gb_load_guide"] = "Charger le guide",
	["gb_open_legacy"] = "Ouvrir le sélecteur classique",
	["gb_path_format"] = "Chemin : %s",
	["gb_select_guide"] = "Sélectionnez un guide",
	["gb_select_guide_from_list"] = "Sélectionnez un guide dans la liste.",
	["gb_select_settings_page"] = "Sélectionnez une page de réglages",
	["gb_all_guides"] = "Tous les guides",
	["gb_other"] = "Autre",
	["gb_unknown"] = "inconnu",
	["gb_none"] = "aucun",
	["gb_folder_format"] = "Dossier : %s",
	["gb_progress_format"] = "Progression : %d%%",
	["gb_guides_count_format"] = "%d guides",
	["gb_current_meta_format"] = "Étape %d / %d  |  %s",
	["gb_detail_meta_format"] = "Étapes : %d\nAuteur : %s\nSuivant : %s",
	["gb_tab_home"] = "Accueil",
	["gb_tab_featured"] = "En vedette",
	["gb_tab_current"] = "Actuel",
	["gb_tab_recent"] = "Recents",
	["gb_tab_options"] = "Options",
	["gb_cat_leveling"] = "Montée en niveau",
	["gb_cat_dungeons"] = "Donjons",
	["gb_cat_daily"] = "Quotidien",
	["gb_cat_events"] = "Événements",
	["gb_cat_reputations"] = "Réputations",
	["gb_cat_gold"] = "Or",
	["gb_cat_professions"] = "Métiers",
	["gb_cat_petsmounts"] = "Mascottes et montures",
	["gb_cat_titles"] = "Titres",
	["gb_cat_achievements"] = "Hauts faits",
	["gb_cat_misc"] = "Divers",
	["gb_cat_favorites"] = "Favoris",
	["gb_opt_guides"] = "Guides",
	["gb_opt_desc_guides"] = "Sélection du guide, informations sur le guide actif et contrôles principaux.",
	["gb_opt_stepdisplay"] = "Affichage des etapes",
	["gb_opt_desc_stepdisplay"] = "Visuels du viewer, disposition de la fenetre, apparence/polices et affichage des etapes et objectifs.",
	["gb_opt_progress"] = "Progression",
	["gb_opt_desc_progress"] = "Comportement de progression, règles de saut et flux d'achèvement.",
	["gb_opt_travel"] = "Systeme de trajet",
	["gb_opt_desc_travel"] = "Choix du fournisseur de points et comportement du systeme de trajet.",
	["gb_opt_map"] = "Cartes et points",
	["gb_opt_desc_map"] = "Style de fleche, marqueurs minicarte/carte et visuels des points.",
	["gb_opt_notifications"] = "Notifications",
	["gb_opt_desc_notifications"] = "Indices visuels de progression et de completion.",
	["gb_opt_actionbuttons"] = "Boutons d'action",
	["gb_opt_desc_actionbuttons"] = "Comportement d'affichage des interactions cliquables d'etapes/objectifs.",
	["gb_opt_convenience"] = "Quetes",
	["gb_opt_desc_convenience"] = "Aides de confort pour accepter/rendre automatiquement les quetes.",
	["gb_opt_accessibility"] = "Accessibilite",
	["gb_opt_desc_accessibility"] = "Options de visibilite des couleurs et de lisibilite.",
	["gb_opt_profile"] = "Profils",
	["gb_opt_desc_profile"] = "Gestion des profils par personnage/global et outils de copie/reinitialisation.",
	["gb_opt_about"] = "A propos",
	["gb_opt_desc_about"] = "Version, assistance et outils de diagnostic/signalement.",
	["gb_opt_advanced"] = "Avance",
	["gb_opt_desc_advanced"] = "Outils de debug, diagnostic et controles pour developpeurs.",
	["gb_opt_general"] = "Général",
	["gb_opt_desc_general"] = "Réglages généraux.",
	["gb_title_viewer"] = "Visionneuse",
	["gb_options_viewer_desc"] = "Comportement principal du visionneur, chargement des guides et contrôles de base.",
	["gb_hint_search_settings"] = "Astuce :\nUtilisez la recherche a gauche pour trouver rapidement une page de reglages.",
	["gb_hint_options_filter"] = "Astuce :\nLa recherche a gauche filtre les pages d'options.\nUtilisez Ouvrir les options completes pour le panneau Blizzard complet.",
	["gb_empty_no_guides_search"] = "Aucun guide ne correspond a cette recherche.",
	["gb_empty_no_guides_category"] = "Aucun guide dans cette categorie.",
	["gb_empty_no_current_guide"] = "Aucun guide actuel charge.",
	["gb_empty_no_current_guide_short"] = "Aucun guide actuel charge",
	["gb_empty_no_recent_guides"] = "Aucun guide recent pour le moment.",
	["gb_empty_no_featured_match"] = "Aucune suggestion mise en avant ne correspond a ce filtre.",
	["gb_empty_no_featured_suggestions"] = "Aucune suggestion mise en avant",
	["gb_empty_no_favorites"] = "Aucun guide favori pour le moment.",
	["gb_no_guide_selected"] = "Aucun guide selectionne",
	["gb_action_clear_search"] = "Effacer la recherche",
	["gb_action_show_all_categories"] = "Afficher toutes les catégories",
	["gb_action_go_home"] = "Aller à l'accueil",
	["gb_action_open_home"] = "Ouvrir l'accueil",
	["gb_action_reset_snoozed"] = "Réinitialiser les suggestions masquées",
	["gb_action_clear_search_restore"] = "Effacez la recherche pour restaurer les suggestions",
	["gb_action_reset_snoozed_restore"] = "Réinitialise les suggestions masquées pour restaurer les recommandations",
	["gb_action_try_home"] = "Essayez l'accueil pour parcourir toutes les catégories",
	["gb_action_browse_all_from_home"] = "Parcourir tous les guides depuis l'accueil",
	["gb_action_back_to_guides"] = "Retour aux guides",
	["gb_action_open_full_options"] = "Ouvrir les options complètes",
	["gb_action_go_current_folder"] = "Aller au dossier du guide actuel",
	["gb_action_resume"] = "Reprendre",
	["gb_action_restart"] = "Redémarrer",
	["gb_nav_navigation"] = "Navigation",
	["gb_nav_back"] = "Retour",
	["gb_nav_reset_to_root"] = "Réinitialiser à la racine de la catégorie",
	["gb_featured_bucket_next"] = "À suivre",
	["gb_featured_bucket_progress"] = "En cours",
	["gb_featured_bucket_level"] = "Autour de votre niveau",
	["gb_featured_bucket_featured"] = "Routes recommandées",
	["gb_featured_confidence_strong"] = "Fort",
	["gb_featured_confidence_good"] = "Bonne",
	["gb_featured_confidence_fallback"] = "Alternative",
	["gb_roadmap"] = "Feuille de route",
	["gb_roadmap_bucket_format"] = "Feuille de route %s",
	["gb_bucket_preview_next_with_title"] = "Continuez votre chaîne : %s",
	["gb_bucket_preview_next"] = "Continuez votre chaîne",
	["gb_bucket_preview_progress_with_title"] = "Reprendre : %s",
	["gb_bucket_preview_progress"] = "Reprendre les guides en cours",
	["gb_bucket_preview_level_with_title"] = "Commencer une route adaptée : %s",
	["gb_bucket_preview_level"] = "Commencer des guides adaptés à votre niveau",
	["gb_bucket_preview_featured_with_title"] = "Route optionnelle : %s",
	["gb_bucket_preview_featured"] = "Routes optionnelles et extras",
	["gb_meta_action"] = "Action",
	["gb_meta_suggestion"] = "Suggestion",
	["gb_meta_suggested"] = "Suggéré",
	["gb_meta_current"] = "Actuel",
	["gb_meta_recommended"] = "recommandé",
	["gb_meta_other_useful_option"] = "autre option utile",
	["gb_meta_current_selection"] = "sélection actuelle",
	["gb_meta_suggestions_snoozed"] = "les suggestions peuvent être masquées",
	["gb_meta_restore_recommendations"] = "restaurer les recommandations",
	["gb_meta_filter_no_matches"] = "le filtre ne renvoie aucun résultat",
	["gb_meta_see_full_recommendations"] = "voir toutes les recommandations",
	["gb_meta_no_bucket_suggestions"] = "aucune suggestion dans cette section",
	["gb_meta_full_category_access"] = "accès complet à la catégorie",
	["gb_meta_suggested_from"] = "Suggéré depuis : %s",
	["gb_meta_confidence"] = "Confiance : %s",
	["gb_meta_why_prefix"] = "Pourquoi : ",
	["gb_meta_gain_prefix"] = "Gain : ",
	["gb_reason_recently_used"] = "utilisé récemment",
	["gb_reason_incomplete"] = "incomplet",
	["gb_reason_your_level_range"] = "votre tranche de niveau",
	["gb_reason_near_your_level"] = "proche de votre niveau",
	["gb_reason_your_class"] = "votre classe",
	["gb_reason_your_race"] = "votre race",
	["gb_reason_your_profession"] = "votre métier",
	["gb_reason_favorite"] = "favori",
	["gb_reason_current_chain"] = "chaîne actuelle",
	["gb_reason_chain_step_format"] = "étape de chaîne +%d",
	["gb_reason_inferred_continuation"] = "continuation déduite",
	["gb_reason_chapter_continuation"] = "continuation du chapitre",
	["gb_tooltip_featured_controls"] = "Contrôles des suggestions recommandées",
	["gb_tooltip_featured_click"] = "Cliquez sur le X : masquer pendant 24 heures",
	["gb_tooltip_featured_shift_click"] = "Maj+clic sur X : masquer pour cette session",
	["gb_tooltip_featured_restore"] = "Appuyez sur R ou utilisez la réinitialisation dans les options pour restaurer.",
	["gb_tooltip_snooze"] = "Masquer la suggestion",
	["gb_tooltip_snooze_click"] = "Clic : masquer pendant 24 heures",
	["gb_tooltip_snooze_shift_click"] = "Maj+clic : masquer pour cette session",
	["gb_tooltip_why_prefix"] = "Pourquoi : ",
	["gb_tooltip_gain_prefix"] = "Gain : ",
	["gb_tooltip_confidence_prefix"] = "Confiance : ",
	["gb_tooltip_chain_prefix"] = "Chaîne : ",
	["gb_tooltip_fallback_recommendation"] = "Recommandation de secours",
	["gb_current_guide"] = "Guide actuel",
	["gb_options_fallback_embed_unavailable"] = "Les options integrees sont indisponibles. Cliquez a nouveau sur Options pour ouvrir les options d'interface Blizzard.",
	["gb_options_fallback_missing_widgets"] = "Les options integrees sont indisponibles. Widgets d'integration AceGUI manquants.",
	["gb_options_fallback_render_error"] = "Impossible d'afficher les options integrees : %s",
	["opt_legacyguideddropdown"] = "Menu deroulant de guide classique",
	["opt_featured_header"] = "Suggestions mises en avant",
	["opt_featured_enablefallback"] = "Activer les suggestions de secours",
	["opt_featured_enablefallback_desc"] = "Quand un groupe mis en avant n'a aucun resultat direct, afficher quelques guides de secours utiles.",
	["opt_featured_hiderecentcompleted"] = "Masquer les guides termines recemment",
	["opt_featured_hiderecentcompleted_desc"] = "Masquer des recommandations intelligentes les guides termines il y a tres peu de temps.",
	["opt_featured_showconfidence"] = "Afficher les niveaux de confiance",
	["opt_featured_showconfidence_desc"] = "Afficher les marqueurs Strong/Good/Fallback dans les lignes mises en avant.",
	["opt_featured_resethidden"] = "Reinitialiser les suggestions masquees",
	["opt_featured_resethidden_desc"] = "Restaurer les suggestions masquees via le bouton de fermeture.",
	["opt_disablerouteloopstacking"] = "Desactiver l'empilement route/boucle",
	["opt_disablerouteloopstacking_desc"] = "Empeche les sections de route et de boucle de s'empiler dans le meme groupe mis en avant.",
	["opt_routeantminimapmode"] = "Trace de route sur la minicarte",
	["opt_routeantminimapmode_desc"] = "Choisissez quelle partie de la trace animee doit apparaitre sur la minicarte.",
	["opt_routeantminimapmode_local"] = "Segment cible",
	["opt_routeantminimapmode_local_desc"] = "Affiche uniquement la portion locale de la route : point precedent, point actuel et point suivant.",
	["opt_routeantminimapmode_all"] = "Route complete",
	["opt_routeantminimapmode_all_desc"] = "Affiche toute la route ou la boucle sur la minicarte.",
	["opt_routeantminimapmode_none"] = "Point de passage uniquement",
	["opt_routeantminimapmode_none_desc"] = "Masque la trace animee sur la minicarte et n'affiche que le point de passage actif.",
	["opt_routeantdensity"] = "Densite de la trace",
	["opt_routeantdensity_desc"] = "Ajuste l'espacement des marqueurs animes entre les points de route. 1 est leger, 5 correspond a la valeur actuelle et 9 est la densite maximale.",
	["opt_accessibility_intro"] = "Ajustez les options visuelles d'accessibilite pour les couleurs et la lisibilite du texte.",
	["opt_colorblindmode"] = "Mode daltonien",
	["opt_colorblindmode_desc"] = "Remplace les couleurs du guide, de la fleche et de la distance par des palettes adaptees au daltonisme et force des couleurs de libelles de fleche plus contrastees.",
	["opt_colorblindmode_off"] = "Desactive",
	["opt_colorblindmode_protanopia"] = "Protanopie",
	["opt_colorblindmode_deuteranopia"] = "Deuteranopie",
	["opt_colorblindmode_tritanopia"] = "Tritanopie",
	["opt_colorblindmode_global"] = "Global",
	["opt_colorblindmode_custom"] = "Personnalise",
	["opt_arrowcolor_far"] = "Loin",
	["opt_arrowcolor_mid"] = "Moyen",
	["opt_arrowcolor_near"] = "Proche",
	["opt_simplifyarrownouncolors"] = "Couleurs simplifiees des libelles de fleche",
	["opt_simplifyarrownouncolors_desc"] = "Utiliser des couleurs plus nettes et plus contrastees pour les libelles de la fleche.",
	["opt_about_heading"] = "Zygor Guides Viewer Remastered pour WoTLK 3.3.5a",
	["opt_about_support"] = "Assistance",
	["opt_about_diag"] = "Astuce : `/zygor status` et `/zygor debug` aident au diagnostic.",
	["opt_showminimapicons"] = "Afficher les icones sur la minicarte",
	["opt_showminimapicons_desc"] = "Afficher les icones sur la minicarte",
	["opt_iconalpha"] = "Alpha des icones",
	["opt_iconalpha_desc"] = "Transparence alpha des icones de notes de carte",
	["opt_iconsize"] = "Taille des icones",
	["opt_iconsize_desc"] = "Taille des icones sur la carte",
	["opt_arrowshow"] = "Afficher la fleche",
	["opt_arrowshow_desc"] = "Afficher ou masquer la fleche interne de points de passage.",
	["opt_arrowcolormode_direction"] = "Direction",
	["opt_arrowcolormode_distance"] = "Distance",
	["opt_arrowtextoutline"] = "Contour du texte de fleche",
	["opt_arrowtextoutline_desc"] = "Choisissez la force du contour du texte de la fleche.",
	["opt_arrowtextoutline_default"] = "Par defaut",
	["opt_arrowtextoutline_strong"] = "Fort",
	["opt_arrowtextoutline_reduced"] = "Reduit",
	["opt_remasterpointeronlegacy"] = "Utiliser le pointeur remasterise sur les skins legacy",
	["opt_remasterpointeronlegacy_desc"] = "Si active, les skins legacy utilisent le style de fleche remasterise.",
	["opt_resetarrowposition"] = "Reinitialiser la position de la fleche",
	["opt_resetarrowposition_desc"] = "Reinitialise la fleche a la position par defaut de retail.",
	["opt_foglightdebug"] = "(Debug) Verifier foglight",
	["opt_foglightdebug_desc"] = "Verifier foglight pour la carte actuelle",
	["opt_travelsystem_intro"] = "Choisissez comment les fournisseurs de trajet et de points de passage sont geres.",
	["opt_mapswaypoints_intro"] = "Configurez les marqueurs de carte et l'apparence de la fleche interne.",
	["opt_notifications_intro"] = "Configurez les indices visuels de notification pendant la progression des etapes.",
	["opt_actionbuttons_intro"] = "Configurez les icones d'objectif et la presentation interactive des etapes.",
	["frame_toolbar_guides"] = "Guides",
	["frame_toolbar_guides_click"] = "pour ouvrir le menu des guides",
	["frame_toolbar_guides_right"] = "pour ouvrir le gestionnaire de guides",
	["frame_toolbar_close"] = "Fermer",
	["frame_toolbar_close_click"] = "pour fermer",
	["frame_toolbar_settings"] = "Options",
	["frame_toolbar_settings_click"] = "pour le menu rapide",
	["frame_toolbar_settings_right"] = "pour ouvrir les options du gestionnaire de guides",
	["frame_toolbar_stepview"] = "Vue des etapes",
	["frame_toolbar_stepview_showall"] = "pour tout afficher",
	["frame_toolbar_stepview_showonly"] = "pour n'afficher que |cffffffff%s|r",
	["frame_toolbar_stepview_setcount"] = "pour definir le nombre d'etapes",
	["frame_toolbar_unlock"] = "Deverrouiller la fenetre",
	["frame_toolbar_unlock_click"] = "pour deverrouiller",
	["frame_toolbar_lock"] = "Verrouiller la fenetre",
	["frame_toolbar_lock_click"] = "pour verrouiller",
	["frame_title_default"] = "Zygor Guides",
	["frame_tab_guides"] = "Guides",
	["frame_tab_spots"] = "Points",

	["completion_done"] = "(termine)",
	["completion_rep"] = "(%s)",

	["req_not"] = "pas %s",

	["stepgoal_rep"] = "Devenez %s envers %s",
	["stepgoal_achieve"] = "Obtenez le haut fait '%s'",
	["stepgoal_achievesub"] = "Terminez '%s' pour le haut fait '%s'",
	["stepgoal_skill"] = "Montez %s au niveau %s",
	["stepgoal_skillmax"] = "Montez %s au niveau maximum %s",
	["stepgoal_learn"] = "Apprenez a fabriquer %s",
	["stepgoal_or"] = "  - ou -",

	["binding_prev"] = "Etape precedente",
	["binding_next"] = "Etape suivante",

	["waypointaddon_detecting"] = "Tentative de detection automatique de l'addon de points...",
	["waypointaddon_disconnected"] = "Deconnecte de |cffddeeff%s|r.",
	["pointer_corpselabel1"] = "Ancien vous",
	["pointer_corpselabel2"] = "Celui qui apprend a fuir...",
	["pointer_corpselabel3"] = "Vous avez vise trop gros.",
	["pointer_corpselabel4"] = "Casseur de seau - par ici",
	["pointer_corpselabel5"] = "Ne pensez pas a la facture de reparation.",

	["opt_group_map_hidearrowwithguide"] = "Masquer la fleche a la fermeture du viewer",
	["opt_group_map_hidearrowwithguide_desc"] = "Activez ceci pour que la fleche suive la visibilite de la fenetre du guide.\nLaissez desactive si vous voulez garder la fleche visible quand les guides sont masques.",
	["opt_group_addons_internal"] = "Points integres",
	["opt_group_addons_carbonite"] = "Carbonite",
	["opt_stepnumber"] = "Afficher les numeros d'etapes",
	["opt_stepnumber_desc"] = "Affiche les numeros d'etapes et les niveaux conseilles pour chaque etape.\nDesactivez pour economiser de l'espace ecran.",
	["opt_hidestepborders"] = "Masquer les bordures",
	["opt_hidestepborders_desc"] = "Masque les bordures graphiques autour des etapes.",
	["opt_stepbackopacity"] = "Opacite du fond",
	["opt_stepbackopacity_desc"] = "Opacite du fond de la fenetre d'etape.\nLa couleur de fond suit l'etat de progression et est assombrie.",
	["opt_goalbackprogressing"] = "Intermediaire",
	["opt_goalbackprogressing_desc"] = "Cette couleur indique les objectifs a 50% de progression.",
	["opt_progressbackcolor_desc"] = "Couleurs d'etapes :",
	["opt_goalbackaux"] = "Deplacement",
	["opt_goalbackaux_desc"] = "Utilisez cette couleur pour les etapes de deplacement.",
	["opt_goalbackobsolete"] = "Perime",
	["opt_goalbackobsolete_desc"] = "Utilisez cette couleur pour les objectifs ou etapes obsoletes.",
	["opt_resetwindow"] = "Reinitialiser la fenetre",
	["opt_resetwindow_desc"] = "Si la fenetre sort de l'ecran, ce bouton la recentre.",
	["opt_trackchains"] = "Suivre les suites de quetes",
	["opt_trackchains_desc"] = "Marque les etapes d'acceptation de quete comme indisponibles si une quete prerequise n'a pas ete terminee.\n\nLa base des suites contient aussi des \"suites souples\" ; il est donc possible qu'une ligne d'acceptation soit marquee indisponible alors que la quete reste acceptabile.",
	["opt_guidesinhistory"] = "Nombre de guides recents",
	["opt_guidesinhistory_desc"] = "Affiche ce nombre de guides utilises recemment.",
	["opt_skin_remaster"] = "|cffc7d9ffRemaster (par defaut)",
	["opt_group_progress"] = "Progression dynamique",
	["opt_group_progress_desc"] = "Pour optimiser le leveling, cet addon peut ignorer dynamiquement les quetes peu utiles a votre niveau.",
	["opt_levelsahead"] = "Niveaux d'avance autorises",
	["opt_levelsahead_desc"] = "Ce reglage controle a quel point vous pouvez jouer en avance sur le guide.\nAvec 0, les quetes normalement faites sous votre niveau sont ignorees (si elles n'ont pas de suite).\nAvec 1 ou plus, seules les quetes de plus de ce nombre de niveaux sous vous seront ignorees.",
	["opt_showobsolete"] = "Marquer les etapes obsoletes",
	["opt_showobsolete_desc"] = "Marque les etapes obsoletes avec un fond gris.\nLes etapes sont obsoletes si leur niveau est trop bas pour vous.",
	["opt_skipobsolete"] = "Ignorer les etapes obsoletes",
	["opt_skipobsolete_desc"] = "Ignore automatiquement les etapes obsoletes.",
	["opt_skipauxsteps"] = "Ignorer les etapes de deplacement",
	["opt_skipauxsteps_desc"] = "Ignore automatiquement les etapes de deplacement si elles sont suivies d'etapes deja terminees ou obsoletes.\nCela evite de voyager loin pour decouvrir ensuite une etape d'acceptation deja faite.",
	["opt_skipflightsteps"] = "Supposer les trajets connus",
	["opt_skipflightsteps_desc"] = "Suppose que vous gerez vous-meme la decouverte des trajets aeriens et marque automatiquement ces etapes comme terminees.\n\nUtile surtout lors d'un saut dans un guide avance, moins en progression normale.",
	["opt_skipimpossible"] = "Ignorer les etapes impossibles",
	["opt_skipimpossible_desc"] = "Ignore automatiquement les etapes impossibles, pour eviter les objectifs de quetes volontairement ignorees.",
	["opt_group_progress_bottomdesc"] = "La progression dynamique marque les quetes comme \"obsoletes\" quand vous depassez les niveaux du guide de plus que la valeur definie ci-dessus. Les suites de quetes ne sont marquees obsoletes que si toute la suite l'est.\n\nPour les nouveaux joueurs, cela aide a utiliser le guide en ignorant intelligemment le contenu bas niveau, tout en conservant les suites utiles plus tard. Pour trouver un bon point de depart, chargez le guide de depart de votre race et laissez le viewer sauter les sections non pertinentes.\n\nPour les joueurs experimentes, cela evite que le guide ralentisse votre progression avec des quetes de bas niveau si vous gagnez des niveaux plus vite que prevu (par exemple via donjons ou bonus d'experience de repos). Vous pouvez definir jusqu'ou vous voulez prendre de l'avance avant que le guide ne pousse vers l'avant.",
	["opt_group_mapinternal"] = "Points internes",
	["opt_arrowmeters"] = "Systeme metrique",
	["opt_arrowmeters_desc"] = "Utilise metres et kilometres au lieu de yards et miles.",
	["opt_arrowfreeze"] = "La fleche ignore les clics",
	["opt_arrowfreeze_desc"] = "Fait ignorer les actions souris par la fleche. Desactivez pour la deplacer.",
	["opt_arrowcam"] = "Fleche liee a la camera",
	["opt_arrowcam_desc"] = "Affiche les directions selon l'orientation de la camera. Sinon, la fleche suit l'orientation du personnage.\n\nNote : en mode camera, la fleche peut paraitre inexacte avec le deplacement au clic.",
	["opt_arrowcolordir"] = "Couleur selon direction",
	["opt_arrowcolordir_desc"] = "Colore la gemme de la fleche en vert quand elle pointe vers la bonne direction.\n\nDesactivez si vous voulez du vert seulement a proximite de la destination.",
	["opt_arrowscale"] = "Echelle de la fleche",
	["opt_arrowscale_desc"] = "Taille de la fleche.",
	["opt_arrowfontsize"] = "Taille du texte de la fleche",
	["opt_arrowfontsize_desc"] = "Taille du texte affiche dans la fenetre de fleche.",
	["opt_minimapzoom"] = "Zoom minimap auto",
	["opt_minimapzoom_desc"] = "Augmente automatiquement le zoom de la minicarte quand un point est place, puis le restaure.",
	["opt_foglight"] = "Reveler la carte",
	["opt_foglight_desc"] = "Affiche les zones inexplorees sur la carte.",
	["opt_group_gold"] = "Guide Or",
	["opt_group_gold_desc"] = "Ces reglages controlent l'affichage des etapes de farm d'or et des ressources.",
	["opt_gold_detectiondist"] = "Distance de detection",
	["opt_gold_detectiondist_desc"] = "Distance de detection des points de farm d'or a proximite.",
	["opt_gold_reqmode"] = "Mode d'exigence",
	["opt_gold_reqmode_desc"] = "Definit quels types de points doivent etre pris en compte.",
	["opt_gold_reqmode_all"] = "Tous",
	["opt_gold_reqmode_current"] = "Guide actuel uniquement",
	["opt_gold_reqmode_future"] = "Actuel + guides futurs",
	["gold_missing_noguidesloaded"] = "Aucun guide Or charge.",
	["gold_missing_nospotsinrange"] = "Aucun point Or valide trouve dans la zone.",
	["gold_header_ore"] = "Gisements :",
	["gold_header_herb"] = "Herbes :",
	["gold_header_skin"] = "Peaux :",
	["gold_header_drop"] = "Butin sur |cffffdddd%s|r :",
	["opt_group_convenience"] = "Fonctions annexes",
	["opt_group_convenience_desc"] = "Diverses options utiles.",
	["opt_autoaccept"] = "Accepter les quetes automatiquement",
	["opt_autoaccept_desc"] = "Accepte automatiquement les quetes proposees.",
	["opt_autoturnin"] = "Rendre les quetes automatiquement",
	["opt_autoturnin_desc"] = "Rend automatiquement les quetes terminees.",
	["opt_fixblizzardautoaccept"] = "Corriger l'auto-acceptation Blizzard",
	["opt_fixblizzardautoaccept_desc"] = "Avec l'option Blizzard \"Accepter automatiquement les quetes\" activee, marque quand meme les etapes \"Accepter\" et \"Acceptee\" comme terminees.",
	["opt_audiocues"] = "Signaux audio",
	["opt_audiocues_desc"] = "Joue des sons lors des progres d'etapes.",
	["opt_analyzereps"] = "Analyser les reputations",
	["opt_analyzereps_desc"] = "Analyse vos reputations actuelles et marque les etapes non pertinentes comme obsoletes.",
	["opt_mapcoords"] = "Afficher les coordonnees carte",
	["opt_mapcoords_desc"] = "Affiche les coordonnees joueur et curseur dans les fenetres de carte.",
	["opt_targetpreview_growth"] = "Direction d'agrandissement",
	["opt_targetpreview_growth_desc"] = "Choisissez si l'aperçu de cible ancré doit suivre la direction de redimensionnement du viewer, grandir vers le haut ou vers le bas.",
	["opt_targetpreview_growth_auto"] = "Suivre le viewer",
	["opt_targetpreview_growth_up"] = "Grandir vers le haut",
	["opt_targetpreview_growth_down"] = "Grandir vers le bas",

	["haman$"] = "hamans",
	["(%a)man$"] = "%1men",

	["binding_togglewindow"] = "Afficher la fenêtre du guide",

} end)



local plurals = {
}

ZygorGuidesViewer_L("Specials", "frFR", function() return {
	["plural"] = function (word)
		return word
	end,
	['contract_mobs'] = false,
} end)



-- Add lines for any translations needed for:


-- MISC STRINGS

ZygorGuidesViewer_L("G_string", "frFR", function() return {
--	["blabla"] = TRUE,
} end)

ZygorGuidesViewer_L("Main", "frFR", function() return {
	["targetpreview_level"] = "Niveau",
	["targetpreview_class_boss"] = "Boss",
	["targetpreview_class_elite"] = "Élite",
	["targetpreview_class_rareelite"] = "Élite rare",
	["targetpreview_class_rare"] = "Rare",
	["targetpreview_title"] = "Aperçu de la cible",
	["targetpreview_title_locked"] = "Aperçu de la cible",
	["targetpreview_role_talk"] = "Parler à",
	["targetpreview_role_kill"] = "Tuer",
	["targetpreview_hint"] = "Cliquez pour cibler\ncette créature.",
	["targetpreview_hint_empty"] = "Aucune cible de dialogue ou de combat n'est active pour cette étape.",
	["targetpreview_empty_name"] = "Aucune cible",
	["popup_accept"] = "Accepter",
	["popup_decline"] = "Refuser",
	["actionbutton_bar_title"] = "Faites glisser pour déplacer les boutons d'action",
	["actionbutton_bar_title_locked"] = "Boutons d'action",
	["actionbutton_tooltip_talk"] = "Ciblez %s et essayez de le marquer avec un triangle vert.",
	["actionbutton_tooltip_kill"] = "Ciblez %s et essayez de le marquer avec une tête de mort.",
	["actionbutton_tooltip_script"] = "Exécute la macro du script de l'étape actuelle.",
	["actionbutton_tooltip_petaction"] = "Utilisez l'action de familier suggérée.",
	["gearfinder_title"] = "Chercheur d'équipement",
	["gearfinder_no_upgrade"] = "Aucune amélioration trouvée",
	["gearfinder_load_guide"] = "Charger le guide",
	["gearfinder_suggested_dungeon"] = "Donjon suggéré :",
	["gearfinder_refresh"] = "Cliquez pour actualiser",
	["gearfinder_status_searching"] = "Recherche d'améliorations%s",
	["gearfinder_status_searching_future"] = "Recherche d'améliorations futures%s",
	["gearfinder_label_dungeon"] = "Donjon :",
	["gearfinder_label_unknown"] = "Inconnu",
	["gearfinder_label_inbags"] = "Dans les sacs :",
	["gearfinder_label_score"] = "Score : %d",
	["gearfinder_label_score_value"] = "%.1f de score",
	["gearfinder_label_equipped"] = "Équipé",
	["gearfinder_label_empty"] = "Emplacement vide",
	["gearfinder_upgrade_percent"] = "+%d%% d'amélioration",
	["gearfinder_upgrade_percent_short"] = "%+.1f%%",
	["gearfinder_label_new_item"] = "Nouvel objet",
	["gearfinder_label_delta_score"] = "%+.1f de score",
	["gearfinder_label_best_gains"] = "Meilleurs gains : %s",
	["gearfinder_label_found"] = "Meilleur trouvé :",
	["gearfinder_label_future"] = "À venir :",
	["gearfinder_items_found"] = "%d objets trouvés",
	["itemscore_ae_equip"] = "Équiper %s",
	["itemscore_ae_over"] = " à la place de %s",
	["itemscore_ae_equip1"] = "Remplacer cet objet",
	["itemscore_ae_equip2"] = "Équiper cet objet",
	["itemscore_ae_with"] = "avec",
	["itemscore_ae_accept"] = "Équiper",
	["itemscore_ae_decline"] = "Pas maintenant",
	["itemscore_ae_report_tip"] = "Maintenez Maj et cliquez pour afficher un rapport détaillé sur l'équipement.\nLes objets refusés ne seront plus suggérés.",
	["itemscore_ae_build"] = "Spécialisation",
	["itemscore_questitem1"] = "Une quête nécessite cet objet.",
	["itemscore_questitem2"] = "L'équiper pour l'étape de quête actuelle ?",
	["itemscore_questitem3"] = "Rééquiper votre objet précédent ?",
	["notifcenter_gear_title"] = "Conseiller d'équipement",
	["notifcenter_gear_text"] = "Amélioration trouvée",
	["notifcenter_gear_text_sl"] = "%d amélioration trouvée",
	["notifcenter_gear_text_pl"] = "%d améliorations trouvées",
	["notifcenter_gear_equipped"] = "%s équipé dans l'emplacement %s",
	["notifcenter_quest_text"] = "Objet de quête",
	["notifcenter_gen_popup_tooltip"] = "Cliquez pour ouvrir",
	["opt_itemscore_ae_clearednotupgrade"] = "La liste des améliorations refusées a été vidée.",
	["opt_itemscore_warning"] = "Modifiez les poids des statistiques pour l'évaluation des objets. Des valeurs plus élevées rendent la statistique plus importante pour votre spécialisation.",
	["opt_gear_title"] = "Configurez l'évaluation automatique de l'équipement et la détection des améliorations.",
	["opt_gear_score_class"] = "Classe :",
	["opt_gear_score_spec"] = "Spécialisation :",
	["opt_gear_sources"] = "Sources du chercheur d'équipement",
	["opt_gear_sources_dungeons"] = "Donjons",
	["opt_gear_sources_raids"] = "Raids",
	["opt_quickscan_warning"] = "Mode de scan rapide : les liens d'objet n'ont pas été collectés.",
	["opt_actionbar_enable"] = "Activer la barre d'action",
	["opt_actionbar_enable_desc"] = "Affiche une barre d'action déplaçable pour les objectifs interactifs de l'étape actuelle.",
	["opt_inlinebuttons_enable"] = "Activer les boutons en ligne",
	["opt_inlinebuttons_enable_desc"] = "Affiche des boutons interactifs directement dans les lignes d'étape pour parler ou tuer. Ils sont masqués lorsque les icônes de ligne sont désactivées ou que la barre d'action est désactivée.",
	["opt_actionbar_onlywhenneeded"] = "Afficher seulement si nécessaire",
	["opt_actionbar_onlywhenneeded_desc"] = "Masque la barre d'action lorsque l'étape actuelle n'a aucun bouton interactif.",
	["opt_actionbar_locked"] = "Verrouiller la position de la barre d'action",
	["opt_actionbar_locked_desc"] = "Empêche la barre d'action d'être déplacée.",
	["opt_actionbar_scale"] = "Échelle de la barre d'action",
	["opt_actionbar_scale_desc"] = "Échelle de la barre d'action.",
	["opt_actionbar_size"] = "Taille du bouton",
	["opt_actionbar_size_desc"] = "Taille de chaque bouton de la barre d'action.",
	["opt_actionbar_spacing"] = "Espacement des boutons",
	["opt_actionbar_spacing_desc"] = "Espacement entre les boutons de la barre d'action.",
	["opt_actionbar_pinside"] = "Côté d'ancrage",
	["opt_actionbar_pinside_desc"] = "Choisissez le côté du viewer auquel la barre d'action doit s'attacher.",
	["opt_actionbar_pinside_top"] = "Haut",
	["opt_actionbar_pinside_bottom"] = "Bas",
	["opt_actionbar_pinside_left"] = "Gauche",
	["opt_actionbar_pinside_right"] = "Droite",
	["opt_actionbar_resetanchor"] = "Réinitialiser la position de la barre d'action",
	["opt_actionbar_resetanchor_desc"] = "Réinitialise la barre d'action à sa position ancrée par défaut.",
	["opt_actionbar_markers"] = "Activer les marqueurs de cible",
	["opt_actionbar_markers_desc"] = "Essaie de placer des marqueurs de raid sur les cibles à qui parler ou à tuer lorsque c'est possible.",
	["opt_targetpreview_header"] = "Aperçu de la cible",
	["opt_targetpreview_intro"] = "Affiche un panneau d'aperçu déplaçable pour la cible actuelle de dialogue ou de combat.",
	["opt_targetpreview_enable"] = "Activer l'aperçu de la cible",
	["opt_targetpreview_enable_desc"] = "Affiche un panneau déplaçable pour les cibles de dialogue et de combat de l'étape actuelle.",
	["opt_targetpreview_onlywhenneeded"] = "Afficher seulement lorsque pertinent",
	["opt_targetpreview_onlywhenneeded_desc"] = "Masque le panneau d'aperçu lorsque l'étape actuelle n'a aucune cible de dialogue ou de combat.",
	["opt_targetpreview_locked"] = "Verrouiller la position de l'aperçu",
	["opt_targetpreview_locked_desc"] = "Empêche le panneau d'aperçu de la cible d'être déplacé.",
	["opt_targetpreview_scale"] = "Échelle de l'aperçu",
	["opt_targetpreview_scale_desc"] = "Échelle du panneau d'aperçu de la cible.",
	["opt_targetpreview_width"] = "Largeur de l'aperçu",
	["opt_targetpreview_width_desc"] = "Largeur du panneau d'aperçu de la cible.",
	["opt_targetpreview_height"] = "Hauteur de l'aperçu",
	["opt_targetpreview_height_desc"] = "Hauteur du panneau d'aperçu de la cible.",
	["opt_targetpreview_pinside"] = "Côté d'ancrage",
	["opt_targetpreview_pinside_desc"] = "Choisissez le côté du viewer auquel l'aperçu de la cible doit s'attacher.",
	["opt_targetpreview_mode"] = "Mode d'aperçu",
	["opt_targetpreview_mode_desc"] = "Choisissez si l'aperçu préfère un modèle 3D en direct, une fiche d'information stylisée ou les deux.",
	["opt_targetpreview_mode_hybrid"] = "Hybride",
	["opt_targetpreview_mode_model"] = "3D uniquement",
	["opt_targetpreview_mode_card"] = "Fiche uniquement",
	["opt_targetpreview_resetanchor"] = "Réinitialiser la position de l'aperçu",
	["opt_targetpreview_resetanchor_desc"] = "Réinitialise le panneau d'aperçu de la cible à sa position ancrée par défaut.",
	["gold_app_no_goldguide"] = "Ouvrez le guide de l'or (/zgold) pour charger les données de tendance.",
	["gold_app_no_goldguide_short"] = "Ouvrez /zgold pour charger des guides. ",
	["gold_app_no_goldguide_tooltip"] = "Ouvrez la fenêtre du guide de l'or pour initialiser les données de tendance depuis les scans de l'hôtel des ventes.",
	["gold_app_no_scan_data"] = "Prix actuels inconnus. Scannez l'hôtel des ventes.",
	["gold_app_no_scan_data_short"] = "Prix actuels inconnus.",
	["gold_app_no_scan_data_tooltip"] = "Scannez l'hôtel des ventes pour collecter les prix actuels.",
	["gold_app_no_servertrends"] = "Aucune donnée de tendance. Scannez chaque jour pour construire des tendances.",
	["gold_app_no_servertrends_short"] = "Aucune donnée de tendance. ",
	["gold_app_no_servertrends_tooltip"] = "Scannez l'hôtel des ventes chaque jour pour créer des tendances de prix.",
	["gold_app_old_scan_data"] = "Les données de scan sont obsolètes. Scannez pour mettre à jour.",
	["gold_app_old_scan_data_short"] = "Scannez pour mettre à jour.",
	["gold_app_old_scan_data_tooltip"] = "Scannez l'hôtel des ventes pour actualiser les données de prix.",
	["gold_app_old_servertrends"] = "Les données de tendance sont obsolètes (%s). Scannez pour mettre à jour.",
	["gold_app_old_servertrends_short"] = "Les données de tendance sont obsolètes (%s). ",
	["gold_app_old_servertrends_tooltip"] = "Les données de tendance sont obsolètes. Scannez chaque jour.",
	["gold_app_trend_tooltip"] = "Les données de tendance sont construites à partir des scans de l'hôtel des ventes. Scannez chaque jour pour améliorer les données.",
	["gold_auctions_error_noresults"] = "Aucune enchère rentable trouvée.",
	["gold_crafting_error_noprofessions"] = "Vous n'avez pas de profession d'artisanat.",
	["gold_crafting_error_noresults"] = "Aucun objet fabriqué rentable trouvé.",
	["gold_crafting_error_recipesnotcached"] = "Aucune recette trouvée. Ouvrez d'abord votre fenêtre des métiers.",
	["gold_farming_error_noitemtype"] = "Aucun objet %s rentable à farmer trouvé pour votre niveau.",
	["gold_farming_error_noresults"] = "Aucun objet rentable à farmer trouvé pour votre niveau.",
	["gold_gathering_error_all_noprofessions"] = "Vous n'avez appris aucune profession de récolte.",
	["gold_gathering_error_one_noresults"] = "Aucune route de récolte rentable trouvée pour %s.",
	["gold_gathering_error_one_noskillin"] = "Vous n'avez pas appris %s.",
	["gold_gathering_error_one_noskillin_skills"] = "\n\nVos professions de récolte : %s",
	["gold_gathering_error_one_nothing"] = "Aucune route de récolte trouvée.\n\nVos professions de récolte : %s",
	["gold_gathering_error_prof"] = "%s (%d)",
	["gold_gathering_no_results"] = "Vous avez besoin d'une profession de récolte : Dépeçage, Herboristerie ou Minage.",
	["gold_general_open_window1"] = "\nOuvrez votre fenêtre des métiers pour mettre les recettes en cache.",
	["gold_general_open_window2"] = "\nOuvrez votre fenêtre des métiers pour mettre les recettes en cache.",
	["gold_expertmode_easylabel"] = "Facile",
	["gold_expertmode_easytooltip"] = "Afficher uniquement les objets qui devraient se vendre rapidement.",
	["gold_expertmode_expertlabel"] = "Expert",
	["gold_expertmode_experttooltip"] = "Afficher les objets à vente rapide et lente.\nLa marchandise peut mettre des jours à se vendre.",
	["gold_expertmode_generictooltip"] = "Définissez le mode d'investissement.",
	["frame_selectguide"] = "Charger le guide",
	["frame_selectguide_left"] = "Cliquez pour charger le guide du donjon",
	["frame_toolbar_stepview_options"] = "pour ouvrir les options d'affichage des étapes",
	["stepgoal_arrive"] = "Arrivez à %s",
	["stepgoal_cast"] = "Lancez %s",
	["stepgoal_click"] = "Cliquez sur %s",
	["stepgoal_fly"] = "Volez vers %s",
	["waypointaddon_disconnecting"] = "Déconnexion de l'addon de points de route : %s",
	["gb_opt_optimization"] = "Optimisation",
	["gb_opt_desc_optimization"] = "Réglages sensibles aux performances, cadence de mise à jour de la flèche et futurs contrôles d'optimisation.",
	["opt_optimization_intro"] = "Adjust performance-sensitive behaviors for the internal arrow and reserve space for future Wrath-specific optimization controls.",
	["opt_optimization_arrow_header"] = "Arrow Performance",
	["opt_optimization_arrow_desc"] = "Control how often the built-in waypoint arrow updates. Lower rates reduce CPU usage; higher rates look smoother.",
	["opt_arrow_refresh_rate"] = "Arrow Refresh Rate",
	["opt_arrow_refresh_rate_desc"] = "Controls how frequently the built-in waypoint arrow updates. Lower values reduce CPU usage; higher values improve smoothness.",
	["opt_arrow_refresh_rate_20"] = "20 FPS (Legacy Default)",
	["opt_arrow_refresh_rate_30"] = "30 FPS (Recommended)",
	["opt_arrow_refresh_rate_60"] = "60 FPS (Smooth)",
	["opt_arrow_refresh_rate_unlimited"] = "Unlimited (Every Frame)",
	["opt_optimization_internal_only"] = "This setting only affects the built-in waypoint arrow when the internal waypointer is active.",
	["opt_optimization_routing_header"] = "Travel Routing",
	["opt_optimization_routing_desc"] = "Control how aggressively the built-in travel system calculates and prepares routes.",
	["opt_pathfinding_speed"] = "Route Calculation Budget",
	["opt_pathfinding_speed_desc"] = "Controls how much work LibRover does per update while building routes. Lower values reduce CPU spikes; higher values finish recalculations sooner.",
	["opt_pathfinding_speed_slow"] = "Slow (Lowest CPU)",
	["opt_pathfinding_speed_medium"] = "Medium",
	["opt_pathfinding_speed_fast"] = "Fast (Quickest Updates)",
	["opt_travel_full_linking_startup"] = "Build Full Travel Links At Startup",
	["opt_travel_full_linking_startup_desc"] = "Precompute more travel links when logging in. This can improve later route responsiveness at the cost of longer startup work.",
	["opt_optimization_memory_header"] = "Memory & Loading",
	["opt_optimization_memory_desc"] = "Future optimization target: lighter initial memory usage through more selective guide/step loading. Not implemented in this pass.",
	["opt_optimization_diagnostics_header"] = "Diagnostics",
	["opt_optimization_diagnostics_desc"] = "Future optimization target: lightweight FPS or memory diagnostics for profiling stutter and load spikes. Not implemented in this pass.",
} end)

