if GetLocale()~="ruRU" then return end

-- These are the main viewer's lines.

local COLOR_TIP_MOUSE = "|cffeedd99"
local COLOR_TIP_HINT = "|cff99ff00"
local COLOR_TIP = "|cff00ff00"

local COLOR_GOAL_LOC = "|cffffee77"
local COLOR_GOAL_COUNT = "|cffffffcc"
local COLOR_GOAL_ITEM = "|cffaaeeff"
local COLOR_GOAL_QUEST = "|cffbb99ff"
local COLOR_GOAL_NPC = "|cffaaffaa"
local COLOR_GOAL_MONSTER = "|cffffaaaa"
local COLOR_GOAL_GOAL = "|cffffcccc"



ZygorGuidesViewer_L("Main", "ruRU", function() return {
	["name"] = "|cffffff88Z|cffffee66y|cffffdd44g|cffffcc22o|cffffbb00r |cffffaa00Guides Viewer|r",
	["name_plain"] = "Zygor Guides Viewer",
	["desc"] = "Основные настройки Zygor Guides Viewer %s.|n",

	['welcome_guides'] = "Загружено %d гайдов.",

	["opt_guide"] = "Выберите гайд:",
	["opt_guide_steps"] = "Шагов: %d",
	["opt_guide_author"] = "Автор: %s",
	["opt_guide_next"] = "Следующий гайд: %s",

	["opt_report"] = "Сообщить об ошибке в шаге",
	["opt_report_desc"] = "Создать отчет об ошибке с данными текущего шага. Скопируйте и отправьте авторам гайда.",

	["opt_visible"] = "Показывать окно Zygor Guides Viewer",
	["opt_visible_desc"] = "",
	["opt_hideincombat"] = "Скрывать гайды в бою",
	["opt_hideincombat_desc"] = "Скрывать все окна гайда во время боя, если на экране мало места.",
	
	--["opt_group_main"] = "Main window settings",
	["opt_opacitymain"] = "Прозрачность",
	["opt_opacitymain_desc"] = "Прозрачность основного окна.",
	["opt_framescale"] = "Масштаб",
	["opt_framescale_desc"] = "Изменение размера окна под ваши предпочтения.",
	["opt_fontsize"] = "Масштаб текста",
	["opt_fontsize_desc"] = "Предпочитаемый размер текста. На него также влияет масштаб окна.",
	["opt_fontsecsize"] = "Масштаб вторичного текста",
	["opt_fontsecsize_desc"] = "Размер дополнительного текста для описаний и заметок.",
	["opt_backcolor"] = "Цвет фона",
	["opt_backcolor_desc"] = "Цвет фона окна.",

	["opt_group_window"] = "Параметры окна",
	--["opt_minimapnotedesc"] = "Show waypoint caption",
	--["opt_minimapnotedesc_desc"] = "Show the relevant waypoint's caption not only on the waypoint's tooltip, but on the mini window as well.",
	--["opt_showgoals"] = "Show step goals",
	--["opt_showgoals_desc"] = "Show step completion goals in the mini window",
	--["opt_autosizemini"] = "Auto-size",
	--["opt_autosizemini_desc"] = "Automatically adjust the height of the mini window.",
	["opt_miniresizeup"] = "Расширять вверх",
	["opt_miniresizeup_desc"] = "Переворачивает направление расширения окна вверх, а не вниз. Удобно, если окно находится внизу экрана.",
	["opt_opacitymini"] = "Прозрачность фона",
	["opt_opacitymini_desc"] = "Прозрачность фона окна шагов.",

	--["opt_showallsteps"] = "Collapsed mode",
	--["opt_showallsteps_desc"] = "Display only the current step and some next steps, instead of the whole guide",

	["opt_showcountsteps"] = "Показывать шаги:",
	["opt_showcountsteps_desc"] = "Количество отображаемых шагов.\n|cffffffaaВсе|r показывает все шаги в прокручиваемом списке.\n|cffffffaa1-5|r показывает текущий шаг сверху и автоматически меняет размер окна для нескольких следующих шагов.",
	["opt_showcountsteps_all"] = "Все",

	["opt_group_map"] = "Маршрутные точки",
	["opt_group_map_desc"] = "Эти настройки определяют, как Zygor Guides Viewer работает с картографическими аддонами.",
	["opt_group_map_waypointing"] = "Аддон маршрутных точек",
	["opt_group_map_waypointing_desc"] = "Выберите аддон, который будет обрабатывать маршрутные точки для Zygor Guides Viewer.",
	['opt_group_map_hidearrowwithguide'] = "Скрывать стрелку при скрытии окна",
	['opt_group_map_hidearrowwithguide_desc'] = "Если включено, стрелка будет скрываться вместе с окном гайда.\nЕсли нужно, чтобы стрелка оставалась видимой, отключите эту опцию.",
	["opt_group_addons_internal"] = "Встроенные маршрутные точки",
	["opt_group_addons_builtin"] = "Встроенные маршрутные точки",
	["opt_group_addons_tomtom"] = "TomTom",
	["opt_group_addons_carbonite"] = "Carbonite",
	["opt_group_addons_cart2"] = "Cartographer 2",
	["opt_group_addons_cart3"] = "Cartographer 3",
	["opt_group_addons_metamap"] = "MetaMap",
	["opt_group_addons_none"] = "нет",
	["opt_debug"] = "Отладка",
	["opt_debug_desc"] = "Показывать отладочную информацию.",
	["opt_debugging"] = "Отладка",
	["opt_debugging_desc"] = "Параметры отладки.",
	--["opt_browse"] = "Toggle windows",
	 --["opt_browse_desc"] = "Toggle the visibility of either of Zygor's Guides windows.",

	["opt_autoskip"] = "Автоматический переход",
	["opt_autoskip_desc"] = "Автоматически переходить к следующему шагу при выполнении всех условий. Некоторые шаги с очень сложными условиями все еще могут требовать ручного пропуска.",

	["opt_goalicons"] = "Показывать иконки шагов",
	["opt_goalicons_desc"] = "Показывать иконки, отражающие статус выполнения.",
	["opt_goalcolorize"] = "Окрашивать выполненные строки",
	["opt_goalcolorize_desc"] = "Полностью окрашивать выполненные строки шага в зеленый.",
	["opt_goalbackprogress"] = "Окраска по проценту выполнения",
	["opt_goalbackprogress_desc"] = "Показывать частичное выполнение промежуточными цветами между невыполненным и выполненным.|nЕсли выключено, цели отображаются только цветами 'невыполнено' или 'выполнено'.",

	["opt_group_step"] = "Цели шага",

	["opt_goalbackcolor_desc"] = "Цвета выполнения:",
	["opt_progressbackcolor_desc"] = "Цвета шагов:",
	["opt_goalbackaux"] = "Путешествие",
	["opt_goalbackaux_desc"] = "Этот цвет используется для шагов перемещения.",
	["opt_goalbackobsolete"] = "Устаревшее",
	["opt_goalbackobsolete_desc"] = "Этот цвет используется для устаревших целей или шагов.",
	["opt_goalbackprogressing"] = "В процессе",
	["opt_goalbackprogressing_desc"] = "Этот цвет обозначает цели примерно на 50% выполнения.",
	["opt_goalbackgrounds"] = "Окрашивать фон",
	["opt_goalbackgrounds_desc"] = "Окрашивать фон строк шага для отображения статуса выполнения.",
	["opt_goalbackcomplete"] = "Выполнено",
	["opt_goalbackcomplete_desc"] = "Цвет выполненных целей.",
	["opt_goalbackincomplete"] = "Не выполнено",
	["opt_goalbackincomplete_desc"] = "Цвет невыполненных целей.",
	["opt_goalbackimpossible"] = "Невозможно",
	["opt_goalbackimpossible_desc"] = "Цвет целей, которые сейчас невозможно выполнить.",

	['opt_tooltipsbelow'] = "Показывать доп. информацию в строке",
	['opt_tooltipsbelow_desc'] = "Дополнительную информацию о некоторых строках шага можно показывать в строке или во всплывающей подсказке при наведении.",

	["opt_flash_desc"] = "Оповещение о прогрессе:",
	["opt_goalcompletionflash"] = "Подсветка цели при выполнении",
	["opt_goalcompletionflash_desc"] = "Визуальная вспышка при выполнении отдельной цели.",
	["opt_goalupdateflash"] = "Подсветка цели при прогрессе",
	["opt_goalupdateflash_desc"] = "Визуальная вспышка при прогрессе отдельной цели.",
	["opt_flashborder"] = "Подсветка окна при завершении шага",
	["opt_flashborder_desc"] = "Подсвечивать все окно при завершении шага.",

	--["opt_colorborder"] = "Color step window border",
	--["opt_colorborder_desc"] = "Use the step window border's color to indicate completion of the whole step.",

	["opt_group_display"] = "Отображение",
	["opt_group_display_desc"] = "Настройка отображения гайдов.",

	["opt_group_data"] = "Встроенные гайды",
	["opt_group_data_desc"] = "Zygor Guides Viewer может хранить коммерческие гайды во внутреннем хранилище, которые нельзя распространять как отдельные аддоны.",
	["opt_group_data_guide"] = "Гайды во внутреннем хранилище:",
	["opt_group_data_guide_desc"] = "Выберите гайд из списка для редактирования или удаления. Здесь НЕ показываются гайды, загруженные отдельными аддонами.",
	["opt_group_data_del"] = "Удалить гайд",
	["opt_group_data_del_desc"] = "Удалить выбранный гайд из внутреннего хранилища.",
	["opt_group_data_edit"] = "Редактировать гайд",
	["opt_group_data_edit_desc"] = "Загрузить выбранный гайд в окно редактора ниже.",
	["opt_group_data_entry"] = "Данные гайда:",
	["opt_group_data_entry_desc"] = "Вставьте новый гайд сюда (оберните шаги в:|nguide Title Of Guide|nsteps...|nsteps...|nend\n); вставка и разбор большого гайда (>30kB) могут занять несколько секунд.",

	['opt_windowlocked'] = "Закрепить окно",
	['opt_windowlocked_desc'] = "Закрепить окно, отключив взаимодействие мышью.\nАктивными останутся только кнопки.",
	['opt_hideborder'] = "Автоскрытие рамки",
	['opt_hideborder_desc'] = "Автоматически скрывать рамку и кнопки окна, когда курсор уходит.\nНаведите курсор на заголовок окна, чтобы снова показать их.",

	['opt_skin'] = "Цвет оформления окна",
	['opt_skin_desc'] = "Выберите цвет оформления окна под ваш интерфейс.",
	['opt_skin_violet'] = "|cffee55ffФиолетовый",
	['opt_skin_green'] = "|cff88ff88Зеленый",
	['opt_skin_blue'] = "|cff99aaffСиний",
	['opt_skin_orange'] = "|cffffbb00Оранжевый",
	["opt_skinpanel_title"] = "Оформление",
	["opt_skinpanel_desc"] = "Выберите визуальную тему для окна гайда.",
	["opt_skinpanel_intro"] = "Сначала выберите общий стиль окна, затем тонко настройте размер, прозрачность и текст. Remaster остаётся рекомендуемой темой по умолчанию, а Retail предлагает внешний вид, более близкий к интерфейсу Blizzard.",
	["opt_skinpanel_skin"] = "Тема",
	["opt_skinpanel_skin_desc"] = "Выберите тему и её цветовой вариант.",
	["opt_skinpanel_appearance_header"] = "Внешний вид",
	["opt_skinpanel_appearance_desc"] = "Настройте масштаб окна, размер текста и прозрачность рамки.",
	["opt_skinpanel_colors_header"] = "Цвета",
	["opt_skinpanel_colors_desc"] = "Настройте интенсивность фона рамки для выбранного варианта темы.",
	["opt_skinpanel_advanced_header"] = "Дополнительно",
	["opt_skinpanel_advanced_desc"] = "Менее часто используемые параметры отображения, влияющие на компоновку окна и показ шагов.",

	['opt_backopacity'] = "Прозрачность фона",
	['opt_backopacity_desc'] = "Прозрачность фона окна.",



	--["mainframe_guide"] = "Select a guide:",
	--["mainframe_notloaded"] = "No leveling guides are loaded.|n|nPlease go to http://zygorguides.com to purchase Zygor's 1-80 Leveling Guides, or load some third-party guides.|n|nIf you're sure you have installed some guides, ask their authors for installation troubleshooting.",
	--["mainframe_notselected"] = "%d guides are loaded.|nPlease select a guide from the list above.",


	["report_title"] = "Нажмите Ctrl+C, чтобы скопировать отчет.|nЗатем отправьте его автору |cffffffff%s|r|nна адрес |cffffffff%s|r.",
	["report_notitle"] = "|cffff8888(неизвестный гайд)|r",
	["report_noauthor"] = "|cffff8888(адрес недоступен)|r",


	["opt_mapbutton"] = "Показывать кнопку у мини-карты",
	["opt_mapbutton_desc"] = "Показывать кнопку Zygor Guides Viewer у мини-карты",

	["minimap_tooltip"] = COLOR_TIP_MOUSE.."ЛКМ|r: показать/скрыть окно гайда|n"..COLOR_TIP_MOUSE.."ПКМ|r: настройки|n",


	["waypointaddon_set"] = "Выбран аддон маршрутных точек: %s",
	["waypointaddon_detecting"] = "Попытка автоматически определить аддон маршрутных точек...",
	["waypointaddon_connecting"] = "Подключение к аддону маршрутных точек: %s",
	["waypointaddon_connected"] = "Успешное подключение к %s.",
	["waypointaddon_fail"] = "Не удалось подключиться к %s.",
	["waypointaddon_disconnected"] = "Отключено от |cffddeeff%s|r.",
	['waypoint_step'] = "Шаг %s",

	["checkmap"] = "Проверьте карту.",

	["initialized"] = 'Инициализация завершена.',

	["miniframe_notloaded"] = "Гайды для прокачки не загружены.|n|nПерейдите на http://zygorguides.com, чтобы приобрести гайды Zygor 1-80, или загрузите сторонние гайды.|n|nЕсли вы уверены, что установили гайды, обратитесь к их авторам за помощью по установке.",
	["miniframe_notselected"] = "Сейчас гайд не выбран.\nНажмите мигающую кнопку выше, чтобы выбрать гайд.",
	["miniframe_loading"] = "Загрузка гайдов: %d%%",

	['frame_locked'] = "Окно закреплено",
	['frame_unlock'] = COLOR_TIP_MOUSE.."ЛКМ|r: открепить",
	['frame_unlocked'] = "Окно не закреплено",
	['frame_lock'] = COLOR_TIP_MOUSE.."ЛКМ|r: закрепить",
	['frame_settings'] = "Настройки",
	['frame_settings1'] = COLOR_TIP_MOUSE.."ЛКМ|r: базовые настройки",
	['frame_settings2'] = COLOR_TIP_MOUSE.."ПКМ|r: полная конфигурация",
	['frame_minimized'] = "Показывается шагов: |cffffffff%d|r",
	['frame_maximized'] = "Показываются все шаги",
	['frame_minimize'] = COLOR_TIP_MOUSE.."ЛКМ|r: показывать только |cffffffff%d|r",
	['frame_minright'] = COLOR_TIP_MOUSE.."ПКМ|r: выбрать количество шагов",
	['frame_maximize'] = COLOR_TIP_MOUSE.."ЛКМ|r: показать все",
	['frame_stepnav_prev'] = "Предыдущий шаг",
	['frame_stepnav_prev_click'] = COLOR_TIP_MOUSE.."ЛКМ|r: назад",
	['frame_stepnav_prev_right'] = COLOR_TIP_MOUSE.."ПКМ|r: перемотка назад",
	['frame_stepnav_next'] = "Следующий шаг",
	['frame_stepnav_next_click'] = COLOR_TIP_MOUSE.."ЛКМ|r: пропустить",
	['frame_stepnav_next_right'] = COLOR_TIP_MOUSE.."ПКМ|r: перемотка вперед",
	['frame_section'] = "Текущий гайд",
	['frame_section_click'] = COLOR_TIP_MOUSE.."ЛКМ|r: выбрать",


	['tooltip_tip'] = COLOR_TIP_HINT.."%s|r",
	['tooltip_waypoint'] = COLOR_TIP_MOUSE.."ЛКМ|r"..COLOR_TIP.." установить точку: |cffffaa00%s|r",
	['tooltip_waypoint_coords'] = "Местоположение: |cffffaa00%s|r",

	["message_errorloading_full"] = "|cffff4444Ошибка|r загрузки гайда |cffaaffaa%s|r\nстрока %d: %s\nошибка: %s",
	["message_errorloading_brief"] = "|cffff4444Ошибка|r загрузки гайда |cffaaffaa%s|r",
	["message_loadedguide"] = "Активирован гайд: |cffaaffaa%s|r",
	["message_missingguide"] = "|cffff4444Отсутствует|r гайд: |cffaaffaa%s|r",
	["title_noguide"] = "Zygor Guides Viewer (гайд не выбран)",


	['step_num'] = "|cffaaaaaa%s|cff888888.|r ",
	['step_level'] = "|cffaaccaaУровень: |cffcceecc%s|cffaaccaa|r ",

	["questtitle"] = "`%s'",
	["questtitle_part"] = "`%s' (часть %s)",
	["coords"] = "%d,%d",
	["map_coords"] = "%s %d,%d",

	["stepgoal_home"] = "Сделайте %s местом возвращения",
	["stepgoal_flightpath"] = "Откройте маршрут полета: %s",

	["stepgoal_accept"] = "Примите %s",
	["stepgoal_turn in"] = "Отдайте %s",
	["stepgoal_talk to"] = "Поговорите с %s",
	["stepgoal_kill"] = "Убийте %s",
	["stepgoal_kill #"] = "Убийте %s %s",
	["stepgoal_goal"] = "%s",
	["stepgoal_goal #"] = "%s %s",
	["stepgoal_get"] = "Получите %s",
	["stepgoal_get #"] = "Получите %s %s",
	["stepgoal_ding"] = "Сейчас у вас должен быть %s уровень.|n     Если нет, добейте немного мобов до нужного уровня.",
	["stepgoal_go to"] = "Идите к %s",
	["stepgoal_also at"] = "Тоже на %s",
	["stepgoal_hearth to"] = "Используйте камень возвращения в %s",
	["stepgoal_collect"] = "Соберите %s",
	["stepgoal_collect #"] = "Соберите %s %s",
	["stepgoal_buy"] = "Купите %s %s",
	["stepgoal_fpath"] = "Откройте маршрут полета: %s",
	["stepgoal_use"] = "Используйте %s",
	["stepgoal_home"] = "Сделайте %s местом возвращения",
	["stepgoal_petaction"] = "Используйте способность питомца %s",
	["stepgoal_havebuff"] = "Получите эффект/дебафф '%s'",
	["stepgoal_nobuff"] = "Снимите эффект/дебафф '%s'",
	["stepgoal_rep"] = "Получите %s у %s",
	["stepgoal_achieve"] = "Получите достижение '%s'",
	["stepgoal_achievesub"] = "Выполните '%s' для достижения '%s'",
	["stepgoal_skill"] = "Изучите %s до уровня %s",
	["stepgoal_skillmax"] = "Повысьте %s до максимального уровня %s",
	["stepgoal_learn"] = "Научитесь создавать %s",
	["stepgoal_invehicle"] = "Сядьте в транспорт",
	["stepgoal_outvehicle"] = "Покиньте транспорт",
	["stepgoal_equipped"] = "Экипируйте %s",
	["stepgoal_or"] = "  - или -",
	["stepgoal_at_suff"] = " (%s)",

	["completion_collect"] = "(%s/%s)",
	["completion_goal"] = "(%s/%s)",
	["completion_ding"] = "(%s%%)",
	["completion_done"] = "(выполнено)",
	["completion_rep"] = "(%s)",
	--["completion_(done)"] = "(done)",

	['quest_part'] = " (часть %s)",

--[[
	["stepgoalshort_complete"] = "готово",
	["stepgoalshort_incomplete"] = "в процессе",
	["stepgoalshort_questgoal"] = "(%d/%d)",
	["stepgoalshort_level"] = "(%d%%)",
--]]

	["step_req"] = "Шаг подходит только для: %s",


	["map_highlight"] = "Подсветить",

	["stepreq"] = "Требование класса/расы для шага: ",
	["stepreqor"] = " или ",
	["req_not"] = "не %s",

	["opt_do_searchforgoal"] = "Найти выполнимую цель",
	["searching_for_goal_success"] = "Для вас найдена выполнимая цель: %s. Это может быть хорошей точкой входа в гайд.",
	["searching_for_goal_failed"] = "Выполнимая цель не найдена. Попробуйте другой гайд или раздел, возьмите квесты или запустите поиск заново с начала раздела (поиск идет только вперед).",
	["going"] = "%d%% до %s",

	["binding_togglewindow"] = "Показать окно гайда",
	["binding_prev"] = "Предыдущий шаг",
	["binding_next"] = "Следующий шаг",
	["menu_last"] = "Последние гайды:",
	["menu_last_entry"] = "%s |cffaaaaaaшаг|r %d",
	["gb_window_title"] = "Браузер гайдов",
	["gb_addon_title"] = "Zygor Guides Viewer Remastered",
	["gb_root"] = "Корень",
	["gb_search"] = "Поиск",
	["gb_folders"] = "Папки",
	["gb_guides"] = "Гайды",
	["gb_load_guide"] = "Загрузить гайд",
	["gb_open_legacy"] = "Открыть старый выбор",
	["gb_path_format"] = "Путь: %s",
	["gb_select_guide"] = "Выберите гайд",
	["gb_select_guide_from_list"] = "Выберите гайд из списка.",
	["gb_select_settings_page"] = "Выберите страницу настроек",
	["gb_all_guides"] = "Все гайды",
	["gb_other"] = "Другое",
	["gb_unknown"] = "неизвестно",
	["gb_none"] = "нет",
	["gb_folder_format"] = "Папка: %s",
	["gb_progress_format"] = "Прогресс: %d%%",
	["gb_guides_count_format"] = "%d гайдов",
	["gb_current_meta_format"] = "Шаг %d / %d  |  %s",
	["gb_detail_meta_format"] = "Шагов: %d\nАвтор: %s\nДалее: %s",
	["gb_tab_home"] = "Главная",
	["gb_tab_featured"] = "Рекомендуемые",
	["gb_tab_current"] = "Текущий",
	["gb_tab_recent"] = "Недавние",
	["gb_tab_options"] = "Настройки",
	["gb_cat_leveling"] = "Прокачка",
	["gb_cat_dungeons"] = "Подземелья",
	["gb_cat_daily"] = "Ежедневные",
	["gb_cat_events"] = "События",
	["gb_cat_reputations"] = "Репутации",
	["gb_cat_gold"] = "Золото",
	["gb_cat_professions"] = "Профессии",
	["gb_cat_petsmounts"] = "Питомцы и маунты",
	["gb_cat_titles"] = "Титулы",
	["gb_cat_achievements"] = "Достижения",
	["gb_cat_misc"] = "Разное",
	["gb_cat_favorites"] = "Избранное",
	["gb_opt_guides"] = "Гайды",
	["gb_opt_desc_guides"] = "Выбор гайда, сведения о текущем гайде и основные элементы управления.",
	["gb_opt_stepdisplay"] = "Отображение шагов",
	["gb_opt_desc_stepdisplay"] = "Внешний вид окна, оформление, шрифты и отображение шагов и целей.",
	["gb_opt_progress"] = "Прогресс",
	["gb_opt_desc_progress"] = "Поведение продвижения по шагам, правила пропуска и логика завершения.",
	["gb_opt_travel"] = "Система перемещения",
	["gb_opt_desc_travel"] = "Выбор провайдера точек и поведение системы перемещения.",
	["gb_opt_map"] = "Карты и точки",
	["gb_opt_desc_map"] = "Стиль стрелки, метки на миникарте и карте мира, а также внешний вид точек.",
	["gb_opt_notifications"] = "Уведомления",
	["gb_opt_desc_notifications"] = "Вспышки прогресса и другие сигналы внимания.",
	["gb_opt_actionbuttons"] = "Кнопки действий",
	["gb_opt_desc_actionbuttons"] = "Поведение кнопок взаимодействия со шагами и целями.",
	["gb_opt_convenience"] = "Квесты",
	["gb_opt_desc_convenience"] = "Авто-принятие, авто-сдача и другие полезные квестовые функции.",
	["gb_opt_accessibility"] = "Доступность",
	["gb_opt_desc_accessibility"] = "Параметры читаемости и цветовой видимости.",
	["gb_opt_profile"] = "Профили",
	["gb_opt_desc_profile"] = "Управление профилями, копирование и сброс.",
	["gb_opt_about"] = "О дополнении",
	["gb_opt_desc_about"] = "Версия, поддержка и инструменты диагностики.",
	["gb_opt_advanced"] = "Расширенные",
	["gb_opt_desc_advanced"] = "Отладочные инструменты, диагностика и настройки для разработчиков.",
	["gb_opt_general"] = "Общие",
	["gb_opt_desc_general"] = "Общие настройки.",
	["gb_title_viewer"] = "Просмотрщик",
	["gb_options_viewer_desc"] = "Основное поведение окна гайда, загрузка гайдов и базовые параметры дополнения.",
	["gb_hint_search_settings"] = "Совет:\nИспользуйте поиск слева, чтобы быстро найти страницу настроек.",
	["gb_hint_options_filter"] = "Совет:\nПоиск слева фильтрует страницы настроек.\nИспользуйте \"Открыть полные настройки\", чтобы открыть полный интерфейс Blizzard.",
	["gb_empty_no_guides_search"] = "По этому запросу гайды не найдены.",
	["gb_empty_no_guides_category"] = "В этой категории нет гайдов.",
	["gb_empty_no_current_guide"] = "Текущий гайд не загружен.",
	["gb_empty_no_current_guide_short"] = "Текущий гайд не загружен",
	["gb_empty_no_recent_guides"] = "Пока нет недавних гайдов.",
	["gb_empty_no_featured_match"] = "Нет рекомендуемых гайдов, подходящих под этот фильтр.",
	["gb_empty_no_featured_suggestions"] = "Нет рекомендаций",
	["gb_empty_no_favorites"] = "Пока нет избранных гайдов.",
	["gb_no_guide_selected"] = "Гайд не выбран",
	["gb_action_clear_search"] = "Очистить поиск",
	["gb_action_show_all_categories"] = "Показать все категории",
	["gb_action_go_home"] = "Перейти на главную",
	["gb_action_open_home"] = "Открыть главную",
	["gb_action_reset_snoozed"] = "Сбросить скрытые рекомендации",
	["gb_action_clear_search_restore"] = "Очистить поиск и вернуть рекомендации",
	["gb_action_reset_snoozed_restore"] = "Сбросить скрытые рекомендации и вернуть подсказки",
	["gb_action_try_home"] = "Откройте главную, чтобы просмотреть все категории",
	["gb_action_browse_all_from_home"] = "Просмотреть все гайды с главной",
	["gb_action_back_to_guides"] = "Назад к гайдам",
	["gb_action_open_full_options"] = "Открыть полные настройки",
	["gb_action_go_current_folder"] = "Перейти к папке текущего гайда",
	["gb_action_resume"] = "Продолжить",
	["gb_action_restart"] = "Начать заново",
	["gb_nav_navigation"] = "Навигация",
	["gb_nav_back"] = "Назад",
	["gb_nav_reset_to_root"] = "Сбросить к корню категории",
	["gb_featured_bucket_next"] = "Следом",
	["gb_featured_bucket_progress"] = "В процессе",
	["gb_featured_bucket_level"] = "Под ваш уровень",
	["gb_featured_bucket_featured"] = "Рекомендуемые маршруты",
	["gb_featured_confidence_strong"] = "Высокая",
	["gb_featured_confidence_good"] = "Хорошая",
	["gb_featured_confidence_fallback"] = "Резерв",
	["gb_roadmap"] = "Маршрут",
	["gb_roadmap_bucket_format"] = "%s: маршрут",
	["gb_bucket_preview_next_with_title"] = "Продолжить цепочку: %s",
	["gb_bucket_preview_next"] = "Продолжить цепочку",
	["gb_bucket_preview_progress_with_title"] = "Продолжить: %s",
	["gb_bucket_preview_progress"] = "Продолжить незавершенные гайды",
	["gb_bucket_preview_level_with_title"] = "Начать по уровню: %s",
	["gb_bucket_preview_level"] = "Начать подходящие по уровню гайды",
	["gb_bucket_preview_featured_with_title"] = "Дополнительный маршрут: %s",
	["gb_bucket_preview_featured"] = "Дополнительные маршруты и полезное",
	["gb_meta_action"] = "Действие",
	["gb_meta_suggestion"] = "Рекомендация",
	["gb_meta_suggested"] = "Рекомендуется",
	["gb_meta_current"] = "Текущий",
	["gb_meta_recommended"] = "рекомендуется",
	["gb_meta_other_useful_option"] = "другой полезный вариант",
	["gb_meta_current_selection"] = "текущий выбор",
	["gb_meta_suggestions_snoozed"] = "рекомендации могли быть скрыты",
	["gb_meta_restore_recommendations"] = "вернуть рекомендации",
	["gb_meta_filter_no_matches"] = "фильтр не дал совпадений",
	["gb_meta_see_full_recommendations"] = "показать все рекомендации",
	["gb_meta_no_bucket_suggestions"] = "в этом разделе нет рекомендаций",
	["gb_meta_full_category_access"] = "полный доступ к категории",
	["gb_meta_suggested_from"] = "Источник рекомендации: %s",
	["gb_meta_confidence"] = "Уверенность: %s",
	["gb_meta_why_prefix"] = "Почему: ",
	["gb_meta_gain_prefix"] = "Польза: ",
	["gb_reason_recently_used"] = "недавно использовался",
	["gb_reason_incomplete"] = "не завершен",
	["gb_reason_your_level_range"] = "под ваш уровень",
	["gb_reason_near_your_level"] = "рядом с вашим уровнем",
	["gb_reason_your_class"] = "под ваш класс",
	["gb_reason_your_race"] = "под вашу расу",
	["gb_reason_your_profession"] = "под вашу профессию",
	["gb_reason_favorite"] = "избранное",
	["gb_reason_current_chain"] = "текущая цепочка",
	["gb_reason_chain_step_format"] = "шаг цепочки +%d",
	["gb_reason_inferred_continuation"] = "предполагаемое продолжение",
	["gb_reason_chapter_continuation"] = "продолжение раздела",
	["gb_tooltip_featured_controls"] = "Управление рекомендуемыми гайдами",
	["gb_tooltip_featured_click"] = "Нажмите X: скрыть на 24 часа",
	["gb_tooltip_featured_shift_click"] = "Shift+клик по X: скрыть на текущую сессию",
	["gb_tooltip_featured_restore"] = "Нажмите R или используйте сброс в настройках, чтобы вернуть.",
	["gb_tooltip_snooze"] = "Скрыть рекомендацию",
	["gb_tooltip_snooze_click"] = "Клик: скрыть на 24 часа",
	["gb_tooltip_snooze_shift_click"] = "Shift-клик: скрыть до конца сессии",
	["gb_tooltip_why_prefix"] = "Почему: ",
	["gb_tooltip_gain_prefix"] = "Польза: ",
	["gb_tooltip_confidence_prefix"] = "Уверенность: ",
	["gb_tooltip_chain_prefix"] = "Цепочка: ",
	["gb_tooltip_fallback_recommendation"] = "Резервная рекомендация",
	["gb_current_guide"] = "Текущий гайд",
	["gb_options_fallback_embed_unavailable"] = "Встроенные настройки недоступны. Нажмите «Настройки» еще раз, чтобы открыть стандартные настройки Blizzard.",
	["gb_options_fallback_missing_widgets"] = "Встроенные настройки недоступны. Отсутствуют виджеты встраивания AceGUI.",
	["gb_options_fallback_render_error"] = "Не удалось отрисовать встроенные настройки: %s",
	["opt_legacyguideddropdown"] = "Старый список гайдов",
	["opt_featured_header"] = "Рекомендуемые предложения",
	["opt_featured_enablefallback"] = "Включить запасные рекомендации",
	["opt_featured_enablefallback_desc"] = "Если в блоке рекомендаций нет прямых совпадений, показывать несколько полезных запасных гайдов.",
	["opt_featured_hiderecentcompleted"] = "Скрывать недавно завершенные гайды",
	["opt_featured_hiderecentcompleted_desc"] = "Не показывать совсем недавно завершенные гайды в умных рекомендациях.",
	["opt_featured_showconfidence"] = "Показывать метки уверенности",
	["opt_featured_showconfidence_desc"] = "Показывать в рекомендациях метки Strong/Good/Fallback.",
	["opt_featured_resethidden"] = "Сбросить скрытые рекомендации",
	["opt_featured_resethidden_desc"] = "Вернуть рекомендации, скрытые кнопкой закрытия.",
	["opt_disablerouteloopstacking"] = "Отключить объединение маршрутов и циклов",
	["opt_disablerouteloopstacking_desc"] = "Не складывать маршруты и циклические секции в один и тот же блок рекомендаций.",
	["opt_routeantminimapmode"] = "Маршрут на миникарте",
	["opt_routeantminimapmode_desc"] = "Выберите, какая часть анимированной трассы маршрута будет показываться на миникарте.",
	["opt_routeantminimapmode_local"] = "Текущий сегмент",
	["opt_routeantminimapmode_local_desc"] = "Показывать только локальный участок маршрута: предыдущая точка, текущая и следующая.",
	["opt_routeantminimapmode_all"] = "Весь маршрут",
	["opt_routeantminimapmode_all_desc"] = "Показывать на миникарте весь маршрут или петлю целиком.",
	["opt_routeantminimapmode_none"] = "Только путевая точка",
	["opt_routeantminimapmode_none_desc"] = "Скрывать анимированную трассу на миникарте и показывать только активную путевую точку.",
	["opt_routeantdensity"] = "Плотность трассы",
	["opt_routeantdensity_desc"] = "Настройте, насколько плотно располагаются анимированные метки между точками маршрута. 1 = редко, 5 = текущее значение по умолчанию, 9 = максимальная плотность.",
	["opt_accessibility_intro"] = "Настройте параметры видимости цветов и читаемости текста.",
	["opt_colorblindmode"] = "Режим дальтонизма",
	["opt_colorblindmode_desc"] = "Заменяет цвета гайда, стрелки и дистанции на палитры, удобные при дальтонизме. Также включает упрощенные цвета подписей стрелки с повышенным контрастом.",
	["opt_colorblindmode_off"] = "Выкл.",
	["opt_colorblindmode_protanopia"] = "Протанопия",
	["opt_colorblindmode_deuteranopia"] = "Дейтеранопия",
	["opt_colorblindmode_tritanopia"] = "Тританопия",
	["opt_colorblindmode_global"] = "Глобально",
	["opt_colorblindmode_custom"] = "Свои",
	["opt_arrowcolor_far"] = "Далеко",
	["opt_arrowcolor_mid"] = "Средне",
	["opt_arrowcolor_near"] = "Близко",
	["opt_simplifyarrownouncolors"] = "Упрощенные цвета подписей стрелки",
	["opt_simplifyarrownouncolors_desc"] = "Использовать более чистые и контрастные цвета для подписей стрелки.",
	["opt_about_heading"] = "Zygor Guides Viewer Remastered для WoTLK 3.3.5a",
	["opt_about_support"] = "Поддержка",
	["opt_about_diag"] = "Подсказка: команды `/zygor status` и `/zygor debug` помогают при поиске проблем.",
	["opt_showminimapicons"] = "Показывать значки на миникарте",
	["opt_showminimapicons_desc"] = "Показывать значки на миникарте",
	["opt_iconalpha"] = "Прозрачность значков",
	["opt_iconalpha_desc"] = "Прозрачность значков заметок на карте",
	["opt_iconsize"] = "Размер значков",
	["opt_iconsize_desc"] = "Размер значков на карте",
	["opt_arrowshow"] = "Показывать стрелку",
	["opt_arrowshow_desc"] = "Показывать или скрывать встроенную стрелку маршрутных точек.",
	["opt_arrowcolormode_direction"] = "Направление",
	["opt_arrowcolormode_distance"] = "Дистанция",
	["opt_arrowtextoutline"] = "Контур текста стрелки",
	["opt_arrowtextoutline_desc"] = "Выберите силу контура текста у стрелки маршрутных точек.",
	["opt_arrowtextoutline_default"] = "По умолчанию",
	["opt_arrowtextoutline_strong"] = "Сильный",
	["opt_arrowtextoutline_reduced"] = "Слабый",
	["opt_remasterpointeronlegacy"] = "Использовать обновленную стрелку на старых скинах",
	["opt_remasterpointeronlegacy_desc"] = "Если включено, старые скины будут использовать обновленный стиль стрелки.",
	["opt_resetarrowposition"] = "Сбросить положение стрелки",
	["opt_resetarrowposition_desc"] = "Сбросить положение стрелки к стандартному положению retail.",
	["opt_foglightdebug"] = "(Отладка) Проверить foglight",
	["opt_foglightdebug_desc"] = "Проверить foglight для текущей карты",
	["opt_travelsystem_intro"] = "Выберите, как будут обрабатываться провайдеры перемещения и маршрутных точек.",
	["opt_mapswaypoints_intro"] = "Настройте метки на карте и внешний вид встроенной стрелки.",
	["opt_notifications_intro"] = "Настройте визуальные сигналы уведомлений во время прохождения шагов.",
	["opt_actionbuttons_intro"] = "Настройте показ значков целей и интерактивное отображение шагов.",
	["frame_toolbar_guides"] = "Гайды",
	["frame_toolbar_guides_click"] = "открыть меню гайдов",
	["frame_toolbar_guides_right"] = "открыть менеджер гайдов",
	["frame_toolbar_close"] = "Закрыть",
	["frame_toolbar_close_click"] = "закрыть",
	["frame_toolbar_settings"] = "Настройки",
	["frame_toolbar_settings_click"] = "открыть быстрое меню",
	["frame_toolbar_settings_right"] = "открыть настройки менеджера гайдов",
	["frame_toolbar_stepview"] = "Вид шагов",
	["frame_toolbar_stepview_showall"] = "показать все",
	["frame_toolbar_stepview_showonly"] = "показывать только |cffffffff%s|r",
	["frame_toolbar_stepview_setcount"] = "задать количество шагов",
	["frame_toolbar_unlock"] = "Разблокировать окно",
	["frame_toolbar_unlock_click"] = "разблокировать",
	["frame_toolbar_lock"] = "Заблокировать окно",
	["frame_toolbar_lock_click"] = "заблокировать",
	["frame_title_default"] = "Zygor Guides",
	["frame_tab_guides"] = "Гайды",
	["frame_tab_spots"] = "Точки",


	["opt_stepnumber"] = "Показывать номера шагов",
	["opt_stepnumber_desc"] = "Показывать номера шагов и рекомендуемый уровень для каждого шага.\nОтключите, чтобы съэкономить место на экране.",
	["opt_hidestepborders"] = "Скрыть рамки",
	["opt_hidestepborders_desc"] = "Скрывает графические рамки вокруг шагов.",
	["opt_stepbackopacity"] = "Прозрачность фона",
	["opt_stepbackopacity_desc"] = "Прозрачность фона окна шагов.\nЦвет фона соответствует статусу выполнения и затемнения.",
	["opt_resetwindow"] = "Сбросить окно",
	["opt_resetwindow_desc"] = "Если окно вне экрана, эта кнопка вернет его в центр.",
	["opt_trackchains"] = "Учитывать цепочки квестов",
	["opt_trackchains_desc"] = "Помечать шаги принятия квестов как недоступные, если предыдущий квест не завершен.\n\nБаза цепочек включает \"свободные цепочки\" — задания, которые следуют друг за другом, но не требуют строгого порядка выполнения, поэтому иногда шаг принятия квеста может отображаться как недоступный, хотя квест все еще можно взять.",
	["opt_guidesinhistory"] = "Количество недавних гайдов",
	["opt_guidesinhistory_desc"] = "Показывать столько недавно использованных гайдов.",
	["opt_skin_remaster"] = "|cffc7d9ffRemaster (по умолчанию)",
	["opt_group_progress"] = "Динамический прогресс",
	["opt_group_progress_desc"] = "Для оптимизации прокачки аддон может динамически пропускать квесты, которые уже мало полезны на вашем уровне.",
	["opt_levelsahead"] = "Разрешить уровни вперед",
	["opt_levelsahead_desc"] = "Этот параметр определяет, насколько вы можете опережать гайд по уровеню.\nПри 0 обычно пропускаются квесты ниже вашего уровня (если нет продолжения).\nПри 1 и выше пропускаются только квесты, которые ниже вас более чем на указанное число уровней.",
	["opt_showobsolete"] = "Отмечать устаревшие шаги",
	["opt_showobsolete_desc"] = "Отмечать устаревшие шаги серым фоном.\nШаг считается устаревшим, если его уровень слишком низок для вас.",
	["opt_skipobsolete"] = "Пропускать устаревшие шаги",
	["opt_skipobsolete_desc"] = "Автоматически пропускать устаревшие шаги.",
	["opt_skipauxsteps"] = "Пропускать транспортные шаги",
	["opt_skipauxsteps_desc"] = "Автоматически пропускать транспортные шаги, если после них идут уже выполненные или устаревшие шаги.\nЭто предотвращает ситуации, когда вы далеко идете, а следующий шаг уже был выполнен.",
	["opt_skipflightsteps"] = "Считать маршруты полета известными",
	["opt_skipflightsteps_desc"] = "Предполагает, что вы сами открываете маршруты полёта, и автоматически помечает шаги получения маршрута как выполненные.\n\nПолезно при прыжке в середину гайда, менее полезно в обычной игре.",
	["opt_skipimpossible"] = "Пропускать невозможные шаги",
	["opt_skipimpossible_desc"] = "Автоматически пропускать невозможные шаги, чтобы не видеть цели из квестов, которые вы специально пропустили.",
	["opt_group_progress_bottomdesc"] = "Динамический прогресс работает так: квесты помечаются как \"устаревшие\", когда вы опережаете уровень гайда больше, чем на значение выше. Цепочки квестов помечаются как устаревшие только если устарела вся цепочка.\n\nДля новых игроков это помогает умно пропускать низкоуровневый контент, останавливаясь только на полезных цепочках.\n\nДля опытных игроков это не даёт гайду замедлять вас низкоуровневыми квестами, если вы качаетесь быстрее, чем ожидалось.",
	["opt_group_mapinternal"] = "Встроенные путевые точки",
	["opt_arrowmeters"] = "Метрическая система",
	["opt_arrowmeters_desc"] = "Использовать метры и километры вместо ярдов и миль.",
	["opt_arrowfreeze"] = "Стрелка игнорирует клики",
	["opt_arrowfreeze_desc"] = "Стрелка игнорирует действия мыши. Отключите, чтобы перетаскивать ее.",
	["opt_arrowcam"] = "Стрелка по камере",
	["opt_arrowcam_desc"] = "Показывать направление относительно камеры. Если выключено, стрелка ориентируется по направлению персонажа.\n\nПримечание: в режиме камеры стрелка может вести себя странно при перемещении по щелчку.",
	["opt_arrowcolordir"] = "Цвет по направлению",
	["opt_arrowcolordir_desc"] = "Делать гамму стрелки зеленой, когда она указывает в правильном направлении.\n\nОтключите, если хотите зеленый только при приблежении к цели.",
	["opt_arrowscale"] = "Масштаб стрелки",
	["opt_arrowscale_desc"] = "Размер стрелки.",
	["opt_arrowfontsize"] = "Размер текста стрелки",
	["opt_arrowfontsize_desc"] = "Размер текста в окне стрелки.",
	["opt_minimapzoom"] = "Авто-масштаб миникарты",
	["opt_minimapzoom_desc"] = "Автоматически увеличивает миникарту при установке точки и потом возращает предыдущий масштаб.",
	["opt_foglight"] = "Разведать карту",
	["opt_foglight_desc"] = "Показать неразведанные области на карте.",
	["opt_targetpreview_growth"] = "Направление роста",
	["opt_targetpreview_growth_desc"] = "Выберите, должен ли закреплённый предпросмотр цели повторять направление изменения размера просмотрщика, расти вверх или вниз.",
	["opt_targetpreview_growth_auto"] = "Как у просмотрщика",
	["opt_targetpreview_growth_up"] = "Расти вверх",
	["opt_targetpreview_growth_down"] = "Расти вниз",
	["opt_group_gold"] = "Гайды по золоту",
	["opt_group_gold_desc"] = "Эти настройки управляют отображением шагов фарма золота и точками ресурсов.",
	["opt_gold_detectiondist"] = "Дистанция обнаружения",
	["opt_gold_detectiondist_desc"] = "Дистанция, на которой учитываются ближайшие точки гайда по золоту.",
	["opt_gold_reqmode"] = "Режим требований",
	["opt_gold_reqmode_desc"] = "Выберите, какие типы точек учитывать.",
	["opt_gold_reqmode_all"] = "Все",
	["opt_gold_reqmode_current"] = "Только текущий гайд",
	["opt_gold_reqmode_future"] = "Текущий + будущие гайды",
	["gold_missing_noguidesloaded"] = "Гайды по золоту не загружены.",
	["gold_missing_nospotsinrange"] = "Подходящие точки в радиусе не найдены.",
	["gold_header_ore"] = "Места с рудой:",
	["gold_header_herb"] = "Травы:",
	["gold_header_skin"] = "Шкуры:",
	["gold_header_drop"] = "Падает с |cffffdddd%s|r:",
	["gold_header_vendor"] = "Покупка:",
	["opt_group_convenience"] = "Дополнительные функции",
	["opt_group_convenience_desc"] = "Разные полезные опции.",
	["opt_autoaccept"] = "Авто-принятие квестов",
	["opt_autoaccept_desc"] = "Автоматически принимать предложенные квесты.",
	["opt_autoturnin"] = "Авто-сдача квестов",
	["opt_autoturnin_desc"] = "Автоматически сдавать выполненные квесты.",
	["opt_fixblizzardautoaccept"] = "Исправить авто-принятие Blizzard",
	["opt_fixblizzardautoaccept_desc"] = "При включении опции Blizzard\"Квесты автоматически принимаются\" все равно отмечаеть шаги \"Принять\" и \"Принято\" как выполненные.",
	["opt_audiocues"] = "Звуковые сигналы",
	["opt_audiocues_desc"] = "Проигрывать звуки при прогрессе шагов.",
	["opt_analyzereps"] = "Анализ репутации",
	["opt_analyzereps_desc"] = "Анализирует текущие репутации и помечает неактивные репутационные шаги как устаревшие.",
	["opt_mapcoords"] = "Показывать координаты на карте",
	["opt_mapcoords_desc"] = "Показывать координаты игрока и курсора в окне карты.",
	["pointer_corpselabel1"] = "Бывший ты",
	["pointer_corpselabel2"] = "Не убежал...",
	["pointer_corpselabel3"] = "Взял слишком много на себя, да?",
	["pointer_corpselabel4"] = "Отбросил копыта",
	["pointer_corpselabel5"] = "Лучше не думать о цене ремонта.",
	["haman$"] = "hamans",
	["(%a)man$"] = "%1men",

} end)



local plurals = {
}

ZygorGuidesViewer_L("Specials", "ruRU", function() return {
	["plural"] = function (word)
		return word
	end,
	['contract_mobs'] = false,
} end)



-- Add lines for any translations needed for:

-- MISC STRINGS

ZygorGuidesViewer_L("G_string", "ruRU", function() return {
	["blabla"] = TRUE,
} end)

ZygorGuidesViewer_L("Main", "ruRU", function() return {
	["targetpreview_level"] = "Уровень",
	["targetpreview_class_boss"] = "Босс",
	["targetpreview_class_elite"] = "Элитный",
	["targetpreview_class_rareelite"] = "Редкий элитный",
	["targetpreview_class_rare"] = "Редкий",
	["frame_selectguide"] = "Выбор гайда",
	["frame_selectguide_left"] = "Выберите гайд слева.",
	["frame_toolbar_stepview_options"] = "Параметры отображения шагов",
	["targetpreview_title"] = "Предпросмотр цели",
	["targetpreview_title_locked"] = "Предпросмотр цели",
	["targetpreview_role_talk"] = "Поговорить",
	["targetpreview_role_kill"] = "Убить",
	["targetpreview_hint"] = "Нажмите, чтобы закрепить\nэту цель.",
	["targetpreview_hint_empty"] = "Для этого шага сейчас нет активной цели для разговора или убийства.",
	["targetpreview_empty_name"] = "Нет цели",
	["popup_accept"] = "Принять",
	["popup_decline"] = "Отказаться",
	["actionbutton_bar_title"] = "Перетащите, чтобы переместить кнопки действий",
	["actionbutton_bar_title_locked"] = "Кнопки действий",
	["actionbutton_tooltip_talk"] = "Выбрать цель %s и попытаться пометить её зелёным треугольником.",
	["actionbutton_tooltip_kill"] = "Выбрать цель %s и попытаться пометить её черепом.",
	["actionbutton_tooltip_script"] = "Выполняет макрос сценария текущего шага.",
	["actionbutton_tooltip_petaction"] = "Использовать рекомендуемое действие питомца.",
	["gearfinder_title"] = "Поиск экипировки",
	["gearfinder_no_upgrade"] = "Улучшения не найдены",
	["gearfinder_load_guide"] = "Загрузить гайд",
	["gearfinder_suggested_dungeon"] = "Рекомендуемое подземелье:",
	["gearfinder_refresh"] = "Нажмите для обновления",
	["gearfinder_status_searching"] = "Поиск улучшений%s",
	["gearfinder_status_searching_future"] = "Поиск будущих улучшений%s",
	["gearfinder_label_dungeon"] = "Подземелье:",
	["gearfinder_label_unknown"] = "Неизвестно",
	["gearfinder_label_inbags"] = "В сумках:",
	["gearfinder_label_score"] = "Очки: %d",
	["gearfinder_label_score_value"] = "%.1f очков",
	["gearfinder_label_equipped"] = "Надето",
	["gearfinder_label_empty"] = "Пустой слот",
	["gearfinder_upgrade_percent"] = "+%d%% улучшение",
	["gearfinder_upgrade_percent_short"] = "%+.1f%%",
	["gearfinder_label_new_item"] = "Новый предмет",
	["gearfinder_label_delta_score"] = "%+.1f очков",
	["gearfinder_label_best_gains"] = "Лучший прирост: %s",
	["gearfinder_label_found"] = "Лучшее найденное:",
	["gearfinder_label_future"] = "Будущее:",
	["gearfinder_items_found"] = "Найдено предметов: %d",
	["itemscore_ae_equip"] = "Надеть %s",
	["itemscore_ae_over"] = " вместо %s",
	["itemscore_ae_equip1"] = "Заменить этот предмет",
	["itemscore_ae_equip2"] = "Надеть этот предмет",
	["itemscore_ae_with"] = "на",
	["itemscore_ae_accept"] = "Надеть",
	["itemscore_ae_decline"] = "Не сейчас",
	["itemscore_ae_report_tip"] = "Удерживайте Shift и нажмите, чтобы открыть подробный отчёт по экипировке.\nОтклонённые предметы больше не будут предлагаться.",
	["itemscore_ae_build"] = "Билд",
	["itemscore_questitem1"] = "Для задания нужен этот предмет.",
	["itemscore_questitem2"] = "Надеть его для текущего этапа задания?",
	["itemscore_questitem3"] = "Снова надеть предыдущий предмет?",
	["notifcenter_gear_title"] = "Советник по экипировке",
	["notifcenter_gear_text"] = "Найдено улучшение",
	["notifcenter_gear_text_sl"] = "Найдено улучшений: %d",
	["notifcenter_gear_text_pl"] = "Найдено улучшений: %d",
	["notifcenter_gear_equipped"] = "%s надето в слот %s",
	["notifcenter_quest_text"] = "Предмет задания",
	["notifcenter_gen_popup_tooltip"] = "Нажмите, чтобы открыть",
	["opt_itemscore_ae_clearednotupgrade"] = "Список отклонённых улучшений очищен.",
	["opt_itemscore_warning"] = "Изменяйте веса характеристик для оценки предметов. Чем выше значение, тем важнее характеристика для вашей специализации.",
	["opt_gear_title"] = "Настройка автоматической оценки экипировки и поиска улучшений.",
	["opt_gear_score_class"] = "Класс:",
	["opt_gear_score_spec"] = "Специализация:",
	["opt_gear_sources"] = "Источники поиска экипировки",
	["opt_gear_sources_dungeons"] = "Подземелья",
	["opt_gear_sources_raids"] = "Рейды",
	["opt_quickscan_warning"] = "Режим быстрого сканирования: ссылки на предметы не были собраны.",
	["opt_actionbar_enable"] = "Включить панель действий",
	["opt_actionbar_enable_desc"] = "Показывает перемещаемую панель действий для интерактивных целей текущего шага.",
	["opt_inlinebuttons_enable"] = "Включить встроенные кнопки",
	["opt_inlinebuttons_enable_desc"] = "Показывает кнопки взаимодействия для разговора и убийства прямо в строках шага. Они скрываются, если значки строк отключены или панель действий выключена.",
	["opt_actionbar_onlywhenneeded"] = "Показывать только при необходимости",
	["opt_actionbar_onlywhenneeded_desc"] = "Скрывает панель действий, когда у текущего шага нет интерактивных кнопок.",
	["opt_actionbar_locked"] = "Заблокировать положение панели действий",
	["opt_actionbar_locked_desc"] = "Запрещает перетаскивание панели действий.",
	["opt_actionbar_scale"] = "Масштаб панели действий",
	["opt_actionbar_scale_desc"] = "Масштаб панели действий.",
	["opt_actionbar_size"] = "Размер кнопок",
	["opt_actionbar_size_desc"] = "Размер каждой кнопки на панели действий.",
	["opt_actionbar_spacing"] = "Расстояние между кнопками",
	["opt_actionbar_spacing_desc"] = "Расстояние между кнопками панели действий.",
	["opt_actionbar_pinside"] = "Сторона привязки",
	["opt_actionbar_pinside_desc"] = "Выберите, к какой стороне просмотрщика должна крепиться панель действий.",
	["opt_actionbar_pinside_top"] = "Сверху",
	["opt_actionbar_pinside_bottom"] = "Снизу",
	["opt_actionbar_pinside_left"] = "Слева",
	["opt_actionbar_pinside_right"] = "Справа",
	["opt_actionbar_resetanchor"] = "Сбросить положение панели действий",
	["opt_actionbar_resetanchor_desc"] = "Возвращает панель действий в её положение привязки по умолчанию.",
	["opt_actionbar_markers"] = "Включить метки целей",
	["opt_actionbar_markers_desc"] = "Пытается ставить рейдовые метки на цели для разговора и убийства, когда это возможно.",
	["opt_targetpreview_header"] = "Предпросмотр цели",
	["opt_targetpreview_intro"] = "Показывает перемещаемую панель предпросмотра для текущей цели разговора или убийства.",
	["opt_targetpreview_enable"] = "Включить предпросмотр цели",
	["opt_targetpreview_enable_desc"] = "Показывает перемещаемую панель для целей разговора и убийства текущего шага.",
	["opt_targetpreview_onlywhenneeded"] = "Показывать только при необходимости",
	["opt_targetpreview_onlywhenneeded_desc"] = "Скрывает панель предпросмотра, когда у текущего шага нет цели для разговора или убийства.",
	["opt_targetpreview_locked"] = "Заблокировать положение предпросмотра",
	["opt_targetpreview_locked_desc"] = "Запрещает перетаскивание панели предпросмотра цели.",
	["opt_targetpreview_scale"] = "Масштаб предпросмотра",
	["opt_targetpreview_scale_desc"] = "Масштаб панели предпросмотра цели.",
	["opt_targetpreview_width"] = "Ширина предпросмотра",
	["opt_targetpreview_width_desc"] = "Ширина панели предпросмотра цели.",
	["opt_targetpreview_height"] = "Высота предпросмотра",
	["opt_targetpreview_height_desc"] = "Высота панели предпросмотра цели.",
	["opt_targetpreview_pinside"] = "Сторона привязки",
	["opt_targetpreview_pinside_desc"] = "Выберите, к какой стороне просмотрщика должен крепиться предпросмотр цели.",
	["opt_targetpreview_mode"] = "Режим предпросмотра",
	["opt_targetpreview_mode_desc"] = "Выберите, должен ли предпросмотр предпочитать живую 3D-модель, стилизованную карточку информации или оба варианта.",
	["opt_targetpreview_mode_hybrid"] = "Гибрид",
	["opt_targetpreview_mode_model"] = "Только 3D",
	["opt_targetpreview_mode_card"] = "Только карточка",
	["opt_targetpreview_resetanchor"] = "Сбросить положение предпросмотра",
	["opt_targetpreview_resetanchor_desc"] = "Возвращает панель предпросмотра цели в её положение привязки по умолчанию.",
	["gold_app_no_goldguide"] = "Откройте гайд по золоту (/zgold), чтобы загрузить данные трендов.",
	["gold_app_no_goldguide_short"] = "Откройте /zgold, чтобы загрузить гайды.",
	["gold_app_no_goldguide_tooltip"] = "Откройте окно гайда по золоту, чтобы инициализировать данные трендов из сканов аукциона.",
	["gold_app_no_scan_data"] = "Текущие цены неизвестны. Просканируйте аукцион.",
	["gold_app_no_scan_data_short"] = "Текущие цены неизвестны.",
	["gold_app_no_scan_data_tooltip"] = "Просканируйте аукцион, чтобы собрать текущие цены.",
	["gold_app_no_servertrends"] = "Нет данных трендов. Сканируйте ежедневно, чтобы накапливать тренды.",
	["gold_app_no_servertrends_short"] = "Нет данных трендов.",
	["gold_app_no_servertrends_tooltip"] = "Сканируйте аукцион ежедневно, чтобы строить ценовые тренды.",
	["gold_app_old_scan_data"] = "Текущие данные цен устарели. Просканируйте снова.",
	["gold_app_old_scan_data_short"] = "Текущие данные цен устарели.",
	["gold_app_old_scan_data_tooltip"] = "Просканируйте аукцион снова, чтобы обновить текущие данные цен.",
	["gold_app_old_servertrends"] = "Данные трендов устарели. Сканируйте чаще.",
	["gold_app_old_servertrends_short"] = "Данные трендов устарели.",
	["gold_app_old_servertrends_tooltip"] = "Сканируйте аукцион чаще, чтобы поддерживать тренды в актуальном состоянии.",
	["gold_app_trend_tooltip"] = "Направление цены по последним серверным трендам и текущей цене из скана.",
	["gold_auctions_error_noresults"] = "Результаты аукциона не найдены.",
	["gold_crafting_error_noprofessions"] = "Нет производящих профессий.",
	["gold_crafting_error_noresults"] = "Прибыльные рецепты не найдены.",
	["gold_crafting_error_recipesnotcached"] = "Данные рецептов ещё не закешированы.",
	["gold_expertmode_easylabel"] = "Простой режим",
	["gold_expertmode_easytooltip"] = "Показывает более простые и быстрые рекомендации.",
	["gold_expertmode_expertlabel"] = "Экспертный режим",
	["gold_expertmode_experttooltip"] = "Показывает более подробные и продвинутые золотые стратегии.",
	["gold_expertmode_generictooltip"] = "Переключает тип стратегий, которые показывает гайд по золоту.",
	["gold_farming_error_noitemtype"] = "Тип предмета не выбран.",
	["gold_farming_error_noresults"] = "Не найдено результатов фарма по этим условиям.",
	["gold_gathering_error_all_noprofessions"] = "Нет собирательных профессий.",
	["gold_gathering_error_one_noresults"] = "Для этой профессии ничего не найдено.",
	["gold_gathering_error_one_noskillin"] = "Недостаточно навыка для этой зоны.",
	["gold_gathering_error_one_noskillin_skills"] = "Требуемый навык для этой зоны: %s",
	["gold_gathering_error_one_nothing"] = "Нет результатов для отображения.",
	["gold_gathering_error_prof"] = "Профессия: %s",
	["gold_gathering_no_results"] = "Результаты сбора не найдены.",
	["gold_general_open_window1"] = "Откройте гайд по золоту, чтобы",
	["gold_general_open_window2"] = "посмотреть полную информацию.",
	["stepgoal_arrive"] = "Прибыть",
	["stepgoal_cast"] = "Применить",
	["stepgoal_click"] = "Щёлкнуть",
	["stepgoal_fly"] = "Лететь",
	["waypointaddon_disconnecting"] = "Отключение",
	["gb_opt_optimization"] = "Оптимизация",
	["gb_opt_desc_optimization"] = "Настройки, влияющие на производительность, частота обновления стрелки и будущие параметры оптимизации.",
	["opt_optimization_intro"] = "Настройте чувствительное к производительности поведение встроенной стрелки и оставьте место для будущих Wrath-специфичных параметров оптимизации.",
	["opt_optimization_arrow_header"] = "Производительность стрелки",
	["opt_optimization_arrow_desc"] = "Управляет частотой обновления встроенной стрелки пути. Низкие значения снижают нагрузку на CPU, высокие делают движение более плавным.",
	["opt_arrow_refresh_rate"] = "Частота обновления стрелки",
	["opt_arrow_refresh_rate_desc"] = "Управляет тем, как часто обновляется встроенная стрелка пути. Низкие значения снижают нагрузку на CPU, высокие улучшают плавность.",
	["opt_arrow_refresh_rate_20"] = "20 FPS (старый стандарт)",
	["opt_arrow_refresh_rate_30"] = "30 FPS (рекомендуется)",
	["opt_arrow_refresh_rate_60"] = "60 FPS (плавно)",
	["opt_arrow_refresh_rate_unlimited"] = "Без ограничений (каждый кадр)",
	["opt_optimization_internal_only"] = "Эта настройка влияет только на встроенную стрелку пути, когда активен внутренний указатель.",
	["opt_optimization_routing_header"] = "Маршрутизация",
	["opt_optimization_routing_desc"] = "Управляет тем, насколько агрессивно встроенная система перемещений рассчитывает и подготавливает маршруты.",
	["opt_pathfinding_speed"] = "Бюджет расчёта маршрута",
	["opt_pathfinding_speed_desc"] = "Управляет объёмом работы, который LibRover выполняет за одно обновление при построении маршрутов. Низкие значения уменьшают пики CPU, высокие быстрее завершают перерасчёт.",
	["opt_pathfinding_speed_slow"] = "Медленно (минимум CPU)",
	["opt_pathfinding_speed_medium"] = "Средне",
	["opt_pathfinding_speed_fast"] = "Быстро (самые быстрые обновления)",
	["opt_travel_full_linking_startup"] = "Строить полные транспортные связи при запуске",
	["opt_travel_full_linking_startup_desc"] = "Предварительно вычисляет больше транспортных связей при входе в игру. Это может улучшить дальнейшую отзывчивость маршрутов ценой более долгой загрузки.",
	["opt_optimization_memory_header"] = "Память и загрузка",
	["opt_optimization_memory_desc"] = "Будущая цель оптимизации: уменьшить начальное использование памяти за счёт более выборочной загрузки гайдов и шагов. В этом проходе не реализовано.",
	["opt_optimization_diagnostics_header"] = "Диагностика",
	["opt_optimization_diagnostics_desc"] = "Будущая цель оптимизации: лёгкая диагностика FPS или памяти для профилирования подлагиваний и всплесков загрузки. В этом проходе не реализовано.",
} end)

