if GetLocale()~="zhCN" then return end

ZygorGuidesViewer.LocaleFont = [[Fonts\ZYKai_T.ttf]]

ZygorGuidesViewer_L("Main", "zhCN", function() return {
	["name"] = "|cffffff88Z|cffffee66y|cffffdd44g|cffffcc22o|cffffbb00r |cffffaa00Guides Viewer|r",
	["name_plain"] = "Zygor 指南查看器",
	["desc"] = "Zygor Guides Viewer %s 的主要设置。|n",

	['welcome_guides'] = "已加载 %d 个指引。",

	["opt_guide"] = "选择指引：",
	["opt_guide_steps"] = "步骤：%d",
	["opt_guide_author"] = "作者：%s",
	["opt_guide_next"] = "系列中的下一个：%s",

	["opt_report"] = "报告错误步骤",
	["opt_report_desc"] = "创建包含当前显示步骤详细信息的错误报告。复制并粘贴后发送给指引作者。",

	["opt_visible"] = "显示 Zygor Guides Viewer 窗口",
	["opt_visible_desc"] = "",
	["opt_hideincombat"] = "战斗中隐藏指引",
	["opt_hideincombat_desc"] = "当屏幕空间紧张时，在战斗中隐藏所有指引窗口。",

	["opt_opacitymain"] = "透明度",
	["opt_opacitymain_desc"] = "主窗口透明度。",
	["opt_framescale"] = "缩放",
	["opt_framescale_desc"] = "可以按你的偏好调整窗口大小。",
	["opt_fontsize"] = "文字缩放",
	["opt_fontsize_desc"] = "设置首选文字大小。注意窗口缩放也会影响此项。",
	["opt_fontsecsize"] = "次级文字缩放",
	["opt_fontsecsize_desc"] = "设置次级文字大小，用于显示额外描述和备注。",
	["opt_backcolor"] = "背景颜色",
	["opt_backcolor_desc"] = "窗口背景颜色。",

	["opt_group_window"] = "窗口功能",
	["opt_miniresizeup"] = "向上扩展",
	["opt_miniresizeup_desc"] = "将窗口翻转，使其向上而不是向下扩展。适合放在屏幕底部时使用。",
	["opt_opacitymini"] = "背景透明度",
	["opt_opacitymini_desc"] = "步骤窗口背景透明度。",

	["opt_showcountsteps"] = "显示步骤：",
	["opt_showcountsteps_desc"] = "显示步骤数量。\n|cffffffaa全部|r 会在可滚动列表中显示所有步骤。\n|cffffffaa1-5|r 会将当前步骤置顶，并自动调整窗口大小，仅显示后续若干步骤。",
	["opt_showcountsteps_all"] = "全部",

	["opt_group_map"] = "路径点",
	["opt_group_map_desc"] = "这些设置控制 Zygor Guides Viewer 与地图类插件的交互方式。",
	["opt_group_map_waypointing"] = "路径点插件",
	["opt_group_map_waypointing_desc"] = "选择你希望用于 Zygor Guides Viewer 路径点处理的插件。",
	['opt_group_map_hidearrowwithguide'] = "关闭窗口时隐藏箭头",
	['opt_group_map_hidearrowwithguide_desc'] = "启用后，箭头显示将跟随指引窗口可见性。\n若希望隐藏指引时箭头仍显示，请不要勾选。",
	["opt_group_addons_internal"] = "内置路径点",
	["opt_group_addons_builtin"] = "内置路径点",
	["opt_group_addons_tomtom"] = "TomTom",
	["opt_group_addons_carbonite"] = "Carbonite",
	["opt_group_addons_cart2"] = "Cartographer 2",
	["opt_group_addons_cart3"] = "Cartographer 3",
	["opt_group_addons_metamap"] = "MetaMap",
	["opt_group_addons_none"] = "无",
	["opt_debug"] = "调试",
	["opt_debug_desc"] = "显示调试信息。",
	["opt_debugging"] = "调试设置",
	["opt_debugging_desc"] = "调试选项。",

	["opt_autoskip"] = "自动前进",
	["opt_autoskip_desc"] = "当当前步骤条件全部完成时自动跳到下一步。部分条件过于复杂的步骤仍可能需要手动跳过。",

	["opt_goalicons"] = "显示步骤行图标",
	["opt_goalicons_desc"] = "显示反映完成状态的图标。",
	["opt_goalcolorize"] = "为已完成步骤行着色",
	["opt_goalcolorize_desc"] = "完成步骤行时，将整行着为绿色。",
	["opt_goalbackprogress"] = "按完成百分比应用颜色",
	["opt_goalbackprogress_desc"] = "以未完成与完成颜色之间的过渡色显示部分完成进度。|n关闭后，目标只会显示“未完成”或“完成”两种颜色。",

	["opt_group_step"] = "步骤目标",

	["opt_goalbackcolor_desc"] = "完成颜色：",
	["opt_goalbackgrounds"] = "背景着色",
	["opt_goalbackgrounds_desc"] = "为步骤行背景着色以反映完成状态。",
	["opt_goalbackcomplete"] = "完成",
	["opt_goalbackcomplete_desc"] = "此颜色用于表示已完成目标。",
	["opt_goalbackincomplete"] = "未完成",
	["opt_goalbackincomplete_desc"] = "此颜色用于表示未完成目标。",
	["opt_goalbackimpossible"] = "无法完成",
	["opt_goalbackimpossible_desc"] = "此颜色用于表示当前无法完成的目标。",

	['opt_tooltipsbelow'] = "在行内显示额外信息",
	['opt_tooltipsbelow_desc'] = "某些步骤行的额外信息可显示为行内文本，或在鼠标悬停时以提示框显示。",

	["opt_flash_desc"] = "进度提醒：",
	["opt_goalcompletionflash"] = "目标完成时闪烁",
	["opt_goalcompletionflash_desc"] = "当单个目标完成时使用视觉“闪烁”提示。",
	["opt_goalupdateflash"] = "目标进度变化时闪烁",
	["opt_goalupdateflash_desc"] = "当单个目标有进度时使用视觉“闪烁”提示。",
	["opt_flashborder"] = "步骤完成时闪烁窗口",
	["opt_flashborder_desc"] = "每当一个步骤完成时闪烁整个窗口。",

	["opt_group_display"] = "显示",
	["opt_group_display_desc"] = "设置你希望指引如何显示。",

	["opt_group_data"] = "内置指引存储",
	["opt_group_data_desc"] = "Zygor Guides Viewer 可以在内部存储商业指引（由于暴雪政策，这些内容不能以独立插件形式分发）。",
	["opt_group_data_guide"] = "内部存储的指引：",
	["opt_group_data_guide_desc"] = "从列表中选择一个内置指引进行编辑或删除。此列表不会显示作为独立插件加载的指引。",
	["opt_group_data_del"] = "删除指引",
	["opt_group_data_del_desc"] = "从内部存储中删除所选指引。",
	["opt_group_data_edit"] = "编辑指引",
	["opt_group_data_edit_desc"] = "将所选指引加载到下方编辑器窗口以进行手动修改。",
	["opt_group_data_entry"] = "指引数据：",
	["opt_group_data_entry_desc"] = "在此粘贴新指引（请记得将步骤包裹在：|nguide 指引标题|nsteps...|nsteps...|nend\n）；注意粘贴并解析较大指引（>30kB）可能需要几秒钟。",

	['opt_windowlocked'] = "锁定窗口",
	['opt_windowlocked_desc'] = "锁定窗口，使其不再响应鼠标交互。\n仅按钮仍可使用。",
	['opt_hideborder'] = "自动隐藏边框",
	['opt_hideborder_desc'] = "当鼠标离开窗口时自动隐藏窗口边框和按钮。\n将鼠标悬停在窗口标题片刻可再次显示。",

	['opt_skin'] = "窗口皮肤颜色",
	['opt_skin_desc'] = "选择窗口装饰颜色以匹配你的界面。",
	['opt_skin_violet'] = "|cffee55ff紫色",
	['opt_skin_green'] = "|cff88ff88绿色",
	['opt_skin_blue'] = "|cff99aaff蓝色",
	['opt_skin_orange'] = "|cffffbb00橙色",
	["opt_skinpanel_title"] = "外观",
	["opt_skinpanel_desc"] = "选择指南查看器的视觉主题。",
	["opt_skinpanel_intro"] = "先选择查看器的整体外观，再细调大小、透明度和文字。Remaster 仍然是推荐的默认皮肤，而 Retail 则提供更接近暴雪原生界面的风格。",
	["opt_skinpanel_skin"] = "皮肤",
	["opt_skinpanel_skin_desc"] = "选择皮肤及其颜色变体。",
	["opt_skinpanel_appearance_header"] = "显示",
	["opt_skinpanel_appearance_desc"] = "调整查看器缩放、文字大小和框体透明度。",
	["opt_skinpanel_colors_header"] = "颜色",
	["opt_skinpanel_colors_desc"] = "调整所选皮肤变体的框体背景强度。",
	["opt_skinpanel_advanced_header"] = "高级",
	["opt_skinpanel_advanced_desc"] = "影响框体布局和步骤显示方式的低频显示选项。",

	['opt_backopacity'] = "背景透明度",
	['opt_backopacity_desc'] = "窗口背景透明度。",

	["report_title"] = "按 Ctrl+C 复制此报告。|n然后将其发送给 |cffffffff%s|r 的作者，|n地址：|cffffffff%s|r。",
	["report_notitle"] = "|cffff8888（未命名指引？）|r",
	["report_noauthor"] = "|cffff8888（无可用地址）|r",

	["opt_mapbutton"] = "显示小地图按钮",
	["opt_mapbutton_desc"] = "在小地图旁显示 Zygor Guides Viewer 按钮",

	["minimap_tooltip"] = "|cffeedd99左键|r 切换指引窗口|n|cffeedd99右键|r 打开设置|n",

	["waypointaddon_set"] = "已选择路径点插件：%s",
	["waypointaddon_connecting"] = "正在连接路径点插件：%s",
	["waypointaddon_connected"] = "已成功连接到 %s。",
	["waypointaddon_fail"] = "连接 %s 失败。",
	['waypoint_step'] = "步骤 %s",

	["checkmap"] = "请查看地图。",

	["initialized"] = "初始化完成。",

	["miniframe_notloaded"] = "未加载任何升级指引。|n|n请前往 http://zygorguides.com 购买 Zygor 的 1-80 升级指引，或加载第三方指引。|n|n如果你确定已经安装了指引，请联系其作者获取安装排错帮助。",
	["miniframe_notselected"] = "当前未选择任何指引。\n请点击上方闪烁按钮以选择一个指引。",
	["miniframe_loading"] = "正在加载指引：%d%%",

	['frame_locked'] = "窗口已锁定",
	['frame_unlock'] = "|cffeedd99左键|r 解锁",
	['frame_unlocked'] = "窗口未锁定",
	['frame_lock'] = "|cffeedd99左键|r 锁定",
	['frame_settings'] = "设置",
	['frame_settings1'] = "|cffeedd99左键|r 打开菜单",
	['frame_settings2'] = "|cffeedd99右键|r 打开选项",
	['frame_minimized'] = "显示 |cffffffff%d|r 个步骤",
	['frame_maximized'] = "显示全部步骤",
	['frame_minimize'] = "|cffeedd99左键|r 仅显示 |cffffffff%d|r 个",
	['frame_minright'] = "|cffeedd99右键|r 设置显示步骤数",
	['frame_maximize'] = "|cffeedd99左键|r 显示全部",
	['frame_stepnav_prev'] = "上一步",
	['frame_stepnav_prev_click'] = "|cffeedd99左键|r：后退",
	['frame_stepnav_prev_right'] = "|cffeedd99右键|r：回退",
	['frame_stepnav_next'] = "下一步",
	['frame_stepnav_next_click'] = "|cffeedd99左键|r：前进",
	['frame_stepnav_next_right'] = "|cffeedd99右键|r：快速前进",
	['frame_section'] = "当前指引",
	['frame_section_click'] = "|cffeedd99点击|r 选择",

	['tooltip_tip'] = "|cff99ff00%s|r",
	['tooltip_waypoint'] = "|cffeedd99点击|r|cff00ff00 设置路径点：|cffffaa00%s|r",
	['tooltip_waypoint_coords'] = "位置：|cffffaa00%s|r",

	["message_errorloading_full"] = "加载指引 |cffaaffaa%s|r 时发生 |cffff4444错误|r\n第 %d 行：%s\n错误：%s",
	["message_errorloading_brief"] = "加载指引 |cffaaffaa%s|r 时发生 |cffff4444错误|r",
	["message_loadedguide"] = "已启用指引：|cffaaffaa%s|r",
	["message_missingguide"] = "缺失指引：|cffaaffaa%s|r",
	["title_noguide"] = "Zygor Guides Viewer（未加载指引）",

	['step_num'] = "|cffaaaaaa%s|cff888888.|r ",
	['step_level'] = "|cffaaccaa等级：|cffcceecc%s|cffaaccaa|r ",

	["questtitle"] = "“%s”",
	["questtitle_part"] = "“%s”（第 %s 部分）",
	["coords"] = "%d,%d",
	["map_coords"] = "%s %d,%d",

	["stepgoal_home"] = "将炉石地点设置为 %s",
	["stepgoal_flightpath"] = "获取 %s 飞行点",

	["stepgoal_accept"] = "接受 %s",
	["stepgoal_turn in"] = "交付 %s",
	["stepgoal_talk to"] = "与 %s 对话",
	["stepgoal_kill"] = "击杀 %s",
	["stepgoal_kill #"] = "击杀 %s %s",
	["stepgoal_goal"] = "%s",
	["stepgoal_goal #"] = "%s %s",
	["stepgoal_get"] = "获得 %s",
	["stepgoal_get #"] = "获得 %s %s",
	["stepgoal_ding"] = "你现在应为 %s 级。|n    若不是，请稍微刷怪直到达到该等级。",
	["stepgoal_go to"] = "前往 %s",
	["stepgoal_also at"] = "也在 %s",
	["stepgoal_hearth to"] = "炉石返回 %s",
	["stepgoal_collect"] = "收集 %s",
	["stepgoal_collect #"] = "收集 %s %s",
	["stepgoal_buy"] = "购买 %s %s",
	["stepgoal_fpath"] = "获取 %s 飞行点",
	["stepgoal_use"] = "使用 %s",
	["stepgoal_home"] = "将 %s 设为你的炉石地点",
	["stepgoal_petaction"] = "使用宠物技能 %s",
	["stepgoal_havebuff"] = "获得增益/减益“%s”",
	["stepgoal_nobuff"] = "失去增益/减益“%s”",
	["stepgoal_invehicle"] = "进入载具",
	["stepgoal_outvehicle"] = "离开载具",
	["stepgoal_equipped"] = "装备 %s",
	["stepgoal_at_suff"] = "（%s）",

	["completion_collect"] = "(%s/%s)",
	["completion_goal"] = "(%s/%s)",
	["completion_ding"] = "(%s%%)",
	["completion_done"] = "(完成)",
	["completion_rep"] = "(%s)",

	["step_req"] = "此步骤仅对以下条件有效：%s",

	["map_highlight"] = "高亮",

	["stepreq"] = "步骤职业/种族要求：",
	["stepreqor"] = " 或 ",

	["opt_do_searchforgoal"] = "查找可完成目标",
	["searching_for_goal_success"] = "已找到一个可完成目标：%s。它可能是你在此指引中的合适起点。",
	["searching_for_goal_failed"] = "未找到可完成目标。请尝试其他指引或章节、先接一些任务，或从章节开头再次搜索（搜索只会向前进行）。",


	["going"] = "%d%% 进行中：%s",
	["opt_stepnumber"] = "显示步骤编号",
	["opt_stepnumber_desc"] = "为每个步骤显示步骤编号和建议等级。\n关闭后可节省一些屏幕空间。",
	["opt_hidestepborders"] = "隐藏边框",
	["opt_hidestepborders_desc"] = "隐藏步骤周围的图形边框。",
	["opt_stepbackopacity"] = "背景透明度",
	["opt_stepbackopacity_desc"] = "步骤窗口背景的透明度。\n背景颜色会反映完成状态与淡出效果。",
	["opt_goalbackprogressing"] = "进行中",
	["opt_goalbackprogressing_desc"] = "目标进行到约 50% 时使用的颜色。",
	["opt_progressbackcolor_desc"] = "进度颜色：",
	["opt_goalbackaux"] = "辅助",
	["opt_goalbackaux_desc"] = "辅助目标使用的颜色。",
	["opt_goalbackobsolete"] = "过时",
	["opt_goalbackobsolete_desc"] = "过时目标使用的颜色。",
	["opt_resetwindow"] = "重置窗口",
	["opt_resetwindow_desc"] = "如果窗口跑到屏幕外，此按钮会将其重置回中央。",
	["opt_trackchains"] = "跟踪任务链",
	["opt_trackchains_desc"] = "如果前置任务未完成，则将接任务步骤标记为不可用。\n\n任务链数据库也包含“宽松链条”数据，即任务彼此相关但不一定严格要求顺序，因此有时会把实际上仍可接的任务显示为不可用。",
	["opt_guidesinhistory"] = "最近指南数量",
	["opt_guidesinhistory_desc"] = "显示这么多最近使用过的指南。",
	["opt_skin_remaster"] = "|cffc7d9ffRemaster（默认）",
	["opt_group_progress"] = "动态进度",
	["opt_group_progress_desc"] = "为了让升级路径更高效，插件会动态跳过对你当前等级收益已不大的任务。",
	["opt_levelsahead"] = "允许超前等级",
	["opt_levelsahead_desc"] = "此设置决定你可以比指南高出多少级。\n设为 0 时，通常会跳过所有低于你当前等级的任务（除非它们有后续）。\n设为 1 或更高时，只会跳过比你低超过该数值的任务。",
	["opt_showobsolete"] = "标记过时步骤",
	["opt_showobsolete_desc"] = "用灰色背景标记过时步骤。\n当步骤等级对你来说过低时，它会被视为过时。",
	["opt_skipobsolete"] = "跳过过时步骤",
	["opt_skipobsolete_desc"] = "自动跳过过时步骤。",
	["opt_skipauxsteps"] = "跳过辅助步骤",
	["opt_skipauxsteps_desc"] = "如果一个交通或过渡步骤之后只剩已完成或已过时的步骤，则自动跳过该辅助步骤。\n这样可避免你走很远后却发现下个步骤早就做过了。",
	["opt_skipflightsteps"] = "视为已知飞行点",
	["opt_skipflightsteps_desc"] = "假定你会自己学习飞行路线，并自动将学习飞行点的步骤标记为完成。\n\n在从指南中途开始时很有用，正常游玩时则没那么必要。",
	["opt_skipimpossible"] = "跳过不可能步骤",
	["opt_skipimpossible_desc"] = "自动跳过不可能完成的步骤，以免显示来自你刻意跳过任务的目标。",
	["opt_group_progress_bottomdesc"] = "动态进度的运作方式是：当你超过指南等级的幅度大于上方设置值时，任务会被标记为“过时”。任务链只有在整条链都过时时才会标记为过时。\n\n对于新手玩家，这有助于智能跳过低等级内容，只在仍然有价值的任务链上停留。\n\n对于熟练玩家，这能避免指南在你升级过快时继续拖着你去做低等级任务。",
	["opt_group_mapinternal"] = "内置路径点",
	["opt_arrowmeters"] = "公制单位",
	["opt_arrowmeters_desc"] = "使用米和公里，而不是码和英里。",
	["opt_arrowfreeze"] = "箭头忽略鼠标",
	["opt_arrowfreeze_desc"] = "让箭头忽略鼠标操作。关闭后可拖动它。",
	["opt_arrowcam"] = "箭头跟随镜头",
	["opt_arrowcam_desc"] = "根据镜头方向显示箭头。如果关闭，箭头将依据角色朝向。\n\n注意：在镜头模式下，点击移动时箭头可能表现异常。",
	["opt_arrowcolordir"] = "按方向着色",
	["opt_arrowcolordir_desc"] = "当箭头指向正确方向时，将其颜色变为绿色。\n\n如果你只想在接近目标时才显示绿色，请关闭此选项。",
	["opt_arrowscale"] = "箭头缩放",
	["opt_arrowscale_desc"] = "箭头的大小。",
	["opt_arrowfontsize"] = "箭头文字大小",
	["opt_arrowfontsize_desc"] = "箭头窗口中文字的大小。",
	["opt_minimapzoom"] = "自动缩放小地图",
	["opt_minimapzoom_desc"] = "设置路径点时自动放大小地图，之后再恢复原先缩放。",
	["opt_foglight"] = "探索地图迷雾",
	["opt_foglight_desc"] = "在地图上显示尚未探索的区域。",
	["opt_targetpreview_growth"] = "增长方向",
	["opt_targetpreview_growth_desc"] = "选择固定后的目标预览是跟随查看器的缩放方向，向上增长，还是向下增长。",
	["opt_targetpreview_growth_auto"] = "跟随查看器",
	["opt_targetpreview_growth_up"] = "向上增长",
	["opt_targetpreview_growth_down"] = "向下增长",
	["opt_group_gold"] = "金币指南",
	["opt_group_gold_desc"] = "这些设置控制金币路线步骤和资源点的显示方式。",
	["opt_gold_detectiondist"] = "检测距离",
	["opt_gold_detectiondist_desc"] = "决定在多远范围内显示附近的金币指南点位。",
	["opt_gold_reqmode"] = "需求模式",
	["opt_gold_reqmode_desc"] = "选择应当考虑哪些类型的点位。",
	["opt_gold_reqmode_all"] = "全部",
	["opt_gold_reqmode_current"] = "当前专业等级",
	["opt_gold_reqmode_future"] = "当前专业，但忽略等级",
	["gold_missing_noguidesloaded"] = "未加载金币指南。",
	["gold_missing_nospotsinrange"] = "范围内没有可用点位。",
	["gold_header_ore"] = "矿点：",
	["gold_header_herb"] = "草药：",
	["gold_header_skin"] = "剥皮目标：",
	["gold_header_drop"] = "|cffffdddd%s|r 掉落：",
	["opt_group_convenience"] = "便捷功能",
	["opt_group_convenience_desc"] = "各种实用的辅助选项。",
	["opt_autoaccept"] = "自动接任务",
	["opt_autoaccept_desc"] = "自动接受提供给你的任务。",
	["opt_autoturnin"] = "自动交任务",
	["opt_autoturnin_desc"] = "自动交付已完成的任务。",
	["opt_fixblizzardautoaccept"] = "修正暴雪自动接任务",
	["opt_fixblizzardautoaccept_desc"] = "当启用暴雪的“自动接受任务”功能时，仍然正确处理“接受”和“已接受”步骤的完成状态。",
	["opt_audiocues"] = "声音提示",
	["opt_audiocues_desc"] = "在步骤进度变化时播放提示音。",
	["opt_analyzereps"] = "分析声望",
	["opt_analyzereps_desc"] = "分析你当前的声望，并将无效的声望步骤标记为过时。",
	["opt_mapcoords"] = "显示地图坐标",
	["opt_mapcoords_desc"] = "在地图窗口中显示玩家与鼠标坐标。",
	["stepgoal_rep"] = "与 %s 达到%s",
	["stepgoal_achieve"] = "完成成就%s",
	["stepgoal_achievesub"] = "完成成就%s的子目标%s",
	["stepgoal_skill"] = "将 %s 提升到 %s",
	["stepgoal_skillmax"] = "将 %s 提升到最大 %s",
	["stepgoal_learn"] = "学习 %s",
	["stepgoal_or"] = "  - ? -",
	["stepgoalshort_complete"] = "完成",
	["stepgoalshort_incomplete"] = "未完成",
	["stepgoalshort_questgoal"] = "(%d/%d)",
	["stepgoalshort_level"] = "(%d%%)",
	["waypointaddon_detecting"] = "正在尝试自动检测路径点插件……",
	["waypointaddon_disconnected"] = "已从 |cffddeeff%s|r 断开连接。",
	["pointer_corpselabel1"] = "曾经的你",
	["pointer_corpselabel2"] = "学会逃跑的人……",
	["pointer_corpselabel3"] = "吃不下这么多吧？",
	["pointer_corpselabel4"] = "踢桶大师在这边",
	["pointer_corpselabel5"] = "尽量别去想修理费。",
	["req_not"] = "? %s",
	["haman$"] = "hamans",
	["(%a)man$"] = "%1men",

	["binding_togglewindow"] = "显示指引窗口",
	["binding_prev"] = "上一步",
	["binding_next"] = "下一步",
	["menu_last"] = "最近使用的指引：",
	["menu_last_entry"] = "%s |cffaaaaaa步骤|r %d",
	["gb_window_title"] = "指南浏览器",
	["gb_addon_title"] = "Zygor Guides Viewer Remastered",
	["gb_root"] = "首页",
	["gb_search"] = "搜索",
	["gb_folders"] = "文件夹",
	["gb_guides"] = "指南",
	["gb_load_guide"] = "加载指南",
	["gb_open_legacy"] = "打开旧版选择器",
	["gb_path_format"] = "路径：%s",
	["gb_select_guide"] = "选择一个指南",
	["gb_select_guide_from_list"] = "从列表中选择一个指南。",
	["gb_select_settings_page"] = "选择一个设置页面",
	["gb_all_guides"] = "全部指南",
	["gb_other"] = "其他",
	["gb_unknown"] = "未知",
	["gb_none"] = "无",
	["gb_folder_format"] = "文件夹：%s",
	["gb_progress_format"] = "进度：%d%%",
	["gb_guides_count_format"] = "%d 个指南",
	["gb_current_meta_format"] = "步骤 %d / %d  |  %s",
	["gb_detail_meta_format"] = "步骤：%d\n作者：%s\n下一个：%s",
	["gb_tab_home"] = "主页",
	["gb_tab_featured"] = "推荐",
	["gb_tab_current"] = "当前",
	["gb_tab_recent"] = "最近",
	["gb_tab_options"] = "设置",
	["gb_cat_leveling"] = "升级",
	["gb_cat_dungeons"] = "地下城",
	["gb_cat_daily"] = "日常",
	["gb_cat_events"] = "活动",
	["gb_cat_reputations"] = "声望",
	["gb_cat_gold"] = "金币",
	["gb_cat_professions"] = "专业",
	["gb_cat_petsmounts"] = "宠物与坐骑",
	["gb_cat_titles"] = "头衔",
	["gb_cat_achievements"] = "成就",
	["gb_cat_misc"] = "杂项",
	["gb_cat_favorites"] = "收藏",
	["gb_opt_guides"] = "指南",
	["gb_opt_desc_guides"] = "指南选择、当前指南信息和核心控制。",
	["gb_opt_stepdisplay"] = "步骤显示",
	["gb_opt_desc_stepdisplay"] = "查看器外观、框体布局、皮肤/字体以及步骤与目标显示控制。",
	["gb_opt_progress"] = "进度",
	["gb_opt_desc_progress"] = "步骤推进行为、跳过规则和完成流程。",
	["gb_opt_travel"] = "旅行系统",
	["gb_opt_desc_travel"] = "路径点提供者选择和旅行系统行为。",
	["gb_opt_map"] = "地图与路径点",
	["gb_opt_desc_map"] = "箭头样式、小地图/地图标记和路径点外观。",
	["gb_opt_notifications"] = "通知",
	["gb_opt_desc_notifications"] = "进度/完成时的闪烁与提醒。",
	["gb_opt_actionbuttons"] = "动作按钮",
	["gb_opt_desc_actionbuttons"] = "可点击步骤/目标交互的显示行为。",
	["gb_opt_convenience"] = "任务",
	["gb_opt_desc_convenience"] = "自动接取/交付以及便捷任务辅助。",
	["gb_opt_accessibility"] = "无障碍",
	["gb_opt_desc_accessibility"] = "提升颜色可见性和可读性的选项。",
	["gb_opt_profile"] = "配置档",
	["gb_opt_desc_profile"] = "按角色/全局配置档管理以及复制/重置工具。",
	["gb_opt_about"] = "关于",
	["gb_opt_desc_about"] = "版本、支持和诊断/报错工具。",
	["gb_opt_advanced"] = "高级",
	["gb_opt_desc_advanced"] = "调试工具、诊断和开发者控制。",
	["gb_opt_general"] = "常规",
	["gb_opt_desc_general"] = "常规设置。",
	["gb_title_viewer"] = "查看器",
	["gb_options_viewer_desc"] = "查看器核心行为、指南加载和基础插件控制。",
	["gb_hint_search_settings"] = "提示：\n使用左侧搜索可快速找到设置页面。",
	["gb_hint_options_filter"] = "提示：\n左侧搜索会筛选设置页面。\n使用“打开完整选项”查看完整的 Blizzard 面板。",
	["gb_empty_no_guides_search"] = "没有指南匹配此搜索。",
	["gb_empty_no_guides_category"] = "此分类中没有指南。",
	["gb_empty_no_current_guide"] = "当前没有加载指南。",
	["gb_empty_no_current_guide_short"] = "当前没有加载指南",
	["gb_empty_no_recent_guides"] = "还没有最近使用的指南。",
	["gb_empty_no_featured_match"] = "没有推荐项符合此筛选。",
	["gb_empty_no_featured_suggestions"] = "没有推荐建议",
	["gb_empty_no_favorites"] = "还没有收藏的指南。",
	["gb_no_guide_selected"] = "未选择指南",
	["gb_action_clear_search"] = "清除搜索",
	["gb_action_show_all_categories"] = "显示所有分类",
	["gb_action_go_home"] = "前往首页",
	["gb_action_open_home"] = "打开首页",
	["gb_action_reset_snoozed"] = "重置已隐藏建议",
	["gb_action_clear_search_restore"] = "清除搜索以恢复建议",
	["gb_action_reset_snoozed_restore"] = "重置已隐藏建议以恢复推荐",
	["gb_action_try_home"] = "试试首页以浏览所有分类",
	["gb_action_browse_all_from_home"] = "从首页浏览所有指南",
	["gb_action_back_to_guides"] = "返回指南",
	["gb_action_open_full_options"] = "打开完整选项",
	["gb_action_go_current_folder"] = "前往当前指南文件夹",
	["gb_action_resume"] = "继续",
	["gb_action_restart"] = "重新开始",
	["gb_nav_navigation"] = "导航",
	["gb_nav_back"] = "返回",
	["gb_nav_reset_to_root"] = "重置到分类根目录",
	["gb_featured_bucket_next"] = "下一步",
	["gb_featured_bucket_progress"] = "进行中",
	["gb_featured_bucket_level"] = "适合你当前等级",
	["gb_featured_bucket_featured"] = "推荐路线",
	["gb_featured_confidence_strong"] = "高",
	["gb_featured_confidence_good"] = "良好",
	["gb_featured_confidence_fallback"] = "备用",
	["gb_roadmap"] = "路线图",
	["gb_roadmap_bucket_format"] = "%s 路线图",
	["gb_bucket_preview_next_with_title"] = "继续你的路线：%s",
	["gb_bucket_preview_next"] = "继续当前路线",
	["gb_bucket_preview_progress_with_title"] = "继续：%s",
	["gb_bucket_preview_progress"] = "继续进行中的指南",
	["gb_bucket_preview_level_with_title"] = "开始适合等级的路线：%s",
	["gb_bucket_preview_level"] = "开始适合当前等级的指南",
	["gb_bucket_preview_featured_with_title"] = "可选路线：%s",
	["gb_bucket_preview_featured"] = "可选路线和额外内容",
	["gb_meta_action"] = "操作",
	["gb_meta_suggestion"] = "建议",
	["gb_meta_suggested"] = "已推荐",
	["gb_meta_current"] = "当前",
	["gb_meta_recommended"] = "推荐",
	["gb_meta_other_useful_option"] = "其他有用选项",
	["gb_meta_current_selection"] = "当前选择",
	["gb_meta_suggestions_snoozed"] = "建议可能已被隐藏",
	["gb_meta_restore_recommendations"] = "恢复推荐",
	["gb_meta_filter_no_matches"] = "筛选无匹配结果",
	["gb_meta_see_full_recommendations"] = "查看完整推荐",
	["gb_meta_no_bucket_suggestions"] = "此分组中没有建议",
	["gb_meta_full_category_access"] = "查看完整分类",
	["gb_meta_suggested_from"] = "建议来源：%s",
	["gb_meta_confidence"] = "置信度：%s",
	["gb_meta_why_prefix"] = "原因：",
	["gb_meta_gain_prefix"] = "收益：",
	["gb_reason_recently_used"] = "最近使用",
	["gb_reason_incomplete"] = "未完成",
	["gb_reason_your_level_range"] = "适合你的等级范围",
	["gb_reason_near_your_level"] = "接近你的等级",
	["gb_reason_your_class"] = "适合你的职业",
	["gb_reason_your_race"] = "适合你的种族",
	["gb_reason_your_profession"] = "适合你的专业",
	["gb_reason_favorite"] = "收藏",
	["gb_reason_current_chain"] = "当前路线",
	["gb_reason_chain_step_format"] = "路线步骤 +%d",
	["gb_reason_inferred_continuation"] = "推断的后续路线",
	["gb_reason_chapter_continuation"] = "章节延续",
	["gb_tooltip_featured_controls"] = "推荐建议控制说明",
	["gb_tooltip_featured_click"] = "点击 X：隐藏 24 小时",
	["gb_tooltip_featured_shift_click"] = "Shift+点击 X：本次会话中隐藏",
	["gb_tooltip_featured_restore"] = "按 R 或在选项中重置以恢复。",
	["gb_tooltip_snooze"] = "隐藏建议",
	["gb_tooltip_snooze_click"] = "点击：隐藏 24 小时",
	["gb_tooltip_snooze_shift_click"] = "Shift+点击：本次会话中隐藏",
	["gb_tooltip_why_prefix"] = "原因：",
	["gb_tooltip_gain_prefix"] = "收益：",
	["gb_tooltip_confidence_prefix"] = "置信度：",
	["gb_tooltip_chain_prefix"] = "路线：",
	["gb_tooltip_fallback_recommendation"] = "备用推荐",
	["gb_current_guide"] = "当前指南",
	["gb_options_fallback_embed_unavailable"] = "内嵌选项不可用。再次点击“设置”以打开 Blizzard 界面选项。",
	["gb_options_fallback_missing_widgets"] = "内嵌选项不可用。缺少 AceGUI 嵌入控件。",
	["gb_options_fallback_render_error"] = "无法渲染内嵌选项：%s",
	["opt_legacyguideddropdown"] = "旧版指南下拉菜单",
	["opt_featured_header"] = "精选推荐",
	["opt_featured_enablefallback"] = "启用备用推荐",
	["opt_featured_enablefallback_desc"] = "当精选分组没有直接匹配时，显示一些有用的备用指南。",
	["opt_featured_hiderecentcompleted"] = "隐藏最近完成的指南",
	["opt_featured_hiderecentcompleted_desc"] = "将刚刚完成的指南从智能精选推荐中隐藏。",
	["opt_featured_showconfidence"] = "显示置信标签",
	["opt_featured_showconfidence_desc"] = "在精选条目中显示 Strong/Good/Fallback 置信标记。",
	["opt_featured_resethidden"] = "重置已隐藏推荐",
	["opt_featured_resethidden_desc"] = "恢复通过关闭按钮隐藏的精选推荐。",
	["opt_disablerouteloopstacking"] = "禁用路线/循环堆叠",
	["opt_disablerouteloopstacking_desc"] = "防止路线和循环内容堆叠到同一个精选分组中。",
	["opt_routeantminimapmode"] = "小地图路线轨迹",
	["opt_routeantminimapmode_desc"] = "选择在小地图上显示多少行进蚂蚁路线。",
	["opt_routeantminimapmode_local"] = "当前路段",
	["opt_routeantminimapmode_local_desc"] = "只显示当前附近的路段：上一个点、当前点和下一个点。",
	["opt_routeantminimapmode_all"] = "全部路线",
	["opt_routeantminimapmode_all_desc"] = "在小地图上显示整条路线或循环。",
	["opt_routeantminimapmode_none"] = "仅显示路径点",
	["opt_routeantminimapmode_none_desc"] = "隐藏小地图上的行进蚂蚁，只显示当前活动路径点。",
	["opt_routeantdensity"] = "路线轨迹密度",
	["opt_routeantdensity_desc"] = "调整路径点之间行进蚂蚁的密集程度。1 最稀疏，5 为当前默认值，9 为最高密度。",
	["opt_accessibility_intro"] = "调整颜色可见性和文字清晰度相关的视觉无障碍选项。",
	["opt_colorblindmode"] = "色盲模式",
	["opt_colorblindmode_desc"] = "将指南、箭头和距离颜色替换为适合色盲的调色板，同时强制使用更高对比度的箭头名词颜色。",
	["opt_colorblindmode_off"] = "关闭",
	["opt_colorblindmode_protanopia"] = "红色盲",
	["opt_colorblindmode_deuteranopia"] = "绿色盲",
	["opt_colorblindmode_tritanopia"] = "蓝色盲",
	["opt_colorblindmode_global"] = "全局",
	["opt_colorblindmode_custom"] = "自定义",
	["opt_arrowcolor_far"] = "远",
	["opt_arrowcolor_mid"] = "中",
	["opt_arrowcolor_near"] = "近",
	["opt_simplifyarrownouncolors"] = "简化箭头文字颜色",
	["opt_simplifyarrownouncolors_desc"] = "为箭头标签使用更清晰、更高对比度的颜色。",
	["opt_about_heading"] = "适用于 WoTLK 3.3.5a 的 Zygor Guides Viewer Remastered",
	["opt_about_support"] = "支持",
	["opt_about_diag"] = "提示：`/zygor status` 和 `/zygor debug` 可帮助排查问题。",
	["opt_showminimapicons"] = "显示小地图图标",
	["opt_showminimapicons_desc"] = "在小地图上显示图标",
	["opt_iconalpha"] = "图标透明度",
	["opt_iconalpha_desc"] = "地图标记图标的透明度",
	["opt_iconsize"] = "图标大小",
	["opt_iconsize_desc"] = "地图上图标的大小",
	["opt_arrowshow"] = "显示箭头",
	["opt_arrowshow_desc"] = "显示或隐藏内置路径点箭头。",
	["opt_arrowcolormode_direction"] = "方向",
	["opt_arrowcolormode_distance"] = "距离",
	["opt_arrowtextoutline"] = "箭头文字描边",
	["opt_arrowtextoutline_desc"] = "选择路径点箭头文字的描边强度。",
	["opt_arrowtextoutline_default"] = "默认",
	["opt_arrowtextoutline_strong"] = "强",
	["opt_arrowtextoutline_reduced"] = "弱",
	["opt_remasterpointeronlegacy"] = "在旧皮肤上使用重制版指针",
	["opt_remasterpointeronlegacy_desc"] = "启用后，旧皮肤将使用重制版路径点箭头样式。",
	["opt_resetarrowposition"] = "重置箭头位置",
	["opt_resetarrowposition_desc"] = "将路径点箭头重置为默认位置。",
	["opt_foglightdebug"] = "（调试）检查 foglight",
	["opt_foglightdebug_desc"] = "检查当前地图的 foglight",
	["opt_travelsystem_intro"] = "选择如何处理旅行和路径点提供者。",
	["opt_mapswaypoints_intro"] = "配置地图标记和内置箭头外观。",
	["opt_notifications_intro"] = "配置步骤推进时的视觉通知提示。",
	["opt_actionbuttons_intro"] = "配置目标图标和交互式步骤显示。",
	["frame_toolbar_guides"] = "指南",
	["frame_toolbar_guides_click"] = "打开指南菜单",
	["frame_toolbar_guides_right"] = "打开指南管理器",
	["frame_toolbar_close"] = "关闭",
	["frame_toolbar_close_click"] = "关闭",
	["frame_toolbar_settings"] = "设置",
	["frame_toolbar_settings_click"] = "打开快捷菜单",
	["frame_toolbar_settings_right"] = "打开指南管理器设置",
	["frame_toolbar_stepview"] = "步骤视图",
	["frame_toolbar_stepview_showall"] = "显示全部",
	["frame_toolbar_stepview_showonly"] = "仅显示 |cffffffff%s|r",
	["frame_toolbar_stepview_setcount"] = "设置步骤数量",
	["frame_toolbar_unlock"] = "解锁窗口",
	["frame_toolbar_unlock_click"] = "解锁",
	["frame_toolbar_lock"] = "锁定窗口",
	["frame_toolbar_lock_click"] = "锁定",
	["frame_title_default"] = "Zygor Guides",
	["frame_tab_guides"] = "指南",
	["frame_tab_spots"] = "点位",
} end)

local plurals = {
}

ZygorGuidesViewer_L("Specials", "zhCN", function() return {
	["plural"] = function (word)
		return word
	end,
	['contract_mobs'] = false,
	['contract_mobs_old'] = function(mobs)
			local start,ending

			if not mobs[1].name and type(mobs)=="table" then
				local l=mobs
				mobs={}
				for i=1,#l do mobs[i]={name=l[i]} end
			end
			local common,all
			for i=1,50 do
				common = mobs[1].name:sub(1,i)
				all=true
				for m=2,#mobs do
					if mobs[m].name:find(common)~=1 then
						all=false
						break
					end
				end
				if not all then
					common = common:sub(1,-2)
					break
				end
			end
			if common:sub(-1)==" " then common = common:sub(1,-2) end
			start=common

			for i=1,50 do
				common = mobs[1].name:sub(-i)
				all=true
				for m=2,#mobs do
					if mobs[m].name:sub(-i)~=common then
						all=false
						break
					end
				end
				if not all then
					common = common:sub(2)
					break
				end
			end
			if common:sub(1,1)==" " then common = common:sub(2) end
			ending=common

			if #start>#ending and #start>3 then
				return ZygorGuidesViewer_L("Specials")['contract_mobs_start'](start)
			elseif #ending>#start and #ending>3 then
				return ZygorGuidesViewer_L("Specials")['contract_mobs_end'](ending)
			else
				return nil
			end
		end,
	['contract_mobs_start'] = function(s) return ZygorGuidesViewer_L("Specials")['plural'](s) end,
	['contract_mobs_end'] = function(s)
		return ZygorGuidesViewer_L("Specials")['plural'](s)
	end,
} end)

ZygorGuidesViewer_L("G_string", "zhCN", function() return {
	["blabla"] = TRUE,
} end)

ZygorGuidesViewer_L("Main", "zhCN", function() return {
	["mainframe_guide"] = "选择一个指南：",
	["mainframe_notloaded"] = "没有加载升级指南。",
	["mainframe_notselected"] = "已加载 %d 个指南。|n请从上方列表中选择一个指南。",
	["opt_group_main"] = "主设置",
	["opt_browse"] = "切换窗口",
	["opt_browse_desc"] = "切换 Zygor 指南窗口的显示状态。",
	["opt_autosizemini"] = "自动调整大小",
	["opt_autosizemini_desc"] = "自动调整迷你窗口的高度。",
	["opt_colorborder"] = "步骤窗口边框着色",
	["opt_colorborder_desc"] = "使用步骤窗口边框颜色来表示整个步骤的完成状态。",
	["opt_minimapnotedesc"] = "显示路径点说明",
	["opt_minimapnotedesc_desc"] = "不仅在路径点提示中显示相关路径点说明，也在迷你窗口中显示。",
	["opt_showallsteps"] = "折叠模式",
	["opt_showallsteps_desc"] = "只显示当前步骤和接下来的几个步骤，而不是整个指南。",
	["opt_showgoals"] = "显示步骤目标",
	["opt_showgoals_desc"] = "在迷你窗口中显示步骤完成目标。",
	["frame_selectguide"] = "选择指南",
	["frame_selectguide_left"] = "请在左侧选择一个指南。",
	["frame_toolbar_stepview_options"] = "步骤视图选项",
	["targetpreview_level"] = "等级",
	["targetpreview_class_boss"] = "首领",
	["targetpreview_class_elite"] = "精英",
	["targetpreview_class_rareelite"] = "稀有精英",
	["targetpreview_class_rare"] = "稀有",
	["targetpreview_title"] = "目标预览",
	["targetpreview_title_locked"] = "目标预览",
	["targetpreview_role_talk"] = "交谈",
	["targetpreview_role_kill"] = "击杀",
	["targetpreview_hint"] = "点击以固定\n此目标。",
	["targetpreview_hint_empty"] = "此步骤当前没有激活的交谈或击杀目标。",
	["targetpreview_empty_name"] = "无目标",
	["popup_accept"] = "接受",
	["popup_decline"] = "拒绝",
	["actionbutton_bar_title"] = "拖动以移动动作按钮",
	["actionbutton_bar_title_locked"] = "动作按钮",
	["actionbutton_tooltip_talk"] = "选中 %s 并尝试为其标记绿色三角。",
	["actionbutton_tooltip_kill"] = "选中 %s 并尝试为其标记骷髅。",
	["actionbutton_tooltip_script"] = "执行当前步骤的脚本宏。",
	["actionbutton_tooltip_petaction"] = "使用建议的宠物动作。",
	["gearfinder_title"] = "装备查找器",
	["gearfinder_no_upgrade"] = "未找到升级",
	["gearfinder_load_guide"] = "加载指南",
	["gearfinder_suggested_dungeon"] = "推荐地下城：",
	["gearfinder_refresh"] = "点击刷新",
	["gearfinder_status_searching"] = "正在搜索升级%s",
	["gearfinder_status_searching_future"] = "正在搜索未来升级%s",
	["gearfinder_label_dungeon"] = "地下城：",
	["gearfinder_label_unknown"] = "未知",
	["gearfinder_label_inbags"] = "背包中：",
	["gearfinder_label_score"] = "评分：%d",
	["gearfinder_label_score_value"] = "%.1f 分",
	["gearfinder_label_equipped"] = "已装备",
	["gearfinder_label_empty"] = "空槽位",
	["gearfinder_upgrade_percent"] = "+%d%% 提升",
	["gearfinder_upgrade_percent_short"] = "%+.1f%%",
	["gearfinder_label_new_item"] = "新物品",
	["gearfinder_label_delta_score"] = "%+.1f 分",
	["gearfinder_label_best_gains"] = "最大提升：%s",
	["gearfinder_label_found"] = "最佳已找到：",
	["gearfinder_label_future"] = "未来：",
	["gearfinder_items_found"] = "找到 %d 件物品",
	["itemscore_ae_equip"] = "装备 %s",
	["itemscore_ae_over"] = " 替换 %s",
	["itemscore_ae_equip1"] = "替换此物品",
	["itemscore_ae_equip2"] = "装备此物品",
	["itemscore_ae_with"] = "用",
	["itemscore_ae_accept"] = "装备",
	["itemscore_ae_decline"] = "暂时不要",
	["itemscore_ae_report_tip"] = "按住 Shift 并点击可查看详细装备报告。\n已拒绝的物品将不再推荐。",
	["itemscore_ae_build"] = "天赋构建",
	["itemscore_questitem1"] = "任务需要此物品。",
	["itemscore_questitem2"] = "是否为当前任务步骤装备它？",
	["itemscore_questitem3"] = "是否重新装备之前的物品？",
	["notifcenter_gear_title"] = "装备顾问",
	["notifcenter_gear_text"] = "发现升级",
	["notifcenter_gear_text_sl"] = "发现 %d 个升级",
	["notifcenter_gear_text_pl"] = "发现 %d 个升级",
	["notifcenter_gear_equipped"] = "%s 已装备到 %s 槽位",
	["notifcenter_quest_text"] = "任务物品",
	["notifcenter_gen_popup_tooltip"] = "点击打开",
	["opt_itemscore_ae_clearednotupgrade"] = "已清空被拒绝的升级列表。",
	["opt_itemscore_warning"] = "编辑物品评分的属性权重。数值越高，表示该属性对你的专精越重要。",
	["opt_gear_title"] = "配置自动装备评分和升级检测。",
	["opt_gear_score_class"] = "职业：",
	["opt_gear_score_spec"] = "专精：",
	["opt_gear_sources"] = "装备查找来源",
	["opt_gear_sources_dungeons"] = "地下城",
	["opt_gear_sources_raids"] = "团队副本",
	["opt_quickscan_warning"] = "快速扫描模式：未收集物品链接。",
	["opt_actionbar_enable"] = "启用动作条",
	["opt_actionbar_enable_desc"] = "为当前步骤中的可交互目标显示一个可移动的动作条。",
	["opt_inlinebuttons_enable"] = "启用行内按钮",
	["opt_inlinebuttons_enable_desc"] = "直接在步骤行中显示交谈或击杀按钮。当行图标被禁用或动作条被禁用时，这些按钮会隐藏。",
	["opt_actionbar_onlywhenneeded"] = "仅在需要时显示",
	["opt_actionbar_onlywhenneeded_desc"] = "当当前步骤没有可交互按钮时隐藏动作条。",
	["opt_actionbar_locked"] = "锁定动作条位置",
	["opt_actionbar_locked_desc"] = "禁止拖动动作条。",
	["opt_actionbar_scale"] = "动作条缩放",
	["opt_actionbar_scale_desc"] = "动作条的缩放比例。",
	["opt_actionbar_size"] = "按钮大小",
	["opt_actionbar_size_desc"] = "动作条中每个按钮的大小。",
	["opt_actionbar_spacing"] = "按钮间距",
	["opt_actionbar_spacing_desc"] = "动作条按钮之间的间距。",
	["opt_actionbar_pinside"] = "停靠位置",
	["opt_actionbar_pinside_desc"] = "选择动作条应停靠在查看器的哪一侧。",
	["opt_actionbar_pinside_top"] = "上方",
	["opt_actionbar_pinside_bottom"] = "下方",
	["opt_actionbar_pinside_left"] = "左侧",
	["opt_actionbar_pinside_right"] = "右侧",
	["opt_actionbar_resetanchor"] = "重置动作条位置",
	["opt_actionbar_resetanchor_desc"] = "将动作条重置为默认停靠位置。",
	["opt_actionbar_markers"] = "启用目标标记",
	["opt_actionbar_markers_desc"] = "在可能的情况下，尝试为交谈和击杀目标设置团队标记。",
	["opt_targetpreview_header"] = "目标预览",
	["opt_targetpreview_intro"] = "为当前的交谈或击杀目标显示一个可移动的预览面板。",
	["opt_targetpreview_enable"] = "启用目标预览",
	["opt_targetpreview_enable_desc"] = "为当前步骤中的交谈和击杀目标显示一个可移动面板。",
	["opt_targetpreview_onlywhenneeded"] = "仅在相关时显示",
	["opt_targetpreview_onlywhenneeded_desc"] = "当当前步骤没有交谈或击杀目标时隐藏预览面板。",
	["opt_targetpreview_locked"] = "锁定预览位置",
	["opt_targetpreview_locked_desc"] = "禁止拖动目标预览面板。",
	["opt_targetpreview_scale"] = "预览缩放",
	["opt_targetpreview_scale_desc"] = "目标预览面板的缩放比例。",
	["opt_targetpreview_width"] = "预览宽度",
	["opt_targetpreview_width_desc"] = "目标预览面板的宽度。",
	["opt_targetpreview_height"] = "预览高度",
	["opt_targetpreview_height_desc"] = "目标预览面板的高度。",
	["opt_targetpreview_pinside"] = "停靠位置",
	["opt_targetpreview_pinside_desc"] = "选择目标预览应停靠在查看器的哪一侧。",
	["opt_targetpreview_mode"] = "预览模式",
	["opt_targetpreview_mode_desc"] = "选择预览应优先显示实时 3D 模型、信息卡片，或同时显示两者。",
	["opt_targetpreview_mode_hybrid"] = "混合",
	["opt_targetpreview_mode_model"] = "仅 3D",
	["opt_targetpreview_mode_card"] = "仅信息卡片",
	["opt_targetpreview_resetanchor"] = "重置预览位置",
	["opt_targetpreview_resetanchor_desc"] = "将目标预览面板重置为默认停靠位置。",
	["gold_app_no_goldguide"] = "打开金币指南（/zgold）以加载趋势数据。",
	["gold_app_no_goldguide_short"] = "打开 /zgold 以加载指南。",
	["gold_app_no_goldguide_tooltip"] = "打开金币指南窗口以从拍卖行扫描中初始化趋势数据。",
	["gold_app_no_scan_data"] = "当前价格未知。请扫描拍卖行。",
	["gold_app_no_scan_data_short"] = "当前价格未知。",
	["gold_app_no_scan_data_tooltip"] = "扫描拍卖行以收集当前价格。",
	["gold_app_no_servertrends"] = "没有趋势数据。请每天扫描以建立趋势。",
	["gold_app_no_servertrends_short"] = "没有趋势数据。",
	["gold_app_no_servertrends_tooltip"] = "每天扫描拍卖行以建立价格趋势。",
	["gold_app_old_scan_data"] = "当前价格数据已过期。请重新扫描。",
	["gold_app_old_scan_data_short"] = "当前价格数据已过期。",
	["gold_app_old_scan_data_tooltip"] = "重新扫描拍卖行以更新当前价格数据。",
	["gold_app_old_servertrends"] = "趋势数据已过期。请更频繁地扫描。",
	["gold_app_old_servertrends_short"] = "趋势数据已过期。",
	["gold_app_old_servertrends_tooltip"] = "更频繁地扫描拍卖行以保持趋势数据最新。",
	["gold_app_trend_tooltip"] = "基于最近服务器趋势和当前扫描价格的价格方向。",
	["gold_auctions_error_noresults"] = "未找到拍卖结果。",
	["gold_crafting_error_noprofessions"] = "没有制造类专业。",
	["gold_crafting_error_noresults"] = "未找到盈利的制造结果。",
	["gold_crafting_error_recipesnotcached"] = "配方数据尚未缓存。",
	["gold_expertmode_easylabel"] = "简单模式",
	["gold_expertmode_easytooltip"] = "显示更简单、更容易立即执行的建议。",
	["gold_expertmode_expertlabel"] = "专家模式",
	["gold_expertmode_experttooltip"] = "显示更详细、更高级的金币策略。",
	["gold_expertmode_generictooltip"] = "切换金币指南显示的策略类型。",
	["gold_farming_error_noitemtype"] = "未选择物品类型。",
	["gold_farming_error_noresults"] = "未找到符合这些条件的刷取结果。",
	["gold_gathering_error_all_noprofessions"] = "没有采集专业。",
	["gold_gathering_error_one_noresults"] = "未找到该专业的结果。",
	["gold_gathering_error_one_noskillin"] = "该区域所需技能不足。",
	["gold_gathering_error_one_noskillin_skills"] = "该区域所需技能：%s",
	["gold_gathering_error_one_nothing"] = "没有可显示的采集结果。",
	["gold_gathering_error_prof"] = "专业：%s",
	["gold_gathering_no_results"] = "未找到采集结果。",
	["gold_general_open_window1"] = "打开金币指南以",
	["gold_general_open_window2"] = "查看完整信息。",
	["stepgoal_arrive"] = "到达",
	["stepgoal_cast"] = "施放",
	["stepgoal_click"] = "点击",
	["stepgoal_fly"] = "飞行",
	["waypointaddon_disconnecting"] = "正在断开连接",
	["gb_opt_optimization"] = "优化",
	["gb_opt_desc_optimization"] = "影响性能的设置、箭头更新频率，以及未来的优化控制。",
	["opt_optimization_intro"] = "调整内置箭头的性能相关行为，并为未来巫妖王之怒专用优化选项预留空间。",
	["opt_optimization_arrow_header"] = "箭头性能",
	["opt_optimization_arrow_desc"] = "控制内置路径箭头的更新频率。较低频率可减少 CPU 占用，较高频率则更平滑。",
	["opt_arrow_refresh_rate"] = "箭头刷新频率",
	["opt_arrow_refresh_rate_desc"] = "控制内置路径箭头更新的频率。较低值可减少 CPU 占用，较高值可提升平滑度。",
	["opt_arrow_refresh_rate_20"] = "20 FPS（旧默认值）",
	["opt_arrow_refresh_rate_30"] = "30 FPS（推荐）",
	["opt_arrow_refresh_rate_60"] = "60 FPS（平滑）",
	["opt_arrow_refresh_rate_unlimited"] = "无限制（每帧）",
	["opt_optimization_internal_only"] = "此设置仅在启用内置路径指示器时影响内置路径箭头。",
	["opt_optimization_routing_header"] = "路线规划",
	["opt_optimization_routing_desc"] = "控制内置旅行系统计算和准备路线的积极程度。",
	["opt_pathfinding_speed"] = "路线计算预算",
	["opt_pathfinding_speed_desc"] = "控制 LibRover 在构建路线时每次更新执行的工作量。较低值可减少 CPU 峰值，较高值可更快完成重新计算。",
	["opt_pathfinding_speed_slow"] = "慢（最低 CPU）",
	["opt_pathfinding_speed_medium"] = "中",
	["opt_pathfinding_speed_fast"] = "快（更新最快）",
	["opt_travel_full_linking_startup"] = "启动时构建完整旅行链接",
	["opt_travel_full_linking_startup_desc"] = "登录时预先计算更多旅行链接。这样可以提升之后的路线响应速度，但会增加启动耗时。",
	["opt_optimization_memory_header"] = "内存与加载",
	["opt_optimization_memory_desc"] = "未来优化目标：通过更有选择地加载指南和步骤来降低初始内存占用。本次未实现。",
	["opt_optimization_diagnostics_header"] = "诊断",
	["opt_optimization_diagnostics_desc"] = "未来优化目标：提供轻量级 FPS 或内存诊断，用于分析卡顿和加载峰值。本次未实现。",
} end)
