if GetLocale()~="zhTW" then return end

ZygorGuidesViewer.LocaleFont = [[Fonts\bLEI00D.ttf]]

ZygorGuidesViewer_L("Main", "zhTW", function() return {
	["name"] = "|cffffff88Z|cffffee66y|cffffdd44g|cffffcc22o|cffffbb00r |cffffaa00Guides Viewer|r",
	["name_plain"] = "Zygor 指南檢視器",
	["desc"] = "Zygor Guides Viewer %s 的主要設定。|n",

	['welcome_guides'] = "已載入 %d 個指引。",

	["opt_guide"] = "選擇指引：",
	["opt_guide_steps"] = "步驟：%d",
	["opt_guide_author"] = "作者：%s",
	["opt_guide_next"] = "系列中的下一個：%s",

	["opt_report"] = "報告錯誤步驟",
	["opt_report_desc"] = "建立包含當前顯示步驟詳細資訊的錯誤報告。複製並貼上後傳送給指引作者。",

	["opt_visible"] = "顯示 Zygor Guides Viewer 視窗",
	["opt_visible_desc"] = "",
	["opt_hideincombat"] = "戰鬥中隱藏指引",
	["opt_hideincombat_desc"] = "當螢幕空間緊張時，在戰鬥中隱藏所有指引視窗。",

	["opt_opacitymain"] = "透明度",
	["opt_opacitymain_desc"] = "主視窗透明度。",
	["opt_framescale"] = "縮放",
	["opt_framescale_desc"] = "可以按你的偏好調整視窗大小。",
	["opt_fontsize"] = "文字縮放",
	["opt_fontsize_desc"] = "設定首選文字大小。注意視窗縮放也會影響此項。",
	["opt_fontsecsize"] = "次要文字縮放",
	["opt_fontsecsize_desc"] = "設定次要文字大小，用於顯示額外描述和備註。",
	["opt_backcolor"] = "背景顏色",
	["opt_backcolor_desc"] = "視窗背景顏色。",

	["opt_group_window"] = "視窗功能",
	["opt_miniresizeup"] = "向上擴展",
	["opt_miniresizeup_desc"] = "將視窗翻轉，使其向上而不是向下擴展。適合放在螢幕底部時使用。",
	["opt_opacitymini"] = "背景透明度",
	["opt_opacitymini_desc"] = "步驟視窗背景透明度。",

	["opt_showcountsteps"] = "顯示步驟：",
	["opt_showcountsteps_desc"] = "顯示步驟數量。\n|cffffffaa全部|r 會在可捲動清單中顯示所有步驟。\n|cffffffaa1-5|r 會將當前步驟置頂，並自動調整視窗大小，僅顯示後續若干步驟。",
	["opt_showcountsteps_all"] = "全部",

	["opt_group_map"] = "路徑點",
	["opt_group_map_desc"] = "這些設定控制 Zygor Guides Viewer 與地圖類插件的互動方式。",
	["opt_group_map_waypointing"] = "路徑點插件",
	["opt_group_map_waypointing_desc"] = "選擇你希望用於 Zygor Guides Viewer 路徑點處理的插件。",
	['opt_group_map_hidearrowwithguide'] = "關閉視窗時隱藏箭頭",
	['opt_group_map_hidearrowwithguide_desc'] = "啟用後，箭頭顯示將跟隨指引視窗可見性。\n若希望隱藏指引時箭頭仍顯示，請不要勾選。",
	["opt_group_addons_internal"] = "內建路徑點",
	["opt_group_addons_builtin"] = "內建路徑點",
	["opt_group_addons_tomtom"] = "TomTom",
	["opt_group_addons_carbonite"] = "Carbonite",
	["opt_group_addons_cart2"] = "Cartographer 2",
	["opt_group_addons_cart3"] = "Cartographer 3",
	["opt_group_addons_metamap"] = "MetaMap",
	["opt_group_addons_none"] = "無",
	["opt_debug"] = "除錯",
	["opt_debug_desc"] = "顯示除錯資訊。",
	["opt_debugging"] = "除錯設定",
	["opt_debugging_desc"] = "除錯選項。",

	["opt_autoskip"] = "自動前進",
	["opt_autoskip_desc"] = "當當前步驟條件全部完成時自動跳到下一步。部分條件過於複雜的步驟仍可能需要手動跳過。",

	["opt_goalicons"] = "顯示步驟行圖示",
	["opt_goalicons_desc"] = "顯示反映完成狀態的圖示。",
	["opt_goalcolorize"] = "為已完成步驟行著色",
	["opt_goalcolorize_desc"] = "完成步驟行時，將整行著為綠色。",
	["opt_goalbackprogress"] = "按完成百分比套用顏色",
	["opt_goalbackprogress_desc"] = "以未完成與完成顏色之間的過渡色顯示部分完成進度。|n關閉後，目標只會顯示“未完成”或“完成”兩種顏色。",

	["opt_group_step"] = "步驟目標",

	["opt_goalbackcolor_desc"] = "完成顏色：",
	["opt_goalbackgrounds"] = "背景著色",
	["opt_goalbackgrounds_desc"] = "為步驟行背景著色以反映完成狀態。",
	["opt_goalbackcomplete"] = "完成",
	["opt_goalbackcomplete_desc"] = "此顏色用於表示已完成目標。",
	["opt_goalbackincomplete"] = "未完成",
	["opt_goalbackincomplete_desc"] = "此顏色用於表示未完成目標。",
	["opt_goalbackimpossible"] = "無法完成",
	["opt_goalbackimpossible_desc"] = "此顏色用於表示當前無法完成的目標。",

	['opt_tooltipsbelow'] = "在行內顯示額外資訊",
	['opt_tooltipsbelow_desc'] = "某些步驟行的額外資訊可顯示為行內文字，或在滑鼠懸停時以提示框顯示。",

	["opt_flash_desc"] = "進度提醒：",
	["opt_goalcompletionflash"] = "目標完成時閃爍",
	["opt_goalcompletionflash_desc"] = "當單一目標完成時使用視覺“閃爍”提示。",
	["opt_goalupdateflash"] = "目標進度變化時閃爍",
	["opt_goalupdateflash_desc"] = "當單一目標有進度時使用視覺“閃爍”提示。",
	["opt_flashborder"] = "步驟完成時閃爍視窗",
	["opt_flashborder_desc"] = "每當一個步驟完成時閃爍整個視窗。",

	["opt_group_display"] = "顯示",
	["opt_group_display_desc"] = "設定你希望指引如何顯示。",

	["opt_group_data"] = "內建指引儲存",
	["opt_group_data_desc"] = "Zygor Guides Viewer 可以在內部儲存商業指引（由於暴雪政策，這些內容不能以獨立插件形式分發）。",
	["opt_group_data_guide"] = "內部儲存的指引：",
	["opt_group_data_guide_desc"] = "從列表中選擇一個內建指引進行編輯或刪除。此列表不會顯示作為獨立插件載入的指引。",
	["opt_group_data_del"] = "刪除指引",
	["opt_group_data_del_desc"] = "從內部儲存中刪除所選指引。",
	["opt_group_data_edit"] = "編輯指引",
	["opt_group_data_edit_desc"] = "將所選指引載入到下方編輯器視窗以進行手動修改。",
	["opt_group_data_entry"] = "指引資料：",
	["opt_group_data_entry_desc"] = "在此貼上新指引（請記得將步驟包裹在：|nguide 指引標題|nsteps...|nsteps...|nend\n）；注意貼上並解析較大指引（>30kB）可能需要幾秒鐘。",

	['opt_windowlocked'] = "鎖定視窗",
	['opt_windowlocked_desc'] = "鎖定視窗，使其不再回應滑鼠交互。\n僅按鈕仍可使用。",
	['opt_hideborder'] = "自動隱藏邊框",
	['opt_hideborder_desc'] = "當滑鼠離開視窗時自動隱藏視窗邊框和按鈕。\n將滑鼠懸停在視窗標題片刻可再次顯示。",

	['opt_skin'] = "視窗外觀顏色",
	['opt_skin_desc'] = "選擇視窗裝飾顏色以匹配你的介面。",
	['opt_skin_violet'] = "|cffee55ff紫色",
	['opt_skin_green'] = "|cff88ff88綠色",
	['opt_skin_blue'] = "|cff99aaff藍色",
	['opt_skin_orange'] = "|cffffbb00橘色",
	["opt_skinpanel_title"] = "外觀",
	["opt_skinpanel_desc"] = "選擇指南檢視器的視覺主題。",
	["opt_skinpanel_intro"] = "先選擇檢視器的整體外觀，再細調大小、透明度與文字。Remaster 仍是推薦的預設皮膚，而 Retail 則提供更接近暴雪原生介面的風格。",
	["opt_skinpanel_skin"] = "皮膚",
	["opt_skinpanel_skin_desc"] = "選擇皮膚及其色彩變體。",
	["opt_skinpanel_appearance_header"] = "顯示",
	["opt_skinpanel_appearance_desc"] = "調整檢視器縮放、文字大小與框架透明度。",
	["opt_skinpanel_colors_header"] = "顏色",
	["opt_skinpanel_colors_desc"] = "調整所選皮膚變體的框架背景強度。",
	["opt_skinpanel_advanced_header"] = "進階",
	["opt_skinpanel_advanced_desc"] = "影響框架配置與步驟顯示方式的低頻顯示選項。",

	['opt_backopacity'] = "背景透明度",
	['opt_backopacity_desc'] = "視窗背景透明度。",

	["report_title"] = "按 Ctrl+C 複製此報告。|n然後將其傳送給 |cffffffff%s|r 的作者，|n地址：|cffffffff%s|r。",
	["report_notitle"] = "|cffff8888（未命名指引？）|r",
	["report_noauthor"] = "|cffff8888（無可用地址）|r",

	["opt_mapbutton"] = "顯示小地圖按鈕",
	["opt_mapbutton_desc"] = "在小地圖旁顯示 Zygor Guides Viewer 按鈕",

	["minimap_tooltip"] = "|cffeedd99左鍵|r 切換指引視窗|n|cffeedd99右鍵|r 開啟設定|n",

	["waypointaddon_set"] = "已選擇路徑點插件：%s",
	["waypointaddon_connecting"] = "正在連接路徑點插件：%s",
	["waypointaddon_connected"] = "已成功連接到 %s。",
	["waypointaddon_fail"] = "連接 %s 失敗。",
	['waypoint_step'] = "步驟 %s",

	["checkmap"] = "請查看地圖。",

	["initialized"] = "初始化完成。",

	["miniframe_notloaded"] = "未載入任何升級指引。|n|n請前往 http://zygorguides.com 購買 Zygor 的 1-80 升級指引，或載入第三方指引。|n|n如果你確定已經安裝了指引，請聯絡其作者獲取安裝排錯協助。",
	["miniframe_notselected"] = "當前未選擇任何指引。\n請點擊上方閃爍按鈕以選擇一個指引。",
	["miniframe_loading"] = "正在載入指引：%d%%",

	['frame_locked'] = "視窗已鎖定",
	['frame_unlock'] = "|cffeedd99左鍵|r 解鎖",
	['frame_unlocked'] = "視窗未鎖定",
	['frame_lock'] = "|cffeedd99左鍵|r 鎖定",
	['frame_settings'] = "設定",
	['frame_settings1'] = "|cffeedd99左鍵|r 開啟選單",
	['frame_settings2'] = "|cffeedd99右鍵|r 開啟選項",
	['frame_minimized'] = "顯示 |cffffffff%d|r 個步驟",
	['frame_maximized'] = "顯示全部步驟",
	['frame_minimize'] = "|cffeedd99左鍵|r 僅顯示 |cffffffff%d|r 個",
	['frame_minright'] = "|cffeedd99右鍵|r 設定顯示步驟數",
	['frame_maximize'] = "|cffeedd99左鍵|r 顯示全部",
	['frame_stepnav_prev'] = "上一步",
	['frame_stepnav_prev_click'] = "|cffeedd99左鍵|r：後退",
	['frame_stepnav_prev_right'] = "|cffeedd99右鍵|r：後退",
	['frame_stepnav_next'] = "下一步",
	['frame_stepnav_next_click'] = "|cffeedd99左鍵|r：前進",
	['frame_stepnav_next_right'] = "|cffeedd99右鍵|r：快速前進",
	['frame_section'] = "當前指引",
	['frame_section_click'] = "|cffeedd99點擊|r 選擇",

	['tooltip_tip'] = "|cff99ff00%s|r",
	['tooltip_waypoint'] = "|cffeedd99點擊|r|cff00ff00 設定路徑點：|cffffaa00%s|r",
	['tooltip_waypoint_coords'] = "位置：|cffffaa00%s|r",

	["message_errorloading_full"] = "載入指引 |cffaaffaa%s|r 時發生 |cffff4444錯誤|r\n第 %d 行：%s\n錯誤：%s",
	["message_errorloading_brief"] = "載入指引 |cffaaffaa%s|r 時發生 |cffff4444錯誤|r",
	["message_loadedguide"] = "已啟用指引：|cffaaffaa%s|r",
	["message_missingguide"] = "缺少指引：|cffaaffaa%s|r",
	["title_noguide"] = "Zygor Guides Viewer（未載入指引）",

	['step_num'] = "|cffaaaaaa%s|cff888888.|r ",
	['step_level'] = "|cffaaccaa等級：|cffcceecc%s|cffaaccaa|r ",

	["questtitle"] = "“%s”",
	["questtitle_part"] = "“%s”（第 %s 部分）",
	["coords"] = "%d,%d",
	["map_coords"] = "%s %d,%d",

	["stepgoal_home"] = "將爐石地點設定為 %s",
	["stepgoal_flightpath"] = "獲取 %s 飛行點",

	["stepgoal_accept"] = "接受 %s",
	["stepgoal_turn in"] = "交付 %s",
	["stepgoal_talk to"] = "與 %s 對話",
	["stepgoal_kill"] = "擊殺 %s",
	["stepgoal_kill #"] = "擊殺 %s %s",
	["stepgoal_goal"] = "%s",
	["stepgoal_goal #"] = "%s %s",
	["stepgoal_get"] = "獲得 %s",
	["stepgoal_get #"] = "獲得 %s %s",
	["stepgoal_ding"] = "你現在應為 %s 級。|n    若不是，請稍微刷怪直到達到該等級。",
	["stepgoal_go to"] = "前往 %s",
	["stepgoal_also at"] = "也在 %s",
	["stepgoal_hearth to"] = "爐石返回 %s",
	["stepgoal_collect"] = "收集 %s",
	["stepgoal_collect #"] = "收集 %s %s",
	["stepgoal_buy"] = "購買 %s %s",
	["stepgoal_fpath"] = "獲取 %s 飛行點",
	["stepgoal_use"] = "使用 %s",
	["stepgoal_home"] = "將 %s 設為你的爐石地點",
	["stepgoal_petaction"] = "使用寵物技能 %s",
	["stepgoal_havebuff"] = "獲得增益/減益“%s”",
	["stepgoal_nobuff"] = "失去增益/減益“%s”",
	["stepgoal_invehicle"] = "進入載具",
	["stepgoal_outvehicle"] = "離開載具",
	["stepgoal_equipped"] = "裝備 %s",
	["stepgoal_at_suff"] = "（%s）",

	["completion_collect"] = "(%s/%s)",
	["completion_goal"] = "(%s/%s)",
	["completion_ding"] = "(%s%%)",
	["completion_done"] = "(完成)",
	["completion_rep"] = "(%s)",

	["step_req"] = "此步驟僅對以下條件有效：%s",

	["map_highlight"] = "高亮顯示",

	["stepreq"] = "步驟職業/種族要求：",
	["stepreqor"] = " 或 ",

	["opt_do_searchforgoal"] = "尋找可完成目標",
	["searching_for_goal_success"] = "已找到一個可完成目標：%s。它可能是你在此指引中的合適起點。",
	["searching_for_goal_failed"] = "未找到可完成目標。請嘗試其他指引或章節、先接一些任務，或從章節開頭再次搜尋（搜尋只會向前進行）。",


	["going"] = "%d%% 進行中：%s",
	["opt_stepnumber"] = "顯示步驟編號",
	["opt_stepnumber_desc"] = "為每個步驟顯示步驟編號和建議等級。\n關閉後可節省一些螢幕空間。",
	["opt_hidestepborders"] = "隱藏邊框",
	["opt_hidestepborders_desc"] = "隱藏步驟周圍的圖形邊框。",
	["opt_stepbackopacity"] = "背景透明度",
	["opt_stepbackopacity_desc"] = "步驟視窗背景的透明度。\n背景顏色會反映完成狀態與淡出效果。",
	["opt_goalbackprogressing"] = "進行中",
	["opt_goalbackprogressing_desc"] = "目標進行到約 50% 時使用的顏色。",
	["opt_progressbackcolor_desc"] = "進度顏色：",
	["opt_goalbackaux"] = "輔助",
	["opt_goalbackaux_desc"] = "輔助目標使用的顏色。",
	["opt_goalbackobsolete"] = "過時",
	["opt_goalbackobsolete_desc"] = "過時目標使用的顏色。",
	["opt_resetwindow"] = "重設視窗",
	["opt_resetwindow_desc"] = "如果視窗跑到螢幕外，此按鈕會將它重設回中央。",
	["opt_trackchains"] = "追蹤任務鏈",
	["opt_trackchains_desc"] = "如果前置任務未完成，則將接任務步驟標記為不可用。\n\n任務鏈資料庫也包含「寬鬆鏈條」資料，也就是任務彼此相關但不一定嚴格要求順序，因此有時會把實際上仍可接的任務顯示為不可用。",
	["opt_guidesinhistory"] = "最近指南數量",
	["opt_guidesinhistory_desc"] = "顯示這麼多最近使用過的指南。",
	["opt_skin_remaster"] = "|cffc7d9ffRemaster（預設）",
	["opt_group_progress"] = "動態進度",
	["opt_group_progress_desc"] = "為了讓升級路線更有效率，插件會動態跳過對你目前等級收益已不大的任務。",
	["opt_levelsahead"] = "允許超前等級",
	["opt_levelsahead_desc"] = "此設定決定你可以比指南高出多少級。\n設為 0 時，通常會跳過所有低於你目前等級的任務（除非它們有後續）。\n設為 1 或更高時，只會跳過比你低超過該數值的任務。",
	["opt_showobsolete"] = "標記過時步驟",
	["opt_showobsolete_desc"] = "用灰色背景標記過時步驟。\n當步驟等級對你來說過低時，它會被視為過時。",
	["opt_skipobsolete"] = "跳過過時步驟",
	["opt_skipobsolete_desc"] = "自動跳過過時步驟。",
	["opt_skipauxsteps"] = "跳過輔助步驟",
	["opt_skipauxsteps_desc"] = "如果一個交通或過渡步驟之後只剩已完成或已過時的步驟，則自動跳過該輔助步驟。\n這樣可避免你走很遠後卻發現下個步驟早就做過了。",
	["opt_skipflightsteps"] = "視為已知飛行點",
	["opt_skipflightsteps_desc"] = "假定你會自己學習飛行路線，並自動將學習飛行點的步驟標記為完成。\n\n在從指南中途開始時很有用，正常遊玩時則沒那麼必要。",
	["opt_skipimpossible"] = "跳過不可能步驟",
	["opt_skipimpossible_desc"] = "自動跳過不可能完成的步驟，以免顯示來自你刻意跳過任務的目標。",
	["opt_group_progress_bottomdesc"] = "動態進度的運作方式是：當你超過指南等級的幅度大於上方設定值時，任務會被標記為「過時」。任務鏈只有在整條鏈都過時時才會標記為過時。\n\n對新手玩家來說，這有助於智慧地跳過低等級內容，只停留在仍然有價值的任務鏈上。\n\n對熟練玩家來說，這能避免指南在你升級過快時繼續拖著你去做低等級任務。",
	["opt_group_mapinternal"] = "內建路徑點",
	["opt_arrowmeters"] = "公制單位",
	["opt_arrowmeters_desc"] = "使用公尺與公里，而不是碼與英里。",
	["opt_arrowfreeze"] = "箭頭忽略滑鼠",
	["opt_arrowfreeze_desc"] = "讓箭頭忽略滑鼠操作。關閉後可拖曳它。",
	["opt_arrowcam"] = "箭頭跟隨鏡頭",
	["opt_arrowcam_desc"] = "依鏡頭方向顯示箭頭。如果關閉，箭頭將根據角色朝向。\n\n注意：在鏡頭模式下，點擊移動時箭頭可能表現異常。",
	["opt_arrowcolordir"] = "依方向著色",
	["opt_arrowcolordir_desc"] = "當箭頭指向正確方向時，將它變成綠色。\n\n如果你只想在接近目標時才顯示綠色，請關閉此選項。",
	["opt_arrowscale"] = "箭頭縮放",
	["opt_arrowscale_desc"] = "箭頭的大小。",
	["opt_arrowfontsize"] = "箭頭文字大小",
	["opt_arrowfontsize_desc"] = "箭頭視窗中文字的大小。",
	["opt_minimapzoom"] = "自動縮放小地圖",
	["opt_minimapzoom_desc"] = "設定路徑點時自動放大小地圖，之後再恢復原先縮放。",
	["opt_foglight"] = "探索地圖迷霧",
	["opt_foglight_desc"] = "在地圖上顯示尚未探索的區域。",
	["opt_targetpreview_growth"] = "成長方向",
	["opt_targetpreview_growth_desc"] = "選擇固定後的目標預覽應跟隨檢視器的縮放方向、向上成長，或向下成長。",
	["opt_targetpreview_growth_auto"] = "跟隨檢視器",
	["opt_targetpreview_growth_up"] = "向上成長",
	["opt_targetpreview_growth_down"] = "向下成長",
	["opt_group_gold"] = "金幣指南",
	["opt_group_gold_desc"] = "這些設定控制金幣路線步驟與資源點的顯示方式。",
	["opt_gold_detectiondist"] = "偵測距離",
	["opt_gold_detectiondist_desc"] = "決定在多遠範圍內顯示附近的金幣指南點位。",
	["opt_gold_reqmode"] = "需求模式",
	["opt_gold_reqmode_desc"] = "選擇應該考慮哪些類型的點位。",
	["opt_gold_reqmode_all"] = "全部",
	["opt_gold_reqmode_current"] = "目前專業等級",
	["opt_gold_reqmode_future"] = "目前專業，但忽略等級",
	["gold_missing_noguidesloaded"] = "未載入金幣指南。",
	["gold_missing_nospotsinrange"] = "範圍內沒有可用點位。",
	["gold_header_ore"] = "礦點：",
	["gold_header_herb"] = "草藥：",
	["gold_header_skin"] = "剝皮目標：",
	["gold_header_drop"] = "|cffffdddd%s|r 掉落：",
	["opt_group_convenience"] = "便利功能",
	["opt_group_convenience_desc"] = "各種實用的輔助選項。",
	["opt_autoaccept"] = "自動接任務",
	["opt_autoaccept_desc"] = "自動接受提供給你的任務。",
	["opt_autoturnin"] = "自動交任務",
	["opt_autoturnin_desc"] = "自動交付已完成的任務。",
	["opt_fixblizzardautoaccept"] = "修正暴雪自動接任務",
	["opt_fixblizzardautoaccept_desc"] = "當啟用暴雪的「自動接受任務」功能時，仍然正確處理「接受」與「已接受」步驟的完成狀態。",
	["opt_audiocues"] = "音效提示",
	["opt_audiocues_desc"] = "在步驟進度變化時播放提示音。",
	["opt_analyzereps"] = "分析聲望",
	["opt_analyzereps_desc"] = "分析你目前的聲望，並將無效的聲望步驟標記為過時。",
	["opt_mapcoords"] = "顯示地圖座標",
	["opt_mapcoords_desc"] = "在地圖視窗中顯示玩家與滑鼠座標。",
	["stepgoal_rep"] = "與 %s 達到%s",
	["stepgoal_achieve"] = "完成成就%s",
	["stepgoal_achievesub"] = "完成成就%s的子目標%s",
	["stepgoal_skill"] = "將 %s 提升到 %s",
	["stepgoal_skillmax"] = "將 %s 提升到最大 %s",
	["stepgoal_learn"] = "學習 %s",
	["stepgoal_or"] = "  - ? -",
	["stepgoalshort_complete"] = "完成",
	["stepgoalshort_incomplete"] = "未完成",
	["stepgoalshort_questgoal"] = "(%d/%d)",
	["stepgoalshort_level"] = "(%d%%)",
	["waypointaddon_detecting"] = "正在嘗試自動偵測路徑點插件……",
	["waypointaddon_disconnected"] = "已從 |cffddeeff%s|r 中斷連線。",
	["pointer_corpselabel1"] = "曾經的你",
	["pointer_corpselabel2"] = "學會逃跑的人……",
	["pointer_corpselabel3"] = "吃不下這麼多吧？",
	["pointer_corpselabel4"] = "踢桶大師在這邊",
	["pointer_corpselabel5"] = "盡量別去想修理費。",
	["req_not"] = "? %s",
	["haman$"] = "hamans",
	["(%a)man$"] = "%1men",

	["binding_togglewindow"] = "顯示指引視窗",
	["binding_prev"] = "上一步",
	["binding_next"] = "下一步",
	["menu_last"] = "最近使用的指引：",
	["menu_last_entry"] = "%s |cffaaaaaa步驟|r %d",
	["gb_window_title"] = "指南瀏覽器",
	["gb_addon_title"] = "Zygor Guides Viewer Remastered",
	["gb_root"] = "首頁",
	["gb_search"] = "搜尋",
	["gb_folders"] = "資料夾",
	["gb_guides"] = "指南",
	["gb_load_guide"] = "載入指南",
	["gb_open_legacy"] = "開啟舊版選擇器",
	["gb_path_format"] = "路徑：%s",
	["gb_select_guide"] = "選擇一個指南",
	["gb_select_guide_from_list"] = "從清單中選擇一個指南。",
	["gb_select_settings_page"] = "選擇一個設定頁面",
	["gb_all_guides"] = "所有指南",
	["gb_other"] = "其他",
	["gb_unknown"] = "未知",
	["gb_none"] = "無",
	["gb_folder_format"] = "資料夾：%s",
	["gb_progress_format"] = "進度：%d%%",
	["gb_guides_count_format"] = "%d 個指南",
	["gb_current_meta_format"] = "步驟 %d / %d  |  %s",
	["gb_detail_meta_format"] = "步驟：%d\n作者：%s\n下一個：%s",
	["gb_tab_home"] = "首頁",
	["gb_tab_featured"] = "推薦",
	["gb_tab_current"] = "目前",
	["gb_tab_recent"] = "最近",
	["gb_tab_options"] = "設定",
	["gb_cat_leveling"] = "升級",
	["gb_cat_dungeons"] = "副本",
	["gb_cat_daily"] = "每日",
	["gb_cat_events"] = "活動",
	["gb_cat_reputations"] = "聲望",
	["gb_cat_gold"] = "金幣",
	["gb_cat_professions"] = "專業",
	["gb_cat_petsmounts"] = "寵物與坐騎",
	["gb_cat_titles"] = "頭銜",
	["gb_cat_achievements"] = "成就",
	["gb_cat_misc"] = "雜項",
	["gb_cat_favorites"] = "最愛",
	["gb_opt_guides"] = "指南",
	["gb_opt_desc_guides"] = "指南選擇、目前指南資訊與核心控制。",
	["gb_opt_stepdisplay"] = "步驟顯示",
	["gb_opt_desc_stepdisplay"] = "檢視器外觀、框架配置、外觀/字型，以及步驟與目標顯示控制。",
	["gb_opt_progress"] = "進度",
	["gb_opt_desc_progress"] = "步驟推進行為、跳過規則與完成流程。",
	["gb_opt_travel"] = "旅行系統",
	["gb_opt_desc_travel"] = "路徑點提供者選擇與旅行系統行為。",
	["gb_opt_map"] = "地圖與路徑點",
	["gb_opt_desc_map"] = "箭頭樣式、小地圖/地圖標記與路徑點外觀。",
	["gb_opt_notifications"] = "通知",
	["gb_opt_desc_notifications"] = "進度/完成時的閃爍與提示。",
	["gb_opt_actionbuttons"] = "動作按鈕",
	["gb_opt_desc_actionbuttons"] = "可點擊步驟/目標互動的顯示行為。",
	["gb_opt_convenience"] = "任務",
	["gb_opt_desc_convenience"] = "自動接取/交回與便利功能。",
	["gb_opt_accessibility"] = "無障礙",
	["gb_opt_desc_accessibility"] = "提升色彩可見性與可讀性的選項。",
	["gb_opt_profile"] = "設定檔",
	["gb_opt_desc_profile"] = "角色/全域設定檔管理以及複製/重設工具。",
	["gb_opt_about"] = "關於",
	["gb_opt_desc_about"] = "版本、支援與診斷/錯誤回報工具。",
	["gb_opt_advanced"] = "進階",
	["gb_opt_desc_advanced"] = "除錯工具、診斷與開發者控制。",
	["gb_opt_general"] = "一般",
	["gb_opt_desc_general"] = "一般設定。",
	["gb_title_viewer"] = "檢視器",
	["gb_options_viewer_desc"] = "檢視器核心行為、指南載入與基本插件控制。",
	["gb_hint_search_settings"] = "提示：\n使用左側搜尋可快速找到設定頁面。",
	["gb_hint_options_filter"] = "提示：\n左側搜尋會篩選設定頁面。\n使用「開啟完整選項」查看完整 Blizzard 面板。",
	["gb_empty_no_guides_search"] = "沒有指南符合此搜尋。",
	["gb_empty_no_guides_category"] = "此分類中沒有指南。",
	["gb_empty_no_current_guide"] = "目前沒有載入指南。",
	["gb_empty_no_current_guide_short"] = "目前沒有載入指南",
	["gb_empty_no_recent_guides"] = "目前還沒有最近使用的指南。",
	["gb_empty_no_featured_match"] = "沒有推薦項目符合此篩選。",
	["gb_empty_no_featured_suggestions"] = "沒有推薦建議",
	["gb_empty_no_favorites"] = "目前還沒有最愛指南。",
	["gb_no_guide_selected"] = "未選擇指南",
	["gb_action_clear_search"] = "清除搜尋",
	["gb_action_show_all_categories"] = "顯示所有分類",
	["gb_action_go_home"] = "前往首頁",
	["gb_action_open_home"] = "開啟首頁",
	["gb_action_reset_snoozed"] = "重設已隱藏建議",
	["gb_action_clear_search_restore"] = "清除搜尋以恢復建議",
	["gb_action_reset_snoozed_restore"] = "重設已隱藏建議以恢復推薦",
	["gb_action_try_home"] = "試試首頁以瀏覽所有分類",
	["gb_action_browse_all_from_home"] = "從首頁瀏覽所有指南",
	["gb_action_back_to_guides"] = "返回指南",
	["gb_action_open_full_options"] = "開啟完整選項",
	["gb_action_go_current_folder"] = "前往目前指南資料夾",
	["gb_action_resume"] = "繼續",
	["gb_action_restart"] = "重新開始",
	["gb_nav_navigation"] = "導覽",
	["gb_nav_back"] = "返回",
	["gb_nav_reset_to_root"] = "重設到分類根目錄",
	["gb_featured_bucket_next"] = "下一步",
	["gb_featured_bucket_progress"] = "進行中",
	["gb_featured_bucket_level"] = "適合你目前等級",
	["gb_featured_bucket_featured"] = "推薦路線",
	["gb_featured_confidence_strong"] = "高",
	["gb_featured_confidence_good"] = "良好",
	["gb_featured_confidence_fallback"] = "備用",
	["gb_roadmap"] = "路線圖",
	["gb_roadmap_bucket_format"] = "%s 路線圖",
	["gb_bucket_preview_next_with_title"] = "繼續你的路線：%s",
	["gb_bucket_preview_next"] = "繼續目前路線",
	["gb_bucket_preview_progress_with_title"] = "繼續：%s",
	["gb_bucket_preview_progress"] = "繼續進行中的指南",
	["gb_bucket_preview_level_with_title"] = "開始符合等級的路線：%s",
	["gb_bucket_preview_level"] = "開始符合目前等級的指南",
	["gb_bucket_preview_featured_with_title"] = "可選路線：%s",
	["gb_bucket_preview_featured"] = "可選路線與額外內容",
	["gb_meta_action"] = "動作",
	["gb_meta_suggestion"] = "建議",
	["gb_meta_suggested"] = "已建議",
	["gb_meta_current"] = "目前",
	["gb_meta_recommended"] = "推薦",
	["gb_meta_other_useful_option"] = "其他有用選項",
	["gb_meta_current_selection"] = "目前選擇",
	["gb_meta_suggestions_snoozed"] = "建議可能已被隱藏",
	["gb_meta_restore_recommendations"] = "恢復推薦",
	["gb_meta_filter_no_matches"] = "篩選沒有符合項目",
	["gb_meta_see_full_recommendations"] = "查看完整推薦",
	["gb_meta_no_bucket_suggestions"] = "此區塊中沒有建議",
	["gb_meta_full_category_access"] = "查看完整分類",
	["gb_meta_suggested_from"] = "建議來源：%s",
	["gb_meta_confidence"] = "信心：%s",
	["gb_meta_why_prefix"] = "原因：",
	["gb_meta_gain_prefix"] = "收益：",
	["gb_reason_recently_used"] = "最近使用",
	["gb_reason_incomplete"] = "未完成",
	["gb_reason_your_level_range"] = "符合你的等級範圍",
	["gb_reason_near_your_level"] = "接近你的等級",
	["gb_reason_your_class"] = "符合你的職業",
	["gb_reason_your_race"] = "符合你的種族",
	["gb_reason_your_profession"] = "符合你的專業",
	["gb_reason_favorite"] = "最愛",
	["gb_reason_current_chain"] = "目前路線",
	["gb_reason_chain_step_format"] = "路線步驟 +%d",
	["gb_reason_inferred_continuation"] = "推測的後續路線",
	["gb_reason_chapter_continuation"] = "章節延續",
	["gb_tooltip_featured_controls"] = "推薦建議控制說明",
	["gb_tooltip_featured_click"] = "點擊 X：隱藏 24 小時",
	["gb_tooltip_featured_shift_click"] = "Shift+點擊 X：本次工作階段中隱藏",
	["gb_tooltip_featured_restore"] = "按 R 或在選項中重設即可恢復。",
	["gb_tooltip_snooze"] = "隱藏建議",
	["gb_tooltip_snooze_click"] = "點擊：隱藏 24 小時",
	["gb_tooltip_snooze_shift_click"] = "Shift+點擊：本次工作階段中隱藏",
	["gb_tooltip_why_prefix"] = "原因：",
	["gb_tooltip_gain_prefix"] = "收益：",
	["gb_tooltip_confidence_prefix"] = "信心：",
	["gb_tooltip_chain_prefix"] = "路線：",
	["gb_tooltip_fallback_recommendation"] = "備用推薦",
	["gb_current_guide"] = "目前指南",
	["gb_options_fallback_embed_unavailable"] = "內嵌選項不可用。再次點擊「設定」以開啟 Blizzard 介面選項。",
	["gb_options_fallback_missing_widgets"] = "內嵌選項不可用。缺少 AceGUI 嵌入元件。",
	["gb_options_fallback_render_error"] = "無法渲染內嵌選項：%s",
	["opt_legacyguideddropdown"] = "舊版指南下拉選單",
	["opt_featured_header"] = "精選建議",
	["opt_featured_enablefallback"] = "啟用備用建議",
	["opt_featured_enablefallback_desc"] = "當精選分類沒有直接匹配時，顯示一些有用的備用指南。",
	["opt_featured_hiderecentcompleted"] = "隱藏最近完成的指南",
	["opt_featured_hiderecentcompleted_desc"] = "將剛完成不久的指南從智慧精選推薦中隱藏。",
	["opt_featured_showconfidence"] = "顯示信心標籤",
	["opt_featured_showconfidence_desc"] = "在精選項目中顯示 Strong/Good/Fallback 信心標記。",
	["opt_featured_resethidden"] = "重設已隱藏建議",
	["opt_featured_resethidden_desc"] = "恢復用關閉按鈕隱藏的精選建議。",
	["opt_disablerouteloopstacking"] = "停用路線/循環堆疊",
	["opt_disablerouteloopstacking_desc"] = "避免路線與循環段落堆疊到同一個精選分類中。",
	["opt_routeantminimapmode"] = "小地圖路線軌跡",
	["opt_routeantminimapmode_desc"] = "選擇要在小地圖上顯示多少行進螞蟻路線。",
	["opt_routeantminimapmode_local"] = "目前路段",
	["opt_routeantminimapmode_local_desc"] = "只顯示目前附近的路段：上一個點、目前點與下一個點。",
	["opt_routeantminimapmode_all"] = "完整路線",
	["opt_routeantminimapmode_all_desc"] = "在小地圖上顯示整條路線或迴圈。",
	["opt_routeantminimapmode_none"] = "只顯示路點",
	["opt_routeantminimapmode_none_desc"] = "隱藏小地圖上的行進螞蟻，只顯示目前的主要路點。",
	["opt_routeantdensity"] = "路線軌跡密度",
	["opt_routeantdensity_desc"] = "調整路點之間行進螞蟻的密集程度。1 最稀疏，5 為目前預設值，9 為最高密度。",
	["opt_accessibility_intro"] = "調整顏色可見性與文字清晰度相關的視覺輔助選項。",
	["opt_colorblindmode"] = "色盲模式",
	["opt_colorblindmode_desc"] = "將指南、箭頭與距離顏色替換為適合色盲的配色，同時強制使用更高對比的箭頭文字顏色。",
	["opt_colorblindmode_off"] = "關閉",
	["opt_colorblindmode_protanopia"] = "紅色盲",
	["opt_colorblindmode_deuteranopia"] = "綠色盲",
	["opt_colorblindmode_tritanopia"] = "藍色盲",
	["opt_colorblindmode_global"] = "全域",
	["opt_colorblindmode_custom"] = "自訂",
	["opt_arrowcolor_far"] = "遠",
	["opt_arrowcolor_mid"] = "中",
	["opt_arrowcolor_near"] = "近",
	["opt_simplifyarrownouncolors"] = "簡化箭頭文字顏色",
	["opt_simplifyarrownouncolors_desc"] = "為箭頭標籤使用更清晰、對比更高的顏色。",
	["opt_about_heading"] = "適用於 WoTLK 3.3.5a 的 Zygor Guides Viewer Remastered",
	["opt_about_support"] = "支援",
	["opt_about_diag"] = "提示：`/zygor status` 與 `/zygor debug` 可協助排錯。",
	["opt_showminimapicons"] = "顯示小地圖圖示",
	["opt_showminimapicons_desc"] = "在小地圖上顯示圖示",
	["opt_iconalpha"] = "圖示透明度",
	["opt_iconalpha_desc"] = "地圖標記圖示的透明度",
	["opt_iconsize"] = "圖示大小",
	["opt_iconsize_desc"] = "地圖上圖示的大小",
	["opt_arrowshow"] = "顯示箭頭",
	["opt_arrowshow_desc"] = "顯示或隱藏內建路徑點箭頭。",
	["opt_arrowcolormode_direction"] = "方向",
	["opt_arrowcolormode_distance"] = "距離",
	["opt_arrowtextoutline"] = "箭頭文字外框",
	["opt_arrowtextoutline_desc"] = "選擇路徑點箭頭文字的外框強度。",
	["opt_arrowtextoutline_default"] = "預設",
	["opt_arrowtextoutline_strong"] = "強",
	["opt_arrowtextoutline_reduced"] = "弱",
	["opt_remasterpointeronlegacy"] = "在舊版外觀使用重製指標",
	["opt_remasterpointeronlegacy_desc"] = "啟用後，舊版外觀會使用重製版路徑點箭頭樣式。",
	["opt_resetarrowposition"] = "重設箭頭位置",
	["opt_resetarrowposition_desc"] = "將路徑點箭頭重設為預設位置。",
	["opt_foglightdebug"] = "（除錯）檢查 foglight",
	["opt_foglightdebug_desc"] = "檢查目前地圖的 foglight",
	["opt_travelsystem_intro"] = "選擇如何處理旅行與路徑點提供者。",
	["opt_mapswaypoints_intro"] = "設定地圖標記與內建箭頭外觀。",
	["opt_notifications_intro"] = "設定步驟推進時的視覺通知提示。",
	["opt_actionbuttons_intro"] = "設定目標圖示與互動式步驟顯示。",
	["frame_toolbar_guides"] = "指南",
	["frame_toolbar_guides_click"] = "開啟指南選單",
	["frame_toolbar_guides_right"] = "開啟指南管理器",
	["frame_toolbar_close"] = "關閉",
	["frame_toolbar_close_click"] = "關閉",
	["frame_toolbar_settings"] = "設定",
	["frame_toolbar_settings_click"] = "開啟快速選單",
	["frame_toolbar_settings_right"] = "開啟指南管理器設定",
	["frame_toolbar_stepview"] = "步驟檢視",
	["frame_toolbar_stepview_showall"] = "顯示全部",
	["frame_toolbar_stepview_showonly"] = "只顯示 |cffffffff%s|r",
	["frame_toolbar_stepview_setcount"] = "設定步驟數量",
	["frame_toolbar_unlock"] = "解除鎖定視窗",
	["frame_toolbar_unlock_click"] = "解除鎖定",
	["frame_toolbar_lock"] = "鎖定視窗",
	["frame_toolbar_lock_click"] = "鎖定",
	["frame_title_default"] = "Zygor Guides",
	["frame_tab_guides"] = "指南",
	["frame_tab_spots"] = "點位",
} end)

local plurals = {
}

ZygorGuidesViewer_L("Specials", "zhTW", function() return {
	["plural"] = function (word)
		return word
	end,
	['contract_mobs'] = false,
	['contract_mobs_old'] = function(mobs)
			local start,ending

			if not mobs[1].name and type(mobs)=="table" then
				local l=mobs
				mobs={}
				for i=1,#l do mobs[i]={name=l[i]} end
			end
			local common,all
			for i=1,50 do
				common = mobs[1].name:sub(1,i)
				all=true
				for m=2,#mobs do
					if mobs[m].name:find(common)~=1 then
						all=false
						break
					end
				end
				if not all then
					common = common:sub(1,-2)
					break
				end
			end
			if common:sub(-1)==" " then common = common:sub(1,-2) end
			start=common

			for i=1,50 do
				common = mobs[1].name:sub(-i)
				all=true
				for m=2,#mobs do
					if mobs[m].name:sub(-i)~=common then
						all=false
						break
					end
				end
				if not all then
					common = common:sub(2)
					break
				end
			end
			if common:sub(1,1)==" " then common = common:sub(2) end
			ending=common

			if #start>#ending and #start>3 then
				return ZygorGuidesViewer_L("Specials")['contract_mobs_start'](start)
			elseif #ending>#start and #ending>3 then
				return ZygorGuidesViewer_L("Specials")['contract_mobs_end'](ending)
			else
				return nil
			end
		end,
	['contract_mobs_start'] = function(s) return ZygorGuidesViewer_L("Specials")['plural'](s) end,
	['contract_mobs_end'] = function(s)
		return ZygorGuidesViewer_L("Specials")['plural'](s)
	end,
} end)

ZygorGuidesViewer_L("G_string", "zhTW", function() return {
	["blabla"] = TRUE,
} end)

ZygorGuidesViewer_L("Main", "zhTW", function() return {
	["mainframe_guide"] = "選擇一個指南：",
	["mainframe_notloaded"] = "沒有載入升級指南。",
	["mainframe_notselected"] = "已載入 %d 個指南。|n請從上方清單中選擇一個指南。",
	["opt_group_main"] = "主要設定",
	["opt_browse"] = "切換視窗",
	["opt_browse_desc"] = "切換 Zygor 指南視窗的顯示狀態。",
	["opt_autosizemini"] = "自動調整大小",
	["opt_autosizemini_desc"] = "自動調整迷你視窗的高度。",
	["opt_colorborder"] = "步驟視窗邊框著色",
	["opt_colorborder_desc"] = "使用步驟視窗邊框顏色來表示整個步驟的完成狀態。",
	["opt_minimapnotedesc"] = "顯示路徑點說明",
	["opt_minimapnotedesc_desc"] = "不僅在路徑點提示中顯示相關路徑點說明，也在迷你視窗中顯示。",
	["opt_showallsteps"] = "折疊模式",
	["opt_showallsteps_desc"] = "只顯示目前步驟與接下來的幾個步驟，而不是整個指南。",
	["opt_showgoals"] = "顯示步驟目標",
	["opt_showgoals_desc"] = "在迷你視窗中顯示步驟完成目標。",
	["frame_selectguide"] = "選擇指南",
	["frame_selectguide_left"] = "請在左側選擇一個指南。",
	["frame_toolbar_stepview_options"] = "步驟檢視選項",
	["targetpreview_level"] = "等級",
	["targetpreview_class_boss"] = "首領",
	["targetpreview_class_elite"] = "精英",
	["targetpreview_class_rareelite"] = "稀有精英",
	["targetpreview_class_rare"] = "稀有",
	["targetpreview_title"] = "目標預覽",
	["targetpreview_title_locked"] = "目標預覽",
	["targetpreview_role_talk"] = "交談",
	["targetpreview_role_kill"] = "擊殺",
	["targetpreview_hint"] = "點擊以固定\n此目標。",
	["targetpreview_hint_empty"] = "此步驟目前沒有啟用的交談或擊殺目標。",
	["targetpreview_empty_name"] = "無目標",
	["popup_accept"] = "接受",
	["popup_decline"] = "拒絕",
	["actionbutton_bar_title"] = "拖曳以移動動作按鈕",
	["actionbutton_bar_title_locked"] = "動作按鈕",
	["actionbutton_tooltip_talk"] = "選取 %s 並嘗試為其標記綠色三角形。",
	["actionbutton_tooltip_kill"] = "選取 %s 並嘗試為其標記骷髏。",
	["actionbutton_tooltip_script"] = "執行目前步驟的腳本巨集。",
	["actionbutton_tooltip_petaction"] = "使用建議的寵物動作。",
	["gearfinder_title"] = "裝備查找器",
	["gearfinder_no_upgrade"] = "未找到升級",
	["gearfinder_load_guide"] = "載入指南",
	["gearfinder_suggested_dungeon"] = "建議副本：",
	["gearfinder_refresh"] = "點擊重新整理",
	["gearfinder_status_searching"] = "正在搜尋升級%s",
	["gearfinder_status_searching_future"] = "正在搜尋未來升級%s",
	["gearfinder_label_dungeon"] = "副本：",
	["gearfinder_label_unknown"] = "未知",
	["gearfinder_label_inbags"] = "背包中：",
	["gearfinder_label_score"] = "分數：%d",
	["gearfinder_label_score_value"] = "%.1f 分",
	["gearfinder_label_equipped"] = "已裝備",
	["gearfinder_label_empty"] = "空欄位",
	["gearfinder_upgrade_percent"] = "+%d%% 提升",
	["gearfinder_upgrade_percent_short"] = "%+.1f%%",
	["gearfinder_label_new_item"] = "新物品",
	["gearfinder_label_delta_score"] = "%+.1f 分",
	["gearfinder_label_best_gains"] = "最佳提升：%s",
	["gearfinder_label_found"] = "目前最佳：",
	["gearfinder_label_future"] = "未來：",
	["gearfinder_items_found"] = "找到 %d 件物品",
	["itemscore_ae_equip"] = "裝備 %s",
	["itemscore_ae_over"] = " 取代 %s",
	["itemscore_ae_equip1"] = "替換此物品",
	["itemscore_ae_equip2"] = "裝備此物品",
	["itemscore_ae_with"] = "用",
	["itemscore_ae_accept"] = "裝備",
	["itemscore_ae_decline"] = "暫時不要",
	["itemscore_ae_report_tip"] = "按住 Shift 並點擊可查看詳細裝備報告。\n已拒絕的物品將不再建議。",
	["itemscore_ae_build"] = "天賦配置",
	["itemscore_questitem1"] = "任務需要此物品。",
	["itemscore_questitem2"] = "要為目前任務步驟裝備它嗎？",
	["itemscore_questitem3"] = "要重新裝備先前的物品嗎？",
	["notifcenter_gear_title"] = "裝備顧問",
	["notifcenter_gear_text"] = "發現升級",
	["notifcenter_gear_text_sl"] = "發現 %d 個升級",
	["notifcenter_gear_text_pl"] = "發現 %d 個升級",
	["notifcenter_gear_equipped"] = "%s 已裝備到 %s 欄位",
	["notifcenter_quest_text"] = "任務物品",
	["notifcenter_gen_popup_tooltip"] = "點擊開啟",
	["opt_itemscore_ae_clearednotupgrade"] = "已清空被拒絕的升級清單。",
	["opt_itemscore_warning"] = "編輯物品評分的屬性權重。數值越高，代表該屬性對你的專精越重要。",
	["opt_gear_title"] = "設定自動裝備評分與升級偵測。",
	["opt_gear_score_class"] = "職業：",
	["opt_gear_score_spec"] = "專精：",
	["opt_gear_sources"] = "裝備查找來源",
	["opt_gear_sources_dungeons"] = "副本",
	["opt_gear_sources_raids"] = "團隊副本",
	["opt_quickscan_warning"] = "快速掃描模式：未收集物品連結。",
	["opt_actionbar_enable"] = "啟用動作條",
	["opt_actionbar_enable_desc"] = "為目前步驟中的可互動目標顯示一個可移動的動作條。",
	["opt_inlinebuttons_enable"] = "啟用行內按鈕",
	["opt_inlinebuttons_enable_desc"] = "直接在步驟行中顯示交談或擊殺按鈕。當行圖示被停用或動作條被停用時，這些按鈕會隱藏。",
	["opt_actionbar_onlywhenneeded"] = "僅在需要時顯示",
	["opt_actionbar_onlywhenneeded_desc"] = "當目前步驟沒有可互動按鈕時隱藏動作條。",
	["opt_actionbar_locked"] = "鎖定動作條位置",
	["opt_actionbar_locked_desc"] = "禁止拖曳動作條。",
	["opt_actionbar_scale"] = "動作條縮放",
	["opt_actionbar_scale_desc"] = "動作條的縮放比例。",
	["opt_actionbar_size"] = "按鈕大小",
	["opt_actionbar_size_desc"] = "動作條中每個按鈕的大小。",
	["opt_actionbar_spacing"] = "按鈕間距",
	["opt_actionbar_spacing_desc"] = "動作條按鈕之間的間距。",
	["opt_actionbar_pinside"] = "停靠位置",
	["opt_actionbar_pinside_desc"] = "選擇動作條應停靠在檢視器的哪一側。",
	["opt_actionbar_pinside_top"] = "上方",
	["opt_actionbar_pinside_bottom"] = "下方",
	["opt_actionbar_pinside_left"] = "左側",
	["opt_actionbar_pinside_right"] = "右側",
	["opt_actionbar_resetanchor"] = "重設動作條位置",
	["opt_actionbar_resetanchor_desc"] = "將動作條重設為預設停靠位置。",
	["opt_actionbar_markers"] = "啟用目標標記",
	["opt_actionbar_markers_desc"] = "在可能時，嘗試為交談與擊殺目標設定團隊標記。",
	["opt_targetpreview_header"] = "目標預覽",
	["opt_targetpreview_intro"] = "為目前的交談或擊殺目標顯示一個可移動的預覽面板。",
	["opt_targetpreview_enable"] = "啟用目標預覽",
	["opt_targetpreview_enable_desc"] = "為目前步驟中的交談與擊殺目標顯示一個可移動面板。",
	["opt_targetpreview_onlywhenneeded"] = "僅在相關時顯示",
	["opt_targetpreview_onlywhenneeded_desc"] = "當目前步驟沒有交談或擊殺目標時隱藏預覽面板。",
	["opt_targetpreview_locked"] = "鎖定預覽位置",
	["opt_targetpreview_locked_desc"] = "禁止拖曳目標預覽面板。",
	["opt_targetpreview_scale"] = "預覽縮放",
	["opt_targetpreview_scale_desc"] = "目標預覽面板的縮放比例。",
	["opt_targetpreview_width"] = "預覽寬度",
	["opt_targetpreview_width_desc"] = "目標預覽面板的寬度。",
	["opt_targetpreview_height"] = "預覽高度",
	["opt_targetpreview_height_desc"] = "目標預覽面板的高度。",
	["opt_targetpreview_pinside"] = "停靠位置",
	["opt_targetpreview_pinside_desc"] = "選擇目標預覽應停靠在檢視器的哪一側。",
	["opt_targetpreview_mode"] = "預覽模式",
	["opt_targetpreview_mode_desc"] = "選擇預覽應優先顯示即時 3D 模型、資訊卡片，或同時顯示兩者。",
	["opt_targetpreview_mode_hybrid"] = "混合",
	["opt_targetpreview_mode_model"] = "僅 3D",
	["opt_targetpreview_mode_card"] = "僅資訊卡片",
	["opt_targetpreview_resetanchor"] = "重設預覽位置",
	["opt_targetpreview_resetanchor_desc"] = "將目標預覽面板重設為預設停靠位置。",
	["gold_app_no_goldguide"] = "開啟金幣指南（/zgold）以載入趨勢資料。",
	["gold_app_no_goldguide_short"] = "開啟 /zgold 以載入指南。",
	["gold_app_no_goldguide_tooltip"] = "開啟金幣指南視窗以從拍賣場掃描初始化趨勢資料。",
	["gold_app_no_scan_data"] = "目前價格未知。請掃描拍賣場。",
	["gold_app_no_scan_data_short"] = "目前價格未知。",
	["gold_app_no_scan_data_tooltip"] = "掃描拍賣場以收集目前價格。",
	["gold_app_no_servertrends"] = "沒有趨勢資料。請每天掃描以建立趨勢。",
	["gold_app_no_servertrends_short"] = "沒有趨勢資料。",
	["gold_app_no_servertrends_tooltip"] = "每天掃描拍賣場以建立價格趨勢。",
	["gold_app_old_scan_data"] = "目前價格資料已過期。請重新掃描。",
	["gold_app_old_scan_data_short"] = "目前價格資料已過期。",
	["gold_app_old_scan_data_tooltip"] = "重新掃描拍賣場以更新目前價格資料。",
	["gold_app_old_servertrends"] = "趨勢資料已過期。請更頻繁地掃描。",
	["gold_app_old_servertrends_short"] = "趨勢資料已過期。",
	["gold_app_old_servertrends_tooltip"] = "更頻繁地掃描拍賣場以保持趨勢資料最新。",
	["gold_app_trend_tooltip"] = "根據最近伺服器趨勢與目前掃描價格得出的價格方向。",
	["gold_auctions_error_noresults"] = "未找到拍賣結果。",
	["gold_crafting_error_noprofessions"] = "沒有製造型專業。",
	["gold_crafting_error_noresults"] = "未找到獲利的製作結果。",
	["gold_crafting_error_recipesnotcached"] = "配方資料尚未快取。",
	["gold_expertmode_easylabel"] = "簡易模式",
	["gold_expertmode_easytooltip"] = "顯示更簡單且可立即執行的建議。",
	["gold_expertmode_expertlabel"] = "專家模式",
	["gold_expertmode_experttooltip"] = "顯示更詳細且進階的金幣策略。",
	["gold_expertmode_generictooltip"] = "切換金幣指南顯示的策略類型。",
	["gold_farming_error_noitemtype"] = "未選擇物品類型。",
	["gold_farming_error_noresults"] = "未找到符合條件的刷取結果。",
	["gold_gathering_error_all_noprofessions"] = "沒有採集專業。",
	["gold_gathering_error_one_noresults"] = "未找到此專業的結果。",
	["gold_gathering_error_one_noskillin"] = "此區域所需技能不足。",
	["gold_gathering_error_one_noskillin_skills"] = "此區域所需技能：%s",
	["gold_gathering_error_one_nothing"] = "沒有可顯示的採集結果。",
	["gold_gathering_error_prof"] = "專業：%s",
	["gold_gathering_no_results"] = "未找到採集結果。",
	["gold_general_open_window1"] = "開啟金幣指南以",
	["gold_general_open_window2"] = "查看完整資訊。",
	["stepgoal_arrive"] = "到達",
	["stepgoal_cast"] = "施放",
	["stepgoal_click"] = "點擊",
	["stepgoal_fly"] = "飛行",
	["waypointaddon_disconnecting"] = "正在中斷連線",
	["gb_opt_optimization"] = "最佳化",
	["gb_opt_desc_optimization"] = "影響效能的設定、箭頭更新頻率，以及未來的最佳化控制。",
	["opt_optimization_intro"] = "調整內建箭頭的效能相關行為，並為未來巫妖王之怒專用最佳化選項預留空間。",
	["opt_optimization_arrow_header"] = "箭頭效能",
	["opt_optimization_arrow_desc"] = "控制內建路徑箭頭的更新頻率。較低頻率可減少 CPU 使用量，較高頻率則更平滑。",
	["opt_arrow_refresh_rate"] = "箭頭更新頻率",
	["opt_arrow_refresh_rate_desc"] = "控制內建路徑箭頭更新的頻率。較低值可減少 CPU 使用量，較高值可提升流暢度。",
	["opt_arrow_refresh_rate_20"] = "20 FPS（舊預設）",
	["opt_arrow_refresh_rate_30"] = "30 FPS（建議）",
	["opt_arrow_refresh_rate_60"] = "60 FPS（平滑）",
	["opt_arrow_refresh_rate_unlimited"] = "無限制（每幀）",
	["opt_optimization_internal_only"] = "此設定僅在啟用內建路徑指示器時影響內建路徑箭頭。",
	["opt_optimization_routing_header"] = "路線規劃",
	["opt_optimization_routing_desc"] = "控制內建旅行系統計算與準備路線的積極程度。",
	["opt_pathfinding_speed"] = "路線計算預算",
	["opt_pathfinding_speed_desc"] = "控制 LibRover 在建構路線時每次更新執行的工作量。較低值可減少 CPU 峰值，較高值可更快完成重新計算。",
	["opt_pathfinding_speed_slow"] = "慢（最低 CPU）",
	["opt_pathfinding_speed_medium"] = "中",
	["opt_pathfinding_speed_fast"] = "快（更新最快）",
	["opt_travel_full_linking_startup"] = "啟動時建立完整旅行連結",
	["opt_travel_full_linking_startup_desc"] = "登入時預先計算更多旅行連結。這可以提升之後的路線反應速度，但會增加啟動耗時。",
	["opt_optimization_memory_header"] = "記憶體與載入",
	["opt_optimization_memory_desc"] = "未來最佳化目標：透過更有選擇地載入指南與步驟來降低初始記憶體占用。本次未實作。",
	["opt_optimization_diagnostics_header"] = "診斷",
	["opt_optimization_diagnostics_desc"] = "未來最佳化目標：提供輕量級 FPS 或記憶體診斷，用於分析卡頓與載入尖峰。本次未實作。",
} end)
