ZGV.Gold.guides_loaded=true
if ZGV:DoMutex("GoldFarmC") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Clefthoof Meat")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Ravager Flesh")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Bat Flesh, Crunchy Spider Leg")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Bear Flank")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Buzzard Meat")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Chunk o' Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Netherweave Cloth, Jaggal Clam Meat, Jaggal Pearl, Fish Oil, Shiny Fish Scales, Unidentified Plant Parts")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Raptor Ribs")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Serpent Flesh")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Talbuk Venison")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Warped Flesh")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Strange Spores, Fertile Spores, Unidentified Plant Parts")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Moongraze Stag Tenderloin")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Lynx Meat")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Sunfury Signet, Arcane Tome, Netherweave Cloth")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Mark of Kil'jaeden, Fel Armament, Netherweave Cloth, Mote of Shadow")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Chilled Meat")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Chunk o' Mammoth")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Northern Egg")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Rhino Meat")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Shoveltusk Flank")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Succulent Clam Meat")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Worg Haunch")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Worm Meat")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Crystallized Air")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Crystallized Earth")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Crystallized Fire")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Crystallized Life")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Crystallized Shadow")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Crystallized Water")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Frostweave Cloth")